<?php $dateLabel=fn($v)=>$v?date('d/m/Y à H:i',strtotime($v)):'Non renseignée'; ?>
<header class="campaign-drawer-heading"><div class="prod-panel-heading"><span class="prod-panel-icon" aria-hidden="true"><i class="bi bi-clipboard-data"></i></span><div><p class="page-kicker">DÉTAIL DE PRODUCTION</p><h2 id="productionDetailTitle"><?=e($b['machine_name'])?></h2><small><?=e($b['batch_number'])?></small></div></div><button class="modal-close" type="button" data-prod-close aria-label="Fermer">×</button></header>
<div class="campaign-drawer-body">
<section class="prod-detail-overview"><div><span class="campaign-status prod-status-<?=e($b['status'])?>"><?=e($states[$b['status']]??$b['status'])?></span><p>Quantité chargée</p><strong><?=e($kg($b['actual_input_quantity_kg']))?></strong><small>Depuis <?=e($b['silo_name'])?></small></div><div class="prod-detail-machine"><?php $machine=['machine_type'=>'main','status'=>'active'];require view_path('machines.illustration');?></div></section>
<section class="prod-detail-section"><h3><i class="bi bi-pie-chart" aria-hidden="true"></i> Bilan de production</h3><?php if($todo):?><p class="prod-detail-empty">Les résultats n’ont pas encore été saisis.</p><?php elseif($b['status']==='cancelled'):?><p class="prod-detail-empty">Lot annulé · résultats conservés pour consultation.</p><dl class="feed-detail-facts"><div><dt>Farine</dt><dd><?=e($kg($b['output_quantity_kg']))?></dd></div><div><dt>Déchets</dt><dd><?=e($kg($b['waste_quantity_kg']))?></dd></div></dl><?php else:require view_path('production.balance');?><p class="prod-detail-caption">Rendement : <?=(float)$b['actual_input_quantity_kg']>0?e(number_format(100*(float)$b['output_quantity_kg']/(float)$b['actual_input_quantity_kg'],1,',',' ')).' %':'Non disponible'?> · Tolérance : <?=e($b['variance_tolerance_percent'])?> %</p><?php endif;?></section>
<section class="prod-detail-section"><h3><i class="bi bi-clock-history" aria-hidden="true"></i> Traçabilité</h3><dl class="feed-detail-facts"><?php foreach(['Bon de sortie silo'=>$b['bss_number']?:'Non référencé','Responsable'=>$b['agent_name']?:'Non renseigné','Début'=>$dateLabel($b['started_at']),'Fin'=>$dateLabel($b['ended_at']),'Validateur'=>$b['validator_name']?:'En attente de validation'] as$label=>$value):?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl></section>
<section class="prod-detail-section"><h3><i class="bi bi-recycle" aria-hidden="true"></i> Déchets par type</h3><?php if($b['waste_lines']):?><dl class="prod-waste-breakdown"><?php foreach($b['waste_lines'] as$line):?><div><dt><?=e($line['name'])?></dt><dd><?=e($kg($line['quantity_kg']))?></dd></div><?php endforeach;?></dl><?php else:?><p class="prod-detail-empty">Aucun déchet renseigné.</p><?php endif;?></section>
<section class="prod-detail-section"><h3><i class="bi bi-chat-left-text" aria-hidden="true"></i> Justification de l’écart</h3><p class="feed-detail-observation"><?=e($b['variance_justification']?:'Aucune justification renseignée.')?></p></section>
</div><footer class="feed-detail-footer"><?php if($edit):?><button class="btn-primary" type="button" data-prod-edit="<?=e($b['id'])?>" data-workspace-modal-open="productionEditor"><?=$todo?'Saisir les résultats':'Corriger les résultats'?></button><?php endif;?><button class="btn-secondary" type="button" data-prod-close>Fermer</button></footer>
