<?php
class KpiService
{
 private $db;private $filters;private $siteId;
 public function __construct(PDO$db=null,array$filters=[]){$this->db=$db?:Database::getInstance()->connection();$this->filters=$this->normalize($filters);$this->siteId=$this->resolveSite($this->filters['site_id']);}
 public function filters(){return$this->filters+['effective_site_id'=>$this->siteId,'consolidated'=>$this->siteId===null];}
 public function catalog(){return[
  'agricultural_yield'=>['label'=>'Rendement agricole','unit'=>'t/ha','component'=>'agriculture'],
  'roof_yield'=>['label'=>'Rendement ROOF','unit'=>'%','component'=>'production'],
  'production_variance'=>['label'=>'Écart de production','unit'=>'%','component'=>'production'],
  'mortality_rate'=>['label'=>'Taux de mortalité','unit'=>'%','component'=>'livestock'],
  'gmq'=>['label'=>'GMQ','unit'=>'kg/jour','component'=>'livestock'],
  'fish_yield'=>['label'=>'Rendement piscicole','unit'=>'kg/m²','component'=>'livestock'],
  'available_stock'=>['label'=>'Stocks disponibles','unit'=>'kg','component'=>'finished-stocks'],
  'transit_stock'=>['label'=>'Stocks en transit','unit'=>'kg','component'=>'transfers'],
  'stock_days'=>['label'=>'Jours de stock emballages','unit'=>'jours','component'=>'empty-packaging'],
  'breakage_rate'=>['label'=>'Taux de casse emballages','unit'=>'%','component'=>'empty-packaging'],
  'waste_available'=>['label'=>'Déchets disponibles','unit'=>'kg','component'=>'waste'],
  'pellet_yield'=>['label'=>'Rendement pelletisation','unit'=>'%','component'=>'pelletization'],
  'cost_price'=>['label'=>'Coût de revient moyen','unit'=>'/kg','component'=>'butchery'],
  'budget_consumption'=>['label'=>'Consommation budgétaire','unit'=>'%','component'=>'budgets'],
  'fuel_consumption'=>['label'=>'Consommation carburant','unit'=>'L','component'=>'fuel-logistics'],
  'pending_movements'=>['label'=>'Mouvements en attente','unit'=>'op.','component'=>'reports'],
  'open_nonconformities'=>['label'=>'Non-conformités non résolues','unit'=>'NC','component'=>'reports']];}
 public function summary(){ $out=[];foreach($this->catalog()as$code=>$meta){if(!$this->visible($meta['component']))continue;$rows=$this->detail($code);$value=$this->aggregate($code,$rows);$out[]=['code'=>$code,'label'=>$meta['label'],'unit'=>$meta['unit'],'value'=>$value,'count'=>count($rows),'detail_path'=>'analytics/'.$code,'status'=>$this->tone($code,$value),'validated_only'=>true,'chart'=>$this->chartSeries($code,$rows)];}return$out;}
 public function detail($code){if(!isset($this->catalog()[$code])||!$this->visible($this->catalog()[$code]['component']))throw new RuntimeException('Indicateur non autorisé.');$p=['start'=>$this->filters['start_date'],'end'=>$this->filters['end_date']];$site=function($column)use(&$p){if($this->siteId===null)return'';$p['site']=$this->siteId;return' AND '.$column.'=:site';};
  switch($code){
   case'agricultural_yield':return$this->rows("SELECT h.harvest_number reference,s.code site,DATE(h.harvested_at) operation_date,h.net_weight_kg,cp.actual_area_ha,CASE WHEN cp.actual_area_ha>0 THEN h.net_weight_kg/1000/cp.actual_area_ha ELSE 0 END value FROM agricultural_harvests h JOIN agricultural_campaign_plots cp ON cp.id=h.campaign_plot_id JOIN sites s ON s.id=h.site_id WHERE h.status='validated' AND h.deleted_at IS NULL AND DATE(h.validated_at) BETWEEN :start AND :end".$site('h.site_id'),$p);
   case'roof_yield':return$this->rows("SELECT b.batch_number reference,s.code site,DATE(b.ended_at) operation_date,b.actual_input_quantity_kg,b.output_quantity_kg,b.yield_percent value FROM production_batches b JOIN sites s ON s.id=b.site_id WHERE b.status='validated' AND b.deleted_at IS NULL AND DATE(b.ended_at) BETWEEN :start AND :end".$site('b.site_id'),$p);
   case'production_variance':return$this->rows("SELECT b.batch_number reference,s.code site,DATE(b.ended_at) operation_date,b.variance_quantity_kg,b.variance_tolerance_percent,b.variance_percent value FROM production_batches b JOIN sites s ON s.id=b.site_id WHERE b.status='validated' AND b.deleted_at IS NULL AND DATE(b.ended_at) BETWEEN :start AND :end".$site('b.site_id'),$p);
   case'mortality_rate':return$this->rows("SELECT b.batch_number reference,s.code site,DATE(m.movement_at) operation_date,m.quantity_heads,CASE WHEN b.initial_heads>0 THEN m.quantity_heads/b.initial_heads*100 ELSE 0 END value FROM livestock_head_movements m JOIN livestock_batches b ON b.id=m.batch_id JOIN sites s ON s.id=b.site_id WHERE m.movement_type='mortality' AND DATE(m.movement_at) BETWEEN :start AND :end".$site('b.site_id'),$p);
   case'gmq':return$this->rows("SELECT b.batch_number reference,s.code site,DATE(w.weighed_at) operation_date,b.initial_average_weight_kg,w.average_weight_kg,CASE WHEN DATEDIFF(DATE(w.weighed_at),b.started_at)>0 THEN (w.average_weight_kg-b.initial_average_weight_kg)/DATEDIFF(DATE(w.weighed_at),b.started_at) ELSE 0 END value FROM livestock_weighings w JOIN livestock_batches b ON b.id=w.batch_id JOIN sites s ON s.id=b.site_id WHERE DATE(w.weighed_at) BETWEEN :start AND :end AND b.status<>'cancelled'".$site('b.site_id'),$p);
   case'fish_yield':return$this->rows("SELECT f.catch_number reference,s.code site,DATE(f.validated_at) operation_date,f.net_weight_kg,f.yield_kg_m2 value FROM fish_catches f JOIN livestock_batches b ON b.id=f.batch_id JOIN sites s ON s.id=b.site_id WHERE f.status='validated' AND DATE(f.validated_at) BETWEEN :start AND :end".$site('b.site_id'),$p);
   case'available_stock':return$this->rows("SELECT CONCAT(p.code,'/',COALESCE(b.name,'Vrac')) reference,s.code site,CURDATE() operation_date,(f.total_weight_kg-f.reserved_weight_kg) value FROM finished_stocks f JOIN products p ON p.id=f.product_id LEFT JOIN bag_formats b ON b.id=f.bag_format_id JOIN sites s ON s.id=f.site_id WHERE f.status IN('active','validated') AND f.deleted_at IS NULL".$site('f.site_id'),$p);
   case'transit_stock':return$this->rows("SELECT t.transfer_number reference,s.code site,DATE(COALESCE(t.approved_at,t.requested_at)) operation_date,SUM(i.shipped_kg-i.received_kg) value FROM stock_transfers t JOIN stock_transfer_items i ON i.transfer_id=t.id JOIN sites s ON s.id=t.source_site_id WHERE t.status IN('partially_shipped','in_transit','partially_received','quality_control','return_pending') AND t.deleted_at IS NULL".$site('t.source_site_id')." GROUP BY t.id,s.code",$p);
   case'stock_days':return$this->rows("SELECT i.code reference,s.code site,CURDATE() operation_date,st.physical_quantity+st.operational_quantity stock_quantity,CASE WHEN COALESCE(c.daily_use,0)>0 THEN (st.physical_quantity+st.operational_quantity)/c.daily_use ELSE 0 END value FROM empty_packaging_stocks st JOIN empty_packaging_items i ON i.id=st.packaging_item_id JOIN sites s ON s.id=st.site_id LEFT JOIN(SELECT m.stock_id,SUM(m.quantity)/GREATEST(1,DATEDIFF(:period_end,:period_start)+1) daily_use FROM empty_packaging_movements m WHERE m.movement_type='consumption' AND DATE(m.movement_at) BETWEEN :start AND :end GROUP BY m.stock_id)c ON c.stock_id=st.id WHERE st.status='active' AND st.deleted_at IS NULL".$site('st.site_id'),array_merge($p,['period_start'=>$this->filters['start_date'],'period_end'=>$this->filters['end_date']]));
   case'breakage_rate':return$this->rows("SELECT i.code reference,s.code site,MAX(DATE(m.movement_at)) operation_date,SUM(CASE WHEN m.movement_type='defective' THEN m.quantity ELSE 0 END)/NULLIF(SUM(CASE WHEN m.movement_type IN('purchase_receipt','transfer_in') THEN m.quantity ELSE 0 END),0)*100 value FROM empty_packaging_movements m JOIN empty_packaging_stocks st ON st.id=m.stock_id JOIN empty_packaging_items i ON i.id=st.packaging_item_id JOIN sites s ON s.id=st.site_id WHERE DATE(m.movement_at) BETWEEN :start AND :end".$site('st.site_id')." GROUP BY st.id,i.code,s.code",$p);
   case'waste_available':return$this->rows("SELECT CONCAT(wt.code,'/',COALESCE(pb.batch_number,'-')) reference,s.code site,DATE(ws.available_at) operation_date,ws.quantity_kg value FROM waste_stocks ws JOIN waste_types wt ON wt.id=ws.waste_type_id LEFT JOIN production_batches pb ON pb.id=ws.production_batch_id JOIN sites s ON s.id=ws.site_id WHERE ws.quantity_kg>0 AND ws.storage_status IN('available','buffer') AND ws.deleted_at IS NULL".$site('ws.site_id'),$p);
   case'pellet_yield':return$this->rows("SELECT o.order_number reference,s.code site,DATE(o.ended_at) operation_date,o.actual_input_kg,o.output_quantity_kg,o.yield_percent value FROM pellet_orders o JOIN sites s ON s.id=o.site_id WHERE o.status='validated' AND o.deleted_at IS NULL AND DATE(o.ended_at) BETWEEN :start AND :end".$site('o.site_id'),$p);
   case'cost_price':return$this->rows("SELECT o.order_number reference,s.code site,DATE(o.production_date) operation_date,o.total_cost,o.cost_per_kg value FROM butchery_orders o JOIN sites s ON s.id=o.site_id WHERE o.status='validated' AND o.deleted_at IS NULL AND o.production_date BETWEEN :start AND :end".$site('o.site_id'),$p);
   case'budget_consumption':return$this->rows("SELECT b.budget_number reference,s.code site,MAX(e.expense_date) operation_date,bl.validated_amount,COALESCE(SUM(e.amount),0) realized,CASE WHEN bl.validated_amount>0 THEN COALESCE(SUM(e.amount),0)/bl.validated_amount*100 ELSE 0 END value FROM budgets b JOIN budget_lines bl ON bl.budget_id=b.id JOIN sites s ON s.id=b.site_id LEFT JOIN budget_expenses e ON e.budget_line_id=bl.id AND e.status='approved' AND e.expense_date BETWEEN :start AND :end AND e.deleted_at IS NULL WHERE b.status IN('active','replaced') AND b.deleted_at IS NULL".$site('b.site_id')." GROUP BY bl.id,b.budget_number,s.code,bl.validated_amount",$p);
   case'fuel_consumption':return$this->rows("SELECT d.distribution_number reference,s.code site,DATE(d.distributed_at) operation_date,d.quantity value,d.normative_quantity,d.variance_percent,d.is_abnormal FROM fuel_distributions d JOIN sites s ON s.id=d.site_id WHERE DATE(d.distributed_at) BETWEEN :start AND :end".$site('d.site_id'),$p);
   case'pending_movements':return$this->pending($p,$site);
   case'open_nonconformities':return$this->nonconformities($p);
  }return[];
 }
 private function pending($p,$site){$rows=[];$sets=[['stock_transfers','source_site_id','requested_at',"status NOT IN('accepted','rejected','returned','closed','cancelled')",'transfer_number'],['production_batches','site_id','started_at',"status IN('pending','in_progress','results_submitted','pending_additional_approval')",'batch_number'],['agricultural_harvests','site_id','harvested_at',"status IN('draft','drying','submitted')",'harvest_number'],['logistics_missions','ordering_site_id','planned_start',"status NOT IN('settled','cancelled')",'mission_number']];foreach($sets as$x){if(!$this->table($x[0]))continue;$q=$p;$cl=$this->siteId===null?'':" AND {$x[1]}=:site";if($this->siteId!==null)$q['site']=$this->siteId;$found=$this->rows("SELECT {$x[4]} reference,(SELECT code FROM sites WHERE id={$x[1]}) site,DATE({$x[2]}) operation_date,1 value FROM {$x[0]} WHERE {$x[3]} AND DATE({$x[2]})<=:end{$cl}",$q);$rows=array_merge($rows,$found);}return$rows;}
 private function nonconformities($p){$rows=[];if($this->table('transfer_non_conformities')){$q=$p;$cl=$this->siteId===null?'':' AND t.source_site_id=:site';if($this->siteId!==null)$q['site']=$this->siteId;$rows=array_merge($rows,$this->rows("SELECT n.reference,s.code site,DATE(n.created_at) operation_date,1 value,n.description FROM transfer_non_conformities n JOIN stock_transfers t ON t.id=n.transfer_id JOIN sites s ON s.id=t.source_site_id WHERE n.status='open' AND DATE(n.created_at) BETWEEN :start AND :end{$cl}",$q));}if($this->table('weighbridge_non_conformities')){$q=['start'=>$p['start'],'end'=>$p['end']];$cl=$this->siteId===null?'':' AND w.site_id=:site';if($this->siteId!==null)$q['site']=$this->siteId;$rows=array_merge($rows,$this->rows("SELECT n.reference,s.code site,DATE(n.created_at) operation_date,1 value,n.description FROM weighbridge_non_conformities n JOIN weighings w ON w.id=n.weighing_id JOIN sites s ON s.id=w.site_id WHERE n.status NOT IN('closed','cancelled') AND n.deleted_at IS NULL AND DATE(n.created_at) BETWEEN :start AND :end{$cl}",$q));}return$rows;}
 private function aggregate($code,$rows){if(!$rows)return 0;$values=array_map(function($r){return(float)($r['value']??0);},$rows);if(in_array($code,['available_stock','transit_stock','waste_available','fuel_consumption','pending_movements','open_nonconformities'],true))return array_sum($values);return array_sum($values)/count($values);}
 private function chartSeries($code,$rows){$series=[];foreach($rows as$r){$series[]=['label'=>(string)($r['operation_date']??$r['reference']??''),'reference'=>(string)($r['reference']??''),'site'=>(string)($r['site']??''),'value'=>(float)($r['value']??0)];}usort($series,function($a,$b){return strcmp($a['label'],$b['label']);});$series=array_slice($series,-10);return['type'=>in_array($code,['available_stock','transit_stock','waste_available','pending_movements','open_nonconformities'],true)?'bar':'line','labels'=>array_column($series,'label'),'references'=>array_column($series,'reference'),'sites'=>array_column($series,'site'),'values'=>array_column($series,'value')];}
 private function visible($component){return Auth::can('analytics','read',$this->siteId)&&(Auth::can($component,'read',$this->siteId)||in_array($component,['reports'],true));}private function tone($code,$v){if(in_array($code,['production_variance','mortality_rate','breakage_rate','pending_movements','open_nonconformities'],true))return$v>0?'warning':'success';return'success';}
 private function normalize($f){$today=date('Y-m-d');$start=isset($f['start_date'])&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$f['start_date'])?$f['start_date']:date('Y-m-01');$end=isset($f['end_date'])&&preg_match('/^\d{4}-\d{2}-\d{2}$/',$f['end_date'])?$f['end_date']:$today;if($end<$start)$end=$start;return['start_date'=>$start,'end_date'=>$end,'site_id'=>isset($f['site_id'])?(string)$f['site_id']:''];}
 private function resolveSite($requested){if($requested==='all'&&Auth::canViewConsolidated())return null;if(ctype_digit($requested)&&Auth::canAccessSite($requested))return(int)$requested;return Auth::currentSiteId();}private function rows($sql,$p){try{$used=[];foreach($p as$k=>$v)if(strpos($sql,':'.$k)!==false)$used[$k]=$v;$q=$this->db->prepare($sql);$q->execute($used);return$q->fetchAll();}catch(PDOException$e){if(strpos($e->getMessage(),"doesn't exist")!==false||strpos($e->getMessage(),'Base table')!==false)return[];throw$e;}}private function table($name){$q=$this->db->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$name]);return(bool)$q->fetchColumn();}
}
