<?php

class WorkflowService
{
    private $db;
    private $states=['draft','submitted','pending_approval','approved','in_progress','received','rejected','cancelled','closed'];
    public function __construct(PDO $db=null){$this->db=$db?:Database::getInstance()->connection();}

    public function createForDocument($documentId,$amount,array $user)
    {
        $own=!$this->db->inTransaction();if($own){$this->db->beginTransaction();}
        try{$doc=$this->lockDocument($documentId);if(!$doc){throw new RuntimeException('Document introuvable.');}$existing=$this->lockInstanceByDocument($documentId);if($existing){if($own){$this->db->commit();}return $existing;}$rule=$this->selectRule($doc['document_type_id'],$doc['site_id'],$amount);if(!$rule){throw new RuntimeException('Aucune règle de validation applicable.');}$state=$this->normalizeState($doc['status']);$level=in_array($state,['approved','closed'],true)?(int)$rule['approval_levels']:0;
            $s=$this->db->prepare('INSERT INTO workflow_instances(workflow_definition_id,document_id,current_state,current_level,required_levels,amount,created_by,completed_at) VALUES(:rule,:document,:state,:level,:levels,:amount,:creator,:completed)');$s->execute(['rule'=>$rule['id'],'document'=>$documentId,'state'=>$state,'level'=>$level,'levels'=>$rule['approval_levels'],'amount'=>$amount,'creator'=>$user['id']??$doc['created_by'],'completed'=>in_array($state,['approved','closed'],true)?date('Y-m-d H:i:s'):null]);$id=$this->db->lastInsertId();$this->record($id,null,$state,'create',null,$user['id']??null,'Création instance');if($own){$this->db->commit();}return $this->get($id);
        }catch(Exception $e){if($own&&$this->db->inTransaction()){$this->db->rollBack();}throw$e;}
    }

    public function transition($instanceId,$action,array $user,$reason=null)
    {
        $this->db->beginTransaction();
        try{$instance=$this->lockInstance($instanceId);if(!$instance){throw new RuntimeException('Workflow introuvable.');}$doc=$this->lockDocument($instance['document_id']);Auth::requireSiteAccess($doc['site_id']);$this->lockBusinessEntity($doc['entity_type'],$doc['entity_id']);$from=$instance['current_state'];$to=$from;$level=null;
            if($action==='submit'){$this->expect($from,['draft','rejected']);$this->assertActor($instance,$user,'create');$to='submitted';if($from==='rejected'){$this->db->prepare('UPDATE workflow_instances SET attempt_number=attempt_number+1,current_level=0 WHERE id=:id')->execute(['id'=>$instanceId]);}}
            elseif($action==='request_approval'){$this->expect($from,['submitted']);$this->assertActor($instance,$user,'create');$to='pending_approval';}
            elseif($action==='approve'){$this->expect($from,['pending_approval']);if((int)$instance['created_by']===(int)$user['id']){throw new RuntimeException('Séparation des tâches: le créateur ne peut pas approuver.');}$level=(int)$instance['current_level']+1;$delegator=$this->assertApprover($instance,$doc,$level,$user);$this->insertDecision($instance,$level,$user['id'],$delegator,'approved',$reason);$to=$level>=(int)$instance['required_levels']?'approved':'pending_approval';}
            elseif($action==='reject'){$this->expect($from,['pending_approval']);if(trim((string)$reason)===''){throw new RuntimeException('Le motif du refus est obligatoire.');}if((int)$instance['created_by']===(int)$user['id']){throw new RuntimeException('Séparation des tâches: le créateur ne peut pas refuser.');}$level=(int)$instance['current_level']+1;$delegator=$this->assertApprover($instance,$doc,$level,$user);$this->insertDecision($instance,$level,$user['id'],$delegator,'rejected',$reason);$to='rejected';}
            elseif($action==='start'){$this->expect($from,['approved']);$this->requirePermission($user,'update',$doc['site_id']);$to='in_progress';}
            elseif($action==='receive'){$this->expect($from,['in_progress']);$this->requirePermission($user,'update',$doc['site_id']);$to='received';}
            elseif($action==='close'){$this->expect($from,['received','approved']);$this->requirePermission($user,'update',$doc['site_id']);$to='closed';}
            elseif($action==='cancel'){$this->expect($from,['draft','submitted','pending_approval','rejected','approved','in_progress']);if(in_array($from,['approved','in_progress'],true)&&trim((string)$reason)===''){throw new RuntimeException('Un motif est obligatoire après approbation.');}$this->requirePermission($user,'delete',$doc['site_id']);$to='cancelled';}
            else{throw new RuntimeException('Action de workflow inconnue.');}
            if($to===$from&&$action!=='approve'){throw new RuntimeException('Transition sans changement interdite.');}
            $newLevel=$action==='approve'?$level:(in_array($action,['reject'],true)?$instance['current_level']:$instance['current_level']);$completed=in_array($to,['approved','cancelled','closed'],true)?date('Y-m-d H:i:s'):null;
            $this->db->prepare('UPDATE workflow_instances SET current_state=:state,current_level=:level,completed_at=:completed,version=version+1 WHERE id=:id')->execute(['state'=>$to,'level'=>$newLevel,'completed'=>$completed,'id'=>$instanceId]);$this->db->prepare('UPDATE documents SET status=:status WHERE id=:id')->execute(['status'=>$to,'id'=>$doc['id']]);$this->record($instanceId,$from,$to,$action,$level,$user['id'],$reason);$this->notify($instanceId,$instance,$doc,$to,$user,$level);$this->db->commit();return $this->get($instanceId);
        }catch(Exception$e){$this->db->rollBack();throw$e;}
    }

    public function delegate(array$data,array$user){if((int)$data['delegator_id']===(int)$data['delegate_id']){throw new RuntimeException('Le délégataire doit être différent.');}if(strtotime($data['expires_at'])<=strtotime($data['starts_at'])){throw new RuntimeException('Période de délégation invalide.');}$this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO workflow_delegations(delegator_id,delegate_id,document_type_id,site_id,starts_at,expires_at,reason,created_by) VALUES(:from,:to,:type,:site,:starts,:expires,:reason,:creator)");$s->execute(['from'=>$data['delegator_id'],'to'=>$data['delegate_id'],'type'=>$data['document_type_id']?:null,'site'=>$data['site_id']?:null,'starts'=>$data['starts_at'],'expires'=>$data['expires_at'],'reason'=>$data['reason']?:null,'creator'=>$user['id']]);$id=(int)$this->db->lastInsertId();$this->log('workflow_delegate',$id,$user,$data);$this->db->commit();return$id;}catch(Exception$e){$this->db->rollBack();throw$e;}}
    public function get($id){$s=$this->db->prepare('SELECT * FROM workflow_instances WHERE id=:id');$s->execute(['id'=>$id]);return$s->fetch();}
    private function selectRule($type,$site,$amount){$s=$this->db->prepare("SELECT * FROM workflow_definitions WHERE status='active' AND deleted_at IS NULL AND (document_type_id=:type OR document_type_id IS NULL) AND (site_id=:site OR site_id IS NULL) AND (min_amount IS NULL OR min_amount<=:amount_min) AND (max_amount IS NULL OR max_amount>=:amount_max) ORDER BY (document_type_id IS NOT NULL) DESC,(site_id IS NOT NULL) DESC,priority DESC,id DESC LIMIT 1");$s->execute(['type'=>$type,'site'=>$site,'amount_min'=>$amount,'amount_max'=>$amount]);return$s->fetch();}
    private function assertApprover($instance,$doc,$level,$user){$hasPermission=$this->requirePermission($user,'validate',$doc['site_id'],false);$s=$this->db->prepare('SELECT required_role_id FROM workflow_steps WHERE workflow_definition_id=:definition AND level_number=:level');$s->execute(['definition'=>$instance['workflow_definition_id'],'level'=>$level]);$role=$s->fetchColumn();if(!$role){if(!$hasPermission){throw new RuntimeException('Permission workflow refusée.');}return null;}if($this->hasEffectiveRole($user['id'],$role,$doc['site_id'])){return null;}$s=$this->db->prepare("SELECT wd.delegator_id FROM workflow_delegations wd WHERE wd.delegate_id=:user AND wd.status='active' AND wd.deleted_at IS NULL AND wd.starts_at<=NOW() AND wd.expires_at>NOW() AND (wd.document_type_id IS NULL OR wd.document_type_id=:type) AND (wd.site_id IS NULL OR wd.site_id=:site) ORDER BY wd.id DESC");$s->execute(['user'=>$user['id'],'type'=>$doc['document_type_id'],'site'=>$doc['site_id']]);foreach($s->fetchAll(PDO::FETCH_COLUMN) as$delegator){if($this->hasEffectiveRole($delegator,$role,$doc['site_id'])){return$delegator;}}throw new RuntimeException('Approbateur non autorisé pour ce niveau.');}
    private function hasEffectiveRole($user,$role,$site){$s=$this->db->prepare("SELECT 1 FROM user_role_assignments WHERE user_id=:user AND role_id=:role AND approval_status='approved' AND deleted_at IS NULL AND starts_at<=NOW() AND (expires_at IS NULL OR expires_at>NOW()) AND (site_id IS NULL OR site_id=:site) LIMIT 1");$s->execute(['user'=>$user,'role'=>$role,'site'=>$site]);return(bool)$s->fetchColumn();}
    private function requirePermission($user,$action,$site,$throw=true){require_once __DIR__.'/AuthorizationService.php';$ok=(new AuthorizationService($this->db))->can($user['id'],'workflows',$action,$site);if(!$ok&&$throw){throw new RuntimeException('Permission workflow refusée.');}return$ok;}
    private function assertActor($instance,$user,$action){if((int)$instance['created_by']!==(int)$user['id']){$this->requirePermission($user,$action,Auth::currentSiteId());}}
    private function expect($state,array$allowed){if(!in_array($state,$allowed,true)){throw new RuntimeException('Transition interdite depuis '.$state.'.');}}
    private function insertDecision($i,$level,$actor,$delegator,$decision,$reason){$check=$this->db->prepare("SELECT 1 FROM workflow_level_approvals WHERE workflow_instance_id=:instance AND attempt_number=:attempt AND approver_id=:actor AND decision='approved' LIMIT 1");$check->execute(['instance'=>$i['id'],'attempt'=>$i['attempt_number'],'actor'=>$actor]);if($decision==='approved'&&$check->fetchColumn()){throw new RuntimeException('Un approbateur différent est requis pour chaque niveau.');}$s=$this->db->prepare('INSERT INTO workflow_level_approvals(workflow_instance_id,level_number,attempt_number,approver_id,delegated_by,decision,reason) VALUES(:instance,:level,:attempt,:actor,:delegator,:decision,:reason)');$s->execute(['instance'=>$i['id'],'level'=>$level,'attempt'=>$i['attempt_number'],'actor'=>$actor,'delegator'=>$delegator,'decision'=>$decision,'reason'=>$reason]);}
    private function lockInstance($id){$s=$this->db->prepare('SELECT * FROM workflow_instances WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);return$s->fetch();}private function lockInstanceByDocument($id){$s=$this->db->prepare('SELECT * FROM workflow_instances WHERE document_id=:id FOR UPDATE');$s->execute(['id'=>$id]);return$s->fetch();}
    private function lockDocument($id){$s=$this->db->prepare('SELECT * FROM documents WHERE id=:id AND deleted_at IS NULL FOR UPDATE');$s->execute(['id'=>$id]);return$s->fetch();}
    private function lockBusinessEntity($type,$id){$map=['weighings'=>'weighings','production_batches'=>'production_batches','distributions'=>'distributions','silo_movements'=>'silo_movements'];if(!isset($map[$type])){return;}$s=$this->db->prepare('SELECT id FROM '.$map[$type].' WHERE id=:id FOR UPDATE');$s->execute(['id'=>$id]);if(!$s->fetch()){throw new RuntimeException('Opération métier liée introuvable.');}}
    private function normalizeState($state){return$state==='validated'?'approved':($state==='pending_validation'?'pending_approval':$state);}
    private function record($id,$from,$to,$action,$level,$actor,$reason){$s=$this->db->prepare('INSERT INTO workflow_transitions(workflow_instance_id,from_state,to_state,action,level_number,actor_id,reason) VALUES(:id,:from,:to,:action,:level,:actor,:reason)');$s->execute(['id'=>$id,'from'=>$from,'to'=>$to,'action'=>$action,'level'=>$level,'actor'=>$actor,'reason'=>$reason]);}
    private function notify($id,$instance,$doc,$state,$user,$level){if($state==='pending_approval'){$s=$this->db->prepare("INSERT INTO workflow_notifications(workflow_instance_id,user_id,event_type,title,message) SELECT DISTINCT :instance,ura.user_id,'approval_required','Approbation requise',:message FROM user_role_assignments ura INNER JOIN role_permissions rp ON rp.role_id=ura.role_id INNER JOIN permissions p ON p.id=rp.permission_id WHERE ura.approval_status='approved' AND ura.deleted_at IS NULL AND ura.starts_at<=NOW() AND (ura.expires_at IS NULL OR ura.expires_at>NOW()) AND (ura.site_id IS NULL OR ura.site_id=:site) AND p.component='workflows' AND p.action='validate' AND ura.user_id<>:actor");$s->execute(['instance'=>$id,'message'=>'Le document #'.$doc['id'].' attend une approbation.','site'=>$doc['site_id'],'actor'=>$user['id']]);return;}$recipient=$instance['created_by'];if(!$recipient||$recipient==$user['id']){return;}$s=$this->db->prepare('INSERT INTO workflow_notifications(workflow_instance_id,user_id,event_type,title,message) VALUES(:instance,:user,:event,:title,:message)');$s->execute(['instance'=>$id,'user'=>$recipient,'event'=>$state,'title'=>'Workflow '.$state,'message'=>'Le document #'.$doc['id'].' est passé à l’état '.$state.'.']);}
    private function log($action,$id,$user,$data){$s=$this->db->prepare("INSERT INTO activity_logs(user_id,site_id,action,module,entity_type,entity_id,description,new_values,user_agent) VALUES(:user,:site,:action,'workflows','workflow_delegations',:id,'Délégation de workflow.',:values,:agent)");$s->execute(['user'=>$user['id'],'site'=>Auth::currentSiteId(),'action'=>$action,'id'=>$id,'values'=>json_encode($data),'agent'=>substr($_SERVER['HTTP_USER_AGENT']??'CLI',0,255)]);}
}
