// Run only against the isolated, authenticated local test server (see docs/travaux-agricoles-validation.md).
if (!/_(test|testing)$/.test(process.env.DAGRIL_DB_DATABASE || '')) throw new Error('DAGRIL_DB_DATABASE must name a test database');
const {chromium}=require(process.env.DAGRIL_PLAYWRIGHT_MODULE || 'playwright');const assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:process.env.DAGRIL_CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message,e.stack);});await page.goto('http://127.0.0.1:8099/agriculture/works');await page.waitForSelector('[data-work-new]');
const data=await page.evaluate(()=>JSON.parse(document.querySelector('[data-work-data]').textContent));const plan=data.plans.find(p=>p.campaign_name==='Test travaux'&&p.campaign_status==='in_progress');assert(plan,'Plan de test disponible');const workers=data.resources.labor.filter(r=>String(r.site_id)===String(plan.site_id)&&r.status==='active'&&r.name.startsWith('Ouvrier test'));const equipment=data.resources.equipment.find(r=>String(r.site_id)===String(plan.site_id)&&r.status==='active'&&r.name==='Tracteur test');
let navigations=0;page.on('framenavigated',f=>{if(f===page.mainFrame())navigations++;});const marker='UI-Test-'+Date.now();
await page.locator('[data-work-new]').click();await page.locator('[data-work-site]').selectOption(String(plan.site_id));await page.locator('[data-work-campaign]').selectOption(String(plan.campaign_id));await page.locator('[name="campaign_plot_id"]').selectOption(String(plan.id));await page.locator('[name="responsible_name"]').fill(marker);await page.locator('[name="worked_at"]').fill('2026-09-11T09:30');await page.locator('[name="currency"]').selectOption('USD');
for(let i=0;i<2;i++){await page.locator('[data-work-add="labor"]').click();const row=page.locator('[data-work-lines="labor"] .work-resource-line').nth(i);await row.locator('[data-line-id]').selectOption(String(workers[i].id));await row.locator('[data-line-quantity]').fill(String(i+1));await row.locator('[data-line-rate]').fill('10');}
await page.locator('[data-work-add="equipment"]').click();const row=page.locator('[data-work-lines="equipment"] .work-resource-line');await row.locator('[data-line-id]').selectOption(String(equipment.id));await row.locator('[data-line-quantity]').fill('3');await row.locator('[data-line-rate]').fill('20');await page.locator('[name="other_cost"]').fill('5');await page.locator('[name="other_cost_reason"]').fill('Transport équipe');assert((await page.locator('[data-work-total]').textContent()).includes('95,00 USD'));
await page.screenshot({path:require('os').tmpdir()+'/work-editor.png',fullPage:true});await page.locator('[data-work-submit]').click();await page.locator('.swal2-cancel').click();assert(await page.locator('[data-work-editor][open]').isVisible());await page.locator('[data-work-submit]').click();await page.locator('.swal2-confirm').click();await page.waitForFunction(()=>!document.querySelector('[data-work-editor]').open);await page.waitForTimeout(300);
await page.locator('[data-work-filter="search"]').fill(marker);await page.locator('[data-work-open]').click();assert((await page.locator('[data-work-detail]').innerText()).includes('95,00 USD'));assert((await page.locator('[data-work-detail]').innerText()).includes('Saisi par'));await page.locator('[data-work-edit]').click();await page.locator('[name="reason"]').fill('Correction vérifiée');await page.locator('[name="other_cost"]').fill('7');await page.locator('[data-work-submit]').click();await page.locator('.swal2-confirm').click();await page.waitForFunction(()=>!document.querySelector('[data-work-editor]').open);await page.waitForTimeout(300);assert.equal(await page.locator('[data-work-filter="search"]').inputValue(),marker);
await page.locator('[data-work-open]').click();assert((await page.locator('[data-work-detail]').innerText()).includes('97,00 USD'));await page.locator('[data-work-cancel]').click();await page.locator('.swal2-confirm').click();assert(await page.locator('.swal2-validation-message').isVisible());await page.locator('.swal2-textarea').fill('Fin du test interface');await page.locator('.swal2-confirm').click();await page.waitForFunction(()=>!document.querySelector('[data-work-detail]').open);await page.waitForTimeout(300);assert.equal((await page.locator('[data-work-kpi="count"]').textContent()).trim(),'0');assert((await page.locator('[data-work-rows]').innerText()).includes('Annulé'));assert.equal(navigations,0,'Aucun rechargement pendant les soumissions');
await page.locator('[data-work-reset]').click();await page.screenshot({path:require('os').tmpdir()+'/works-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);assert(await page.locator('.work-table').evaluate(el=>el.getBoundingClientRect().right<=innerWidth));await page.screenshot({path:require('os').tmpdir()+'/works-mobile-final.png',fullPage:true});await page.locator('[data-work-new]').click();await page.screenshot({path:require('os').tmpdir()+'/work-mobile-final.png',fullPage:false});await page.keyboard.press('Escape');assert.equal(await page.locator('[data-work-editor][open]').count(),0);const invalid=await page.request.post('http://127.0.0.1:8099/agriculture/works',{headers:{'X-Requested-With':'XMLHttpRequest'},form:{_token:'invalid',_return_to:'agriculture/works'}});assert.equal(invalid.status(),419);assert.equal((await invalid.json()).ok,false);assert.deepEqual(errors,[]);console.log('OK: création multiressources, total, confirmation annulée, AJAX sans navigation, correction, motif annulation, exclusion des totaux, filtres conservés, mobile.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
