if(!/_(test|testing)$/.test(process.env.DAGRIL_DB_DATABASE||''))throw Error('Test database required');
const {chromium}=require(process.env.DAGRIL_PLAYWRIGHT_MODULE||'playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:process.env.DAGRIL_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8099/agriculture/campaigns');await page.waitForSelector('[data-campaign-directory][data-ready]');
const row=page.locator('[data-campaign-row]').filter({hasText:'Campagne corrigée'}).first();const id=await row.getAttribute('data-id'),search=(await row.locator('.table-subline').first().innerText()).split(' · ')[0];await page.fill('[data-campaign-filter="search"]',search);await page.click('[data-campaign-open="'+id+'"]');await page.screenshot({path:require('os').tmpdir()+'/campaign-detail-updated.png'});
await page.click('[data-campaign-edit]');const form=page.locator('[data-campaign-edit-form]:visible');await form.locator('[name="end_date"]').fill('2025-01-01');await form.locator('[name="reason"]').fill('Test correction interface');await form.locator('[type="submit"]').click();assert((await form.locator('[data-campaign-edit-error]').innerText()).includes('date de fin'));await form.locator('[name="end_date"]').fill('2026-12-31');const name='Campagne AJAX '+Date.now();await form.locator('[name="name"]').fill(name);
await form.locator('[type="submit"]').click();await page.click('.swal2-cancel');assert.equal(await form.locator('[name="name"]').inputValue(),name);let nav=0;page.on('framenavigated',f=>{if(f===page.mainFrame())nav++;});await form.locator('[type="submit"]').click();await page.click('.swal2-confirm');await page.waitForFunction(n=>document.querySelector('#campaignDrawerTitle')?.textContent===n,name);assert.equal(nav,0);assert.equal(await page.locator('[data-campaign-filter="search"]').inputValue(),search);assert((await page.locator('[data-campaign-row][data-id="'+id+'"]').innerText()).includes(name));
await page.click('[data-campaign-edit]');assert.equal(await page.locator('[data-campaign-edit-form]:visible [name="name"]').inputValue(),name);await page.setViewportSize({width:390,height:844});await page.screenshot({path:require('os').tmpdir()+'/campaign-edit-mobile.png'});assert(await page.locator('[data-campaign-drawer]').evaluate(e=>e.scrollWidth<=e.clientWidth));await page.click('[data-campaign-edit-back]');await page.keyboard.press('Escape');assert.equal(await page.locator('[data-campaign-drawer][open]').count(),0);
const invalid=await page.request.post('http://127.0.0.1:8099/agriculture/campaigns/'+id+'/update',{headers:{'X-Requested-With':'XMLHttpRequest'},form:{_token:'invalid'}});assert.equal(invalid.status(),419);assert.deepEqual(errors,[]);console.log('OK: détail, édition, dates, confirmation annulée, sauvegarde AJAX sans navigation, liste/détail actualisés, filtres conservés, mobile, CSRF.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
