if(!/_(test|testing)$/.test(process.env.DAGRIL_DB_DATABASE||''))throw Error('Test database required');
const {chromium}=require(process.env.DAGRIL_PLAYWRIGHT_MODULE||'playwright'),assert=require('assert');
(async()=>{const browser=await chromium.launch({executablePath:process.env.DAGRIL_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8099/machine-feeds');await page.waitForSelector('[data-feed-search]');await page.fill('[data-feed-search]','introuvable999');assert(await page.locator('[data-feed-empty]').isVisible());await page.click('[data-feed-reset]');await page.screenshot({path:'/private/tmp/machine-feeds-desktop.png'});await page.click('[data-workspace-modal-open="machineFeedModal"]');await page.waitForSelector('#machineFeedModal.is-open',{state:'visible'});const modal=page.locator('#machineFeedModal');assert(await modal.evaluate(e=>Math.abs(e.getBoundingClientRect().right-innerWidth)<2));const silo=await modal.locator('[name="silo_id"] option[data-stock]').evaluateAll(os=>os.find(o=>Number(o.dataset.stock)>1).value),machine=await modal.locator('[name="machine_id"] option[data-site]').first().getAttribute('value');await modal.locator('[name="silo_id"]').selectOption(silo);await modal.locator('[name="machine_id"]').selectOption(machine);await modal.locator('[name="authorized_quantity_kg"]').fill('0.200');await modal.locator('[name="quantity_kg"]').fill('999999999');assert(await modal.locator('[name="quantity_kg"]').evaluate(e=>e.validationMessage.includes('Stock insuffisant')));await modal.locator('[name="quantity_kg"]').fill('0.125');assert((await page.locator('[data-feed-context]').textContent()).includes('Stock après chargement'));await modal.locator('[name="ended_at"]').fill('2000-01-01T00:00');assert(await modal.locator('[name="ended_at"]').evaluate(e=>!e.validity.valid));await modal.locator('[name="ended_at"]').fill('');await page.screenshot({path:'/private/tmp/machine-feed-modal.png'});
await modal.locator('button[type="submit"]').click();await page.locator('button[data-action-dialog-close]:visible').last().click();assert(await modal.isVisible());assert.equal(await modal.locator('[name="quantity_kg"]').inputValue(),'0.125');
// Force a stale/invalid machine past browser validation to exercise server errors and recovery.
await modal.locator('[name="machine_id"]').evaluate(e=>e.selectedOptions[0].value='99999999');await modal.locator('button[type="submit"]').click();await page.click('[data-action-dialog-confirm]');await page.waitForSelector('[data-feed-error]:visible');assert((await page.locator('[data-feed-error]').textContent()).includes('Machine principale'));assert(await modal.isVisible());assert.equal(await modal.locator('[name="quantity_kg"]').inputValue(),'0.125');await modal.locator('[name="machine_id"]').evaluate((e,id)=>{e.selectedOptions[0].value=id;e.dispatchEvent(new Event('change',{bubbles:true}));},machine);
let nav=0;page.on('framenavigated',f=>{if(f===page.mainFrame())nav++;});await modal.locator('button[type="submit"]').click();const response=page.waitForResponse(r=>r.request().method()==='POST'&&r.url().endsWith('/machine-feeds'));await page.click('[data-action-dialog-confirm]');const payload=await(await response).json();assert.equal(payload.ok,true,JSON.stringify(payload));await page.waitForSelector('#machineFeedModal.is-open',{state:'hidden'});assert.equal(nav,0);assert(page.url().endsWith('/machine-feeds'));assert(await page.locator('a[href$="/machine-feeds/'+payload.id+'"]').count());
for(const width of [390,320]){await page.setViewportSize({width,height:844});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth);await page.screenshot({path:'/private/tmp/machine-feed-list-'+width+'.png'});await page.click('[data-workspace-modal-open="machineFeedModal"]');assert.equal(await modal.locator('[name="quantity_kg"]').inputValue(),'');assert(await modal.evaluate(e=>e.scrollWidth<=e.clientWidth));await page.waitForFunction(()=>getComputedStyle(document.getElementById('machineFeedModal')).opacity==='1');await page.screenshot({path:'/private/tmp/machine-feed-mobile-'+width+'.png'});await modal.locator('[data-workspace-modal-close]').first().click();}
await page.goto('http://127.0.0.1:8099/machine-feeds/create');await page.waitForSelector('#machineFeedModal.is-open',{state:'visible'});assert.deepEqual(errors,[]);console.log('OK : filtres, formulaire latéral, contexte, stock/dates, confirmation annulée, erreur serveur explicite, saisie conservée, création AJAX, remise à zéro, mobile et ancien lien de création.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
