<?php
$labels=['pending_approval'=>'À approuver','approved'=>'Approuvée','completed'=>'Exécutée','rejected'=>'Refusée'];
$groups=['all'=>['Demandes affichées',$requests],'pending'=>['À approuver',array_values(array_filter($requests,static function($r){return $r['status']==='pending_approval';}))],'completed'=>['Annulations exécutées',array_values(array_filter($requests,static function($r){return $r['status']==='completed';}))],'rejected'=>['Demandes refusées',array_values(array_filter($requests,static function($r){return $r['status']==='rejected';}))]];
$date=static function($v){return $v?date('d/m/Y H:i',strtotime($v)):'—';};
$modals=[];$modal=static function($id,$title,$body)use(&$modals){ob_start();?>
<section id="<?=e($id)?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="<?=e($id)?>-title"><header><h2 id="<?=e($id)?>-title"><?=e($title)?></h2><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header><?=$body?></section>
<?php $modals[]=ob_get_clean();};
?>
<div class="butchery-workspace transfer-workspace cancellation-workspace"><header class="butchery-heading"><span class="butchery-heading-icon"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i></span><div><p>Contrôle interne</p><h2>Annulations et corrections</h2></div></header>
<?php if($success):?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?>
<div class="butchery-metrics"><?php foreach($groups as $key=>$group):?><button type="button" class="butchery-kpi" data-workspace-modal-open="cancellation-kpi-<?=e($key)?>"><strong><?=count($group[1])?></strong><span><?=e($group[0])?></span><i class="bi bi-chevron-right" aria-hidden="true"></i></button><?php endforeach;?></div>
<section class="trace-brief"><h3>Lecture de direction</h3><p><?=count($groups['pending'][1])?> demande(s) à examiner · <?=count($groups['completed'][1])?> annulation(s) exécutée(s) avec contre-opération.</p><small>Synthèse des 200 dernières demandes accessibles. Les filtres du registre n’affectent pas ces compteurs. Une demande ne signifie pas que l’opération est déjà annulée.</small></section>
<section class="table-panel butchery-history"><header class="fuel-section-heading"><h3>Demandes et décisions</h3><?php if(Auth::can('cancellations','create')):?><button type="button" class="btn-primary" data-workspace-modal-open="cancellation-create">Demander une annulation</button><?php endif;?></header><?php $rows=$requests;$filters=true;require __DIR__.'/table.php';?></section>
<details class="fuel-reference"><summary>Règles et effets des annulations</summary><?php require __DIR__.'/policies.php';?></details>
<?php foreach($groups as $key=>$group):ob_start();?><div class="feed-form-body"><?php $rows=$group[1];$filters=false;require __DIR__.'/table.php';?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer><?php $modal('cancellation-kpi-'.$key,$group[0],ob_get_clean());endforeach;?>
<?php if(Auth::can('cancellations','create')):ob_start();require __DIR__.'/create_form.php';$modal('cancellation-create','Demander une annulation',ob_get_clean());endif;?>
<?php foreach($requests as $r):ob_start();?>
<div class="feed-form-body"><div class="butchery-detail-banner"><strong><?=e($r['request_number'])?></strong><span class="butchery-status"><?=e($labels[$r['status']]??$r['status'])?></span></div><dl class="butchery-history-details"><?php foreach(['Opération'=>$r['label'].' #'.$r['entity_id'],'Site'=>$r['site_code'],'Demandé par'=>$r['requester_name'],'Demandé le'=>$date($r['requested_at']),'Approuvé par'=>$r['approver_name']?:'—','Contre-opération'=>$r['reversal_number']?:'Non exécutée','Exécutée le'=>$date($r['completed_at']??null)] as $label=>$value):?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl><h3 class="cancellation-label">Motif</h3><p><?=nl2br(e($r['reason']))?></p><?php if(!empty($r['rejection_reason'])):?><h3 class="cancellation-label">Motif du refus</h3><p><?=nl2br(e($r['rejection_reason']))?></p><?php endif;?>
<details><summary>Effets et contrôles applicables</summary><p><strong>Stock :</strong> <?=e($r['stock_effects'])?></p><p><strong>Blocages :</strong> <?=e($r['blocking_dependencies'])?></p><p><strong>Documents :</strong> <?=e($r['document_types']?:'—')?></p></details>
<?php if($r['status']==='pending_approval'&&Auth::can('cancellations','validate',$r['site_id'])&&(int)$r['requested_by']!==(int)(Auth::user()['id']??0)):?>
<form method="post" action="<?=e(base_url('cancellations/'.$r['id'].'/approve'))?>" data-cancellation-form data-native-submit><?=csrf_field()?><p class="app-alert app-alert-error" data-cancellation-error role="alert" hidden></p><p class="butchery-detail-note">L’approbation exécute la contre-opération si les contrôles métier le permettent.</p><button type="submit" class="btn-primary">Approuver et exécuter</button></form>
<details class="cancellation-reject"><summary>Refuser la demande</summary><form method="post" action="<?=e(base_url('cancellations/'.$r['id'].'/reject'))?>" data-cancellation-form data-native-submit><?=csrf_field()?><p class="app-alert app-alert-error" data-cancellation-error role="alert" hidden></p><label><span>Motif du refus *</span><textarea name="reason" required rows="2"></textarea></label><button type="submit" class="btn-secondary">Confirmer le refus</button></form></details>
<?php elseif($r['status']==='pending_approval'&&(int)$r['requested_by']===(int)(Auth::user()['id']??0)):?><p class="butchery-detail-note">Une autre personne habilitée doit statuer sur votre demande.</p><?php endif;?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer>
<?php $modal('cancellation-detail-'.$r['id'],'Examiner la demande',ob_get_clean());endforeach;echo implode('',$modals);?></div>
