<section class="dashboard-hero"><span class="hero-icon"><i class="bi bi-arrow-counterclockwise"></i></span><div><p class="section-label">Contrôle interne</p><h2>Annulations et corrections</h2><p>Aucune suppression : chaque annulation produit une contre-opération liée et auditée.</p></div></section>
<?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?>
<?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>

<?php if(Auth::can('cancellations','create')):?><section class="form-panel"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-file-earmark-minus"></i></span><div><h3>Demander une annulation</h3><p>Le motif est obligatoire. Les opérations ayant produit du stock exigent une autre personne pour approuver.</p></div></div><form method="post" action="<?=e(base_url('cancellations'))?>" class="enterprise-form"><?=csrf_field()?><div class="form-grid"><label><span>Type d’opération</span><select name="entity_type" required><option value="">Sélectionner</option><?php foreach($policies as$p):?><option value="<?=e($p['entity_type'])?>"><?=e($p['label'])?></option><?php endforeach;?></select></label><label><span>ID de l’opération</span><input type="number" min="1" name="entity_id" required></label><label class="field-wide"><span>Motif détaillé</span><textarea name="reason" minlength="5" required></textarea></label></div><div class="form-actions"><button class="btn-primary">Soumettre la demande</button></div></form></section><?php endif;?>

<section class="table-panel"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-shield-check"></i></span><div><h3>Matrice de contrôle</h3><p>Statuts, effets inverses, documents et dépendances bloquantes.</p></div></div><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Opération</th><th>Statuts annulables</th><th>Effets de stock</th><th>Documents</th><th>Blocages</th><th>Approbation</th></tr></thead><tbody><?php foreach($policies as$p):?><tr><td><?=e($p['label'])?></td><td><?=e($p['allowed_statuses'])?></td><td><?=e($p['stock_effects'])?></td><td><?=e($p['document_types']?:'—')?></td><td><?=e($p['blocking_dependencies'])?></td><td><?=$p['requires_approval_after_validation']?'Oui après validation':'Non'?></td></tr><?php endforeach;?></tbody></table></div></section>

<section class="table-panel"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-clock-history"></i></span><div><h3>Demandes et contre-opérations</h3><p>Historique limité aux sites autorisés, ou consolidé pour la Direction.</p></div></div><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Demande</th><th>Site</th><th>Opération</th><th>Motif</th><th>Demandeur</th><th>Statut</th><th>Contre-opération</th><th>Décision</th></tr></thead><tbody><?php foreach($requests as$r):?><tr><td><?=e($r['request_number'])?><br><small><?=e($r['requested_at'])?></small></td><td><?=e($r['site_code'])?></td><td><?=e($r['label'].' #'.$r['entity_id'])?></td><td><?=e($r['reason'])?></td><td><?=e($r['requester_name'])?></td><td><?=e($r['status'])?></td><td><?=e($r['reversal_number']?:'—')?></td><td><?php if($r['status']==='pending_approval'&&Auth::can('cancellations','validate',$r['site_id'])):?><form method="post" action="<?=e(base_url('cancellations/'.$r['id'].'/approve'))?>" style="display:inline"><?=csrf_field()?><button class="btn-primary">Approuver</button></form><form method="post" action="<?=e(base_url('cancellations/'.$r['id'].'/reject'))?>" class="enterprise-form" style="margin-top:.5rem"><?=csrf_field()?><input name="reason" placeholder="Motif du refus" required><button class="btn-secondary">Rejeter</button></form><?php else:?><?=e($r['approver_name']?:'—')?><?php endif;?></td></tr><?php endforeach;?><?php if(!$requests):?><tr><td colspan="8">Aucune demande.</td></tr><?php endif;?></tbody></table></div></section>
