<?php
$chainLabels=['agriculture'=>'Agriculture','mill'=>'Minoterie','waste'=>'Déchets et valorisation','butchery'=>'Élevage et boucherie'];
$states=['draft'=>'Brouillon','preparation'=>'En préparation','submitted'=>'À valider','pending'=>'En attente','validated'=>'Validé','approved'=>'Approuvé','active'=>'Actif','in_transit'=>'En transit','received'=>'Reçu','completed'=>'Terminé','closed'=>'Clôturé','cancelled'=>'Annulé','rejected'=>'Refusé','return_pending'=>'Retour à traiter','returned'=>'Retourné','available'=>'Disponible','reserved'=>'Réservé','depleted'=>'Épuisé','in_progress'=>'En cours','open'=>'Ouvert','resolved'=>'Résolu'];
$date=static function($v){return $v?date('d/m/Y H:i',strtotime($v)):'—';};
$rows=$dossier??$results;$siteCount=count(array_unique(array_column($rows,'site_code')));$docs=[];$issues=[];$corrections=[];
foreach($dossier??[] as $event){foreach($event['documents'] as $d)$docs[$d['id']]=$d;foreach($event['nonconformities'] as $n)$issues[$n['reference']]=$n;foreach($event['corrections'] as $c)$corrections[$c['request_number']]=$c;}
$openIssues=array_filter($issues,static function($n){return !in_array($n['status'],['resolved','closed','cancelled'],true);});
?>
<div class="butchery-workspace trace-workspace">
<header class="butchery-heading"><span class="butchery-heading-icon"><i class="bi bi-diagram-3" aria-hidden="true"></i></span><div><p>Pilotage · Origine et destination</p><h2><?=$dossier===null?'Traçabilité des opérations':'Dossier de traçabilité'?></h2></div><?php if($dossier!==null):?><a class="btn-secondary" href="<?=e(base_url('traceability?'.http_build_query($filters)))?>">Retour aux résultats</a><?php endif;?></header>
<?php if($error):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?>
<form method="get" action="<?=e(base_url('traceability'))?>" class="trace-filters">
<label class="field-wide"><span>Document, lot, camion, produit ou fournisseur</span><input name="q" value="<?=e($filters['q'])?>" placeholder="BTR/…, LOT-…, plaque, produit, fournisseur"></label>
<label><span>Site</span><select name="site_id"><option value="">Sites autorisés</option><?php if(Auth::canViewConsolidated()):?><option value="all" <?=$filters['site_id']==='all'?'selected':''?>>Tous les sites</option><?php endif;?><?php foreach($sites as$s):?><option value="<?=$s['id']?>" <?=(string)$filters['site_id']===(string)$s['id']?'selected':''?>><?=e($s['code'].' — '.$s['name'])?></option><?php endforeach;?></select></label>
<label><span>Du</span><input type="date" name="start_date" value="<?=e($filters['start_date'])?>"></label><label><span>Au</span><input type="date" name="end_date" value="<?=e($filters['end_date'])?>"></label><button class="btn-primary">Rechercher</button><a class="btn-secondary" href="<?=e(base_url('traceability'))?>">Réinitialiser</a></form><div class="trace-metrics"><article><strong><?=count($rows)?></strong><span><?=$dossier===null?'Dossiers trouvés':'Étapes reliées'?></span></article><article><strong><?=$siteCount?></strong><span>Sites représentés</span></article><?php if($dossier!==null):?><article><strong><?=count($docs)?></strong><span>Documents liés</span></article><article><strong><?=count($openIssues)?></strong><span>Non-conformités à examiner</span></article><?php else:?><article><strong><?=count(array_unique(array_column($results,'chain')))?></strong><span>Filières représentées</span></article><?php endif;?></div>
<section class="trace-brief"><h3>Lecture de direction</h3>
<?php if(!$rows):?><p>Aucun résultat sur ce périmètre. Vérifiez la référence, les dates et les sites autorisés.</p>
<?php elseif($dossier===null):?><p><?=count($results)?> dossier(s) correspondent aux critères. Ouvrez une chaîne pour examiner les étapes, les documents et les éventuels écarts.</p><small>Les statuts affichés concernent les opérations d’origine, pas la conformité de l’ensemble de la chaîne.</small>
<?php else:?><p><?php if($openIssues):?><?=count($openIssues)?> non-conformité(s) à examiner avant de conclure sur ce dossier.<?php else:?>Aucune non-conformité ouverte trouvée dans les étapes accessibles.<?php endif;?> <?=count($corrections)?> demande(s) d’annulation ou de correction liée(s).</p><small>Du <?=e($date($rows[0]['event_date']))?> au <?=e($date($rows[count($rows)-1]['event_date']))?>. Seuls les liens enregistrés et autorisés sont affichés ; cela ne garantit pas l’exhaustivité de la chaîne. Les quantités des étapes ne sont pas additionnées.</small>
<?php endif;?></section>
<section class="table-panel butchery-history"><header class="fuel-section-heading"><h3><?=$dossier===null?'Dossiers trouvés':'Parcours chronologique'?></h3></header><div class="table-responsive">
<?php if($dossier===null):?><table class="enterprise-table"><thead><tr><th>Référence / filière</th><th>Description</th><th>Site</th><th>Date</th><th>Statut d’origine</th><th>Action</th></tr></thead><tbody><?php foreach($results as $r):?><tr><td><strong><?=e($r['reference'])?></strong><small><?=e($chainLabels[$r['chain']]??$r['chain'])?></small></td><td><?=e($r['label'])?></td><td><?=e($r['site_code'])?></td><td><?=e($date($r['operation_date']))?></td><td><span class="butchery-status"><?=e($states[$r['status']]??$r['status'])?></span></td><td><a class="btn-secondary" href="<?=e(base_url('traceability/'.$r['chain'].'/'.$r['root_id'].'?'.http_build_query($filters)))?>">Ouvrir la chaîne</a></td></tr><?php endforeach;?></tbody></table>
<?php else:?><table class="enterprise-table"><thead><tr><th>Étape / référence</th><th>Date</th><th>Site</th><th>Quantité</th><th>Statut</th><th>Pièces / écarts</th><th>Détails</th></tr></thead><tbody><?php foreach($dossier as $i=>$r):?><tr><td><strong><?=e(($i+1).' · '.$r['stage'])?></strong><small><?=e($r['reference'])?></small></td><td><?=e($date($r['event_date']))?></td><td><?=e($r['site_code'])?></td><td><?=$r['quantity']!==null?e(number_format((float)$r['quantity'],3,',',' ').' '.$r['unit']):'—'?></td><td><?=e($states[$r['status']]??$r['status'])?></td><td><?=count($r['documents'])?> document(s)<small><?=count($r['nonconformities'])?> écart(s) · <?=count($r['corrections'])?> correction(s)</small></td><td><button type="button" class="btn-secondary" data-workspace-modal-open="trace-event-<?=$i?>">Consulter</button></td></tr><?php endforeach;?></tbody></table><?php endif;?>
</div></section>
<?php foreach($dossier??[] as $i=>$r):?><section id="trace-event-<?=$i?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="trace-title-<?=$i?>"><header><h2 id="trace-title-<?=$i?>"><?=e($r['stage'])?></h2><button class="modal-close" type="button" data-workspace-modal-close aria-label="Fermer">×</button></header><div class="feed-form-body"><div class="butchery-detail-banner"><strong><?=e($r['reference'])?></strong><span class="butchery-status"><?=e($states[$r['status']]??$r['status'])?></span></div><p><?=e($r['label'])?></p><dl class="butchery-history-details"><?php foreach(['Site'=>$r['site_code'],'Date'=>$date($r['event_date']),'Quantité'=>$r['quantity']!==null?number_format((float)$r['quantity'],3,',',' ').' '.$r['unit']:'—','Saisi par'=>$r['user_name']?:'Non renseigné','Validé par'=>$r['validator_name']?:'Non renseigné','Date de validation'=>$date($r['validated_at']??null)] as $label=>$value):?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl><?php require __DIR__.'/event_details.php';?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer></section><?php endforeach;?>
</div>
