<section class="dashboard-hero"><span class="hero-icon"><i class="bi bi-diagram-3"></i></span><div><p class="section-label">De la source au destinataire</p><h2>Traçabilité complète</h2><p>Navigation bidirectionnelle par lots, documents et mouvements.</p></div></section>
<?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<section class="form-panel"><form method="get" action="<?=e(base_url('traceability'))?>" class="enterprise-form"><div class="form-grid">
<label class="field-wide"><span>Document, lot, camion, produit ou fournisseur</span><input name="q" value="<?=e($filters['q'])?>" placeholder="BTR/…, LOT-…, plaque, produit, fournisseur"></label>
<label><span>Site</span><select name="site_id"><option value="">Sites autorisés</option><?php if(Auth::canViewConsolidated()):?><option value="all" <?=$filters['site_id']==='all'?'selected':''?>>Tous les sites</option><?php endif;?><?php foreach($sites as$s):?><option value="<?=$s['id']?>" <?=(string)$filters['site_id']===(string)$s['id']?'selected':''?>><?=e($s['code'].' — '.$s['name'])?></option><?php endforeach;?></select></label>
<label><span>Du</span><input type="date" name="start_date" value="<?=e($filters['start_date'])?>"></label><label><span>Au</span><input type="date" name="end_date" value="<?=e($filters['end_date'])?>"></label></div><div class="form-actions"><button class="btn-primary">Rechercher</button><a class="btn-secondary" href="<?=e(base_url('traceability'))?>">Réinitialiser</a></div></form></section>
<?php if($dossier!==null):?><section class="table-panel"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-signpost-split"></i></span><div><h3>Chaîne reconstituée</h3><p>Étapes chronologiques liées uniquement par les clés enregistrées.</p></div></div><div class="trace-timeline">
<?php foreach($dossier as$i=>$r):?><article class="metric-card" style="margin-bottom:1rem"><div class="metric-card-top"><span><?=e(($i+1).' · '.$r['stage'])?></span><span class="badge"><?=e($r['status'])?></span></div><h3><?=e($r['reference'])?></h3><p><?=e($r['label'])?></p><p><strong><?=e($r['quantity']!==null?number_format((float)$r['quantity'],3,',',' ').' '.$r['unit']:'—')?></strong> · <?=e($r['site_code'])?> · <?=e($r['event_date'])?></p><small>Saisi par <?=e($r['user_name']?:'non renseigné')?><?php if(!empty($r['validator_name'])):?> · Validé par <?=e($r['validator_name'])?> <?=e($r['validated_at']??'')?><?php endif;?></small>
<?php if($r['documents']):?><p><strong>Documents :</strong> <?php foreach($r['documents'] as$d):?><a href="<?=e(base_url('documents/'.$d['id']))?>"><?=e($d['display_code'].' '.$d['document_number'].' ['.$d['status'].']')?></a> <?php endforeach;?></p><?php endif;?>
<?php if($r['nonconformities']):?><div class="alert alert-warning"><strong>Non-conformités :</strong> <?php foreach($r['nonconformities'] as$n):?><?=e($n['reference'].' ['.$n['status'].'] — '.($n['description']?:'Sans commentaire'))?> <?php endforeach;?></div><?php endif;?>
<?php if($r['movements']):?><details><summary>Mouvements de stock (<?=count($r['movements'])?>)</summary><div class="table-responsive"><table class="enterprise-table"><tbody><?php foreach($r['movements'] as$m):?><tr><td><?=e($m['movement_type'])?></td><td><?=e($m['quantity_kg']??$m['quantity']??'')?></td><td><?=e($m['movement_date'])?></td><td><?=e(($m['stock_before_kg']??$m['physical_before_kg']??'').' → '.($m['stock_after_kg']??$m['physical_after_kg']??''))?></td></tr><?php endforeach;?></tbody></table></div></details><?php endif;?>
<?php if($r['corrections']):?><div class="alert alert-warning"><strong>Annulation/correction :</strong> <?php foreach($r['corrections'] as$c):?><?=e($c['request_number'].' '.$c['status'].' '.($c['reversal_number']?:'').' — '.$c['reason'])?> <?php endforeach;?></div><?php endif;?></article><?php endforeach;?></div><a class="btn-secondary" href="<?=e(base_url('traceability'))?>">Retour à la recherche</a></section>
<?php else:?><section class="table-panel"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-search"></i></span><div><h3>Dossiers trouvés</h3><p>Ouvrez une racine pour parcourir la chaîne dans les deux sens.</p></div></div><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Chaîne</th><th>Référence</th><th>Description</th><th>Site</th><th>Date</th><th>Statut</th><th></th></tr></thead><tbody><?php foreach($results as$r):?><tr><td><?=e($r['chain'])?></td><td><?=e($r['reference'])?></td><td><?=e($r['label'])?></td><td><?=e($r['site_code'])?></td><td><?=e($r['operation_date'])?></td><td><?=e($r['status'])?></td><td><a class="btn-secondary" href="<?=e(base_url('traceability/'.$r['chain'].'/'.$r['root_id']))?>">Parcourir</a></td></tr><?php endforeach;?><?php if(!$results):?><tr><td colspan="7">Aucun dossier correspondant sur les sites autorisés.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
