<?php
require dirname(__DIR__).'/app/helpers/functions.php';require dirname(__DIR__).'/app/core/Database.php';
if(!preg_match('/_(test|testing)$/',config('database.database')))throw new RuntimeException('Base de test obligatoire.');
class Auth {static $allowed=true;static $site;static function requireSiteAccess($s){if((int)$s!==self::$site)throw new RuntimeException('Site interdit');}static function requirePermission($c,$a,$s){self::requireSiteAccess($s);if(!self::$allowed)throw new RuntimeException('Permission refusée');}}
require dirname(__DIR__).'/app/services/AgriculturalWorkService.php';
$db=Database::getInstance()->connection();$service=new AgriculturalWorkService($db);$tag=bin2hex(random_bytes(5));
function sql($q,$p=[]){global $db;$s=$db->prepare($q);$s->execute($p);return $s;}
function check($ok,$message){if(!$ok)throw new RuntimeException($message);echo 'OK - '.$message.PHP_EOL;}
$site=(int)sql("SELECT id FROM sites WHERE code='FARM-MUT'")->fetchColumn();Auth::$site=$site;$user=['id'=>(int)sql('SELECT id FROM users ORDER BY id LIMIT 1')->fetchColumn()];$season=sql('SELECT id FROM agricultural_seasons LIMIT 1')->fetchColumn();$variety=sql('SELECT id FROM agricultural_varieties LIMIT 1')->fetchColumn();
sql("INSERT INTO agricultural_campaigns(site_id,season_id,code,name,start_date,end_date,status,created_by) VALUES(?,?,?,?,'2020-01-01','2099-12-31','in_progress',?)",[$site,$season,'TEST-'.$tag,'Test travaux',$user['id']]);$campaign=$db->lastInsertId();
sql("INSERT INTO agricultural_plots(site_id,code,name,total_area_ha) VALUES(?,?,?,10)",[$site,'TEST-'.$tag,'Parcelle test']);$plot=$db->lastInsertId();sql("INSERT INTO agricultural_campaign_plots(campaign_id,plot_id,variety_id,planned_area_ha,actual_area_ha,target_tons_per_ha,status) VALUES(?,?,?,10,10,3,'in_progress')",[$campaign,$plot,$variety]);$cp=$db->lastInsertId();
$workers=[];for($i=0;$i<2;$i++){sql("INSERT INTO agricultural_workers(site_id,worker_number,name,worker_type,daily_rate,status) VALUES(?,?,?,'daily',999,'active')",[$site,'TEST-'.$tag.'-'.$i,'Ouvrier test '.$i]);$workers[]=$db->lastInsertId();}sql("INSERT INTO agricultural_equipment(site_id,code,name,hourly_cost,status) VALUES(?,?,?,999,'active')",[$site,'TEST-'.$tag,'Tracteur test']);$equipment=$db->lastInsertId();
$base=['submission_key'=>bin2hex(random_bytes(20)),'campaign_plot_id'=>$cp,'work_type'=>'Labour','worked_at'=>date('Y-m-d').'T00:00','responsible_name'=>'Chef de parcelle','currency'=>'USD','other_cost'=>'5','other_cost_reason'=>'Transport de l’équipe','labor'=>[['id'=>$workers[0],'quantity'=>2,'rate'=>10],['id'=>$workers[1],'quantity'=>1,'rate'=>15]],'equipment'=>[['id'=>$equipment,'quantity'=>3,'rate'=>20]]];
$id=$service->save($base,$user);check((float)sql('SELECT exchange_rate FROM agricultural_works WHERE id=?',[$id])->fetchColumn()===1.0,'USD : taux automatique 1');check($id>0,'Travail avec deux travailleurs et un équipement');check((float)sql('SELECT SUM(cost) FROM agricultural_work_labor WHERE work_id=?',[$id])->fetchColumn()===35.0,'Tarifs déclarés en devise appliqués sans conversion du catalogue');check((float)sql('SELECT SUM(cost) FROM agricultural_work_equipment WHERE work_id=?',[$id])->fetchColumn()===60.0,'Coût matériel exact');check($service->save($base,$user)===$id,'Double soumission : une seule opération');
function refuses($patch,$label,$expected=null){global $base,$service,$user; $data=array_replace($base,$patch,['submission_key'=>bin2hex(random_bytes(20))]);$before=(int)sql('SELECT COUNT(*) FROM agricultural_works')->fetchColumn();$caught=false;try{$service->save($data,$user);}catch(Throwable $e){$caught=$expected===null||str_contains($e->getMessage(),$expected);}check($caught&&$before===(int)sql('SELECT COUNT(*) FROM agricultural_works')->fetchColumn(),$label.' : refus sans écriture partielle');}
refuses(['other_cost'=>-1],'Coût négatif');refuses(['other_cost_reason'=>''],'Coût additionnel sans motif');refuses(['worked_at'=>'2026-02-30T12:00'],'Date impossible');refuses(['worked_at'=>'2099-01-01T12:00'],'Date future');refuses(['currency'=>''],'Devise absente');refuses(['responsible_name'=>''],'Responsable absent');refuses(['labor'=>[['id'=>$workers[0],'quantity'=>0,'rate'=>10]]],'Ressource sans durée');refuses(['labor'=>[['id'=>'','quantity'=>2,'rate'=>10]]],'Durée sans ressource');refuses(['labor'=>[['id'=>$workers[0],'quantity'=>1,'rate'=>10],['id'=>$workers[0],'quantity'=>2,'rate'=>10]]],'Ressource répétée');refuses(['labor'=>[['id'=>$workers[0],'quantity'=>1]]],'Tarif sans devise non repris automatiquement');
sql("UPDATE agricultural_workers SET status='inactive' WHERE id=?",[$workers[0]]);refuses([],'Ressource inactive');sql("UPDATE agricultural_workers SET status='active' WHERE id=?",[$workers[0]]);
sql("UPDATE agricultural_campaigns SET status='closed' WHERE id=?",[$campaign]);refuses([],'Campagne clôturée');sql("UPDATE agricultural_campaigns SET status='in_progress' WHERE id=?",[$campaign]);Auth::$allowed=false;refuses([],'Permission refusée');Auth::$allowed=true;
$otherSite=(int)sql("SELECT id FROM sites WHERE code='FARM-DIK'")->fetchColumn();sql('UPDATE agricultural_workers SET site_id=? WHERE id=?',[$otherSite,$workers[0]]);refuses([],'Ressource d’une autre ferme');sql('UPDATE agricultural_workers SET site_id=? WHERE id=?',[$site,$workers[0]]);
$cdf=$base;$cdf['submission_key']=bin2hex(random_bytes(20));$cdf['currency']='CDF';$cdf['exchange_rate']=2800;$cdf['labor'][0]['rate']=25000;$cdfId=$service->save($cdf,$user);check(sql('SELECT currency FROM agricultural_works WHERE id=?',[$cdfId])->fetchColumn()==='CDF','Devise CDF conservée sans conversion');check((float)sql('SELECT cost FROM agricultural_work_labor WHERE work_id=? AND worker_id=?',[$cdfId,$workers[0]])->fetchColumn()===50000.0,'Montant CDF calculé indépendamment du travail USD');
refuses(['currency'=>'CDF'],'CDF sans taux');refuses(['currency'=>'CDF','exchange_rate'=>0],'Taux nul');refuses(['currency'=>'CDF','exchange_rate'=>-2],'Taux négatif');refuses(['currency'=>'CDF','exchange_rate'=>'abc'],'Taux non numérique');refuses(['currency'=>'CDF','exchange_rate'=>0.0000001],'Taux inférieur à la précision admise');
check((float)sql('SELECT exchange_rate FROM agricultural_works WHERE id=?',[$cdfId])->fetchColumn()===2800.0,'Taux CDF conservé');
$default=$base;unset($default['currency']);$default['exchange_rate']=2800;$default['submission_key']=bin2hex(random_bytes(20));$defaultId=$service->save($default,$user);$defaults=sql('SELECT currency,exchange_rate FROM agricultural_works WHERE id=?',[$defaultId])->fetch();check($defaults['currency']==='USD'&&(float)$defaults['exchange_rate']===1.0,'Devise omise : USD, taux forcé à 1 côté serveur');
$cdf['revision']=1;$cdf['reason']='Correction du taux';$cdf['exchange_rate']=2900;$service->save($cdf,$user,$cdfId);$history=json_decode(sql('SELECT new_values FROM agricultural_work_history WHERE work_id=? ORDER BY id DESC LIMIT 1',[$cdfId])->fetchColumn(),true);check((float)$history['work']['exchange_rate']===2900.0,'Correction du taux historisée');
$edit=$base;$edit['revision']=1;$edit['reason']='Correction du temps de travail';$edit['labor'][0]['quantity']=3;$service->save($edit,$user,$id);check((int)sql('SELECT revision FROM agricultural_works WHERE id=?',[$id])->fetchColumn()===2,'Correction incrémente la version');$caught=false;try{$service->save($edit,$user,$id);}catch(Throwable $e){$caught=true;}check($caught,'Correction concurrente obsolète refusée');
$service->cancel($id,['revision'=>2,'reason'=>'Intervention saisie deux fois'],$user);check(sql('SELECT status FROM agricultural_works WHERE id=?',[$id])->fetchColumn()==='cancelled','Annulation conserve le travail');check((int)sql('SELECT COUNT(*) FROM agricultural_work_history WHERE work_id=?',[$id])->fetchColumn()===3,'Création, correction et annulation historisées');check((int)sql('SELECT COUNT(*) FROM agricultural_work_labor WHERE work_id=?',[$id])->fetchColumn()===2,'Annulation conserve le détail des coûts');
refuses(['worked_at'=>''],'Date vide expliquée','Date et heure manquantes');
refuses(['worked_at'=>'2026-02-30T12:00'],'Date impossible expliquée','Date et heure invalides');
refuses(['worked_at'=>'2098-01-01T12:00'],'Heure future expliquée','Date ou heure future');
sql("UPDATE agricultural_campaigns SET start_date='2026-01-01',end_date='2026-08-31' WHERE id=?",[$campaign]);
refuses(['worked_at'=>'2026-09-01T12:00'],'Période autorisée dans le message','31/08/2026');
sql("UPDATE agricultural_campaigns SET start_date='2098-01-01',end_date='2099-12-31' WHERE id=?",[$campaign]);
refuses(['worked_at'=>'2098-01-01T12:00'],'Campagne future expliquée','campagne déjà commencée');
sql("UPDATE agricultural_campaigns SET start_date='2020-01-01',end_date='2099-12-31' WHERE id=?",[$campaign]);
echo "Tests des travaux terminés.\n";
