<?php
require dirname(__DIR__).'/app/helpers/functions.php';require dirname(__DIR__).'/app/core/Database.php';require dirname(__DIR__).'/app/core/Model.php';
if(!preg_match('/_(test|testing)$/',config('database.database')))throw new RuntimeException('Base de test obligatoire.');
class Auth {static $admin=true,$site;static function hasRole($roles){return self::$admin;}static function requireSiteAccess($site){if((int)$site!==self::$site)throw new RuntimeException('Site interdit');}static function requirePermission($m,$a,$site){self::requireSiteAccess($site);}static function currentSiteId(){return self::$site;}}
require dirname(__DIR__).'/app/models/Agriculture.php';
$db=Database::getInstance()->connection();$m=new Agriculture();
function sql($q,$p=[]){global $db;$s=$db->prepare($q);$s->execute($p);return $s;}
function check($ok,$label){if(!$ok)throw new RuntimeException($label);echo "OK - $label\n";}
Auth::$site=(int)sql("SELECT id FROM sites WHERE code='FARM-MUT'")->fetchColumn();$user=['id'=>(int)sql('SELECT id FROM users LIMIT 1')->fetchColumn()];$season=sql("SELECT id FROM agricultural_seasons WHERE status='active' AND deleted_at IS NULL LIMIT 1")->fetchColumn();$code='EDIT-'.bin2hex(random_bytes(6));
sql("INSERT INTO agricultural_campaigns(site_id,season_id,code,name,start_date,end_date,status,created_by) VALUES(?,?,?,'Campagne modification test','2026-01-01','2026-12-31','planned',?)",[Auth::$site,$season,$code,$user['id']]);$id=$db->lastInsertId();
$old=sql('SELECT * FROM agricultural_campaigns WHERE id=?',[$id])->fetch();$base=array_merge($old,['version'=>Agriculture::campaignVersion($old),'reason'=>'Correction vérifiée','name'=>'Campagne corrigée']);
function refuses($patch,$label,$text){global $id,$base,$m,$user;$before=sql('SELECT * FROM agricultural_campaigns WHERE id=?',[$id])->fetch();try{$m->updateCampaign($id,array_replace($base,$patch),$user);throw new RuntimeException('Accepté à tort');}catch(RuntimeException $e){check(str_contains($e->getMessage(),$text)&&$before===sql('SELECT * FROM agricultural_campaigns WHERE id=?',[$id])->fetch(),$label);}}
Auth::$admin=false;refuses([],'Non-administrateur refusé','administrateurs');Auth::$admin=true;
Auth::$site++;refuses([],'Autre site refusé','Site interdit');Auth::$site--;
refuses(['start_date'=>'2026-02-30'],'Date impossible refusée','dates');refuses(['end_date'=>'2025-12-31'],'Dates inversées refusées','date de fin');refuses(['reason'=>''],'Motif obligatoire','Motif');refuses(['status'=>'invalid'],'Statut invalide refusé','Statut');refuses(['season_id'=>999999],'Saison inexistante refusée','saison');refuses(['site_id'=>999999],'Ferme protégée','ferme');refuses(['version'=>'obsolete'],'Version obsolète refusée','depuis son ouverture');
$m->updateCampaign($id,$base,$user);$updated=sql('SELECT * FROM agricultural_campaigns WHERE id=?',[$id])->fetch();check($updated['name']==='Campagne corrigée','Modification persistée');$audit=sql("SELECT * FROM activity_logs WHERE entity_type='agricultural_campaigns' AND entity_id=? AND action='update_campaign' ORDER BY id DESC LIMIT 1",[$id])->fetch();check(json_decode($audit['old_values'],true)['name']===$old['name']&&json_decode($audit['new_values'],true)['name']===$updated['name'],'Anciennes et nouvelles valeurs auditées');refuses([],'Écriture concurrente refusée','depuis son ouverture');
$base=array_merge($updated,['version'=>Agriculture::campaignVersion($updated),'reason'=>'Test période']);
$cp=sql("SELECT cp.* FROM agricultural_campaign_plots cp JOIN agricultural_campaigns c ON c.id=cp.campaign_id WHERE c.site_id=? LIMIT 1",[Auth::$site])->fetch();sql("INSERT INTO agricultural_campaign_plots(campaign_id,plot_id,variety_id,planned_area_ha,actual_area_ha,target_tons_per_ha,status) VALUES(?,?,?,1,1,1,'in_progress')",[$id,$cp['plot_id'],$cp['variety_id']]);$plan=$db->lastInsertId();sql("INSERT INTO agricultural_works(campaign_plot_id,work_type,worked_at,status,created_by) VALUES(?,'Labour','2026-06-15 10:00:00','completed',?)",[$plan,$user['id']]);
refuses(['end_date'=>'2026-05-31'],'Travail existant reste dans la période','15/06/2026');
$m->updateCampaign($id,array_replace($base,['status'=>'closed']),$user);check(sql('SELECT status FROM agricultural_campaigns WHERE id=?',[$id])->fetchColumn()==='closed','Statut modifiable par administrateur');
echo "Tests de modification de campagne terminés.\n";
