<?php
require dirname(__DIR__).'/app/helpers/functions.php';
class Auth{static $site=null;static function currentSiteId(){return self::$site;}static function can(...$args){return true;}}
function check($ok,$label){if(!$ok)throw new RuntimeException($label);echo "OK - $label\n";}
$refs=['farm_sites'=>[['id'=>1,'name'=>'Ferme A','code'=>'FARM-MUT'],['id'=>2,'name'=>'Ferme B','code'=>'FARM-DIK']]];
$campaigns=[['id'=>1,'name'=>'Campagne A']];$campaignPlots=[['id'=>1,'campaign_id'=>1,'plot_name'=>'Parcelle A']];
$base=['id'=>1,'site_id'=>1,'harvest_id'=>1,'status'=>'available','physical_quantity_kg'=>100,'reserved_quantity_kg'=>30,'available_quantity_kg'=>70,'product_name'=>'Maïs','variety_name'=>'Variété'];
$stocks=[$base,array_replace($base,['id'=>2,'harvest_id'=>2,'physical_quantity_kg'=>50,'reserved_quantity_kg'=>0,'available_quantity_kg'=>50]),array_replace($base,['id'=>3,'harvest_id'=>3,'status'=>'cancelled','physical_quantity_kg'=>999]),array_replace($base,['id'=>4,'harvest_id'=>4,'physical_quantity_kg'=>999]),array_replace($base,['id'=>5,'harvest_id'=>5,'status'=>'depleted','physical_quantity_kg'=>0,'reserved_quantity_kg'=>0,'available_quantity_kg'=>0])];
$harvests=[];foreach([1,2,3,4,5] as$id)$harvests[]=['id'=>$id,'campaign_plot_id'=>1,'status'=>$id===4?'cancelled':'validated','harvest_number'=>'REC-'.$id,'campaign_code'=>'C1','plot_code'=>'P1','harvested_at'=>'2026-09-12','has_draft_transport'=>$id===2];$transports=[];
ob_start();require view_path('agriculture.depots');$html=ob_get_clean();
check(count($depots)===2,'Dépôt vide également visible');check($depots[1]['physical']===150.0&&$depots[1]['reserved']===30.0&&$depots[1]['available']===120.0,'Agrégation physique/réservé/disponible exacte');check(count($depots[1]['lots'])===3,'Stocks annulés et récoltes annulées exclus');check(str_contains($html,'data-depot-stock="1"')&&!str_contains($html,'data-depot-stock="2"'),'Transport proposé seulement sans brouillon existant');check(str_contains($html,'Lots épuisés'),'Lots épuisés consultables');check(str_contains($html,'<svg class="depot-illustration"'),'Illustrations vectorielles locales');check(str_contains($html,'80,0 % disponible, 20,0 % réservé'),'Répartition proportionnelle au stock physique');check(str_contains($html,'Aucun stock en dépôt'),'Dépôt vide sans fausse jauge de capacité');Auth::$site=2;ob_start();require view_path('agriculture.depots');ob_end_clean();check(count($depots)===1&&isset($depots[2]),'Périmètre de ferme sélectionnée respecté');
