<?php
require dirname(__DIR__).'/app/helpers/functions.php';require dirname(__DIR__).'/app/core/Database.php';require dirname(__DIR__).'/app/core/Model.php';
if(!preg_match('/_(test|testing)$/',config('database.database')))throw new RuntimeException('Base de test obligatoire');
class Auth{static $admin=false,$allowed=true,$site;static function hasRole($r){return self::$admin;}static function requireSiteAccess($s){if((int)$s!==self::$site)throw new RuntimeException('Site interdit');}static function requirePermission($m,$a,$s){self::requireSiteAccess($s);if(!self::$allowed)throw new RuntimeException('Droit refusé');}static function currentSiteId(){return self::$site;}}
require dirname(__DIR__).'/app/models/Agriculture.php';$db=Database::getInstance()->connection();$m=new Agriculture();
function sql($q,$p=[]){global $db;$s=$db->prepare($q);$s->execute($p);return $s;}
function check($ok,$label){if(!$ok)throw new RuntimeException($label);echo "OK - $label\n";}
Auth::$site=(int)sql("SELECT id FROM sites WHERE code='FARM-MUT'")->fetchColumn();$user=['id'=>(int)sql('SELECT id FROM users LIMIT 1')->fetchColumn()];$tag=bin2hex(random_bytes(5));$source=sql('SELECT cp.*,c.season_id FROM agricultural_campaign_plots cp JOIN agricultural_campaigns c ON c.id=cp.campaign_id WHERE c.site_id=? LIMIT 1',[Auth::$site])->fetch();
sql("INSERT INTO agricultural_campaigns(site_id,season_id,code,name,start_date,end_date,status,created_by) VALUES(?,?,?,'Test correction récolte','2020-01-01','2099-12-31','in_progress',?)",[Auth::$site,$source['season_id'],'HC-'.$tag,$user['id']]);$campaign=$db->lastInsertId();sql("INSERT INTO agricultural_campaign_plots(campaign_id,plot_id,variety_id,planned_area_ha,actual_area_ha,target_tons_per_ha,status) VALUES(?,?,?,10,10,3,'in_progress')",[$campaign,$source['plot_id'],$source['variety_id']]);$cp=$db->lastInsertId();
$base=['campaign_plot_id'=>$cp,'harvested_at'=>'2026-09-12T09:00','gross_weight_kg'=>1100,'tare_weight_kg'=>100,'drying_loss_kg'=>0,'moisture_before'=>0,'moisture_after'=>0,'drying_started_at'=>'','drying_ended_at'=>''];$id=$m->createHarvest($base,$user);
function payload($patch=[]){global $base,$id;return array_replace($base,['reason'=>'Correction test','version'=>Agriculture::harvestVersion(sql('SELECT * FROM agricultural_harvests WHERE id=?',[$id])->fetch())],$patch);}
function refuses($patch,$text){global $m,$user,$id;$before=sql('SELECT * FROM agricultural_harvests WHERE id=?',[$id])->fetch();$caught=false;try{$m->updateHarvest($id,payload($patch),$user);}catch(RuntimeException $e){$caught=str_contains($e->getMessage(),$text);}check($caught&&$before===sql('SELECT * FROM agricultural_harvests WHERE id=?',[$id])->fetch(),'Refus atomique : '.$text);}
$m->updateHarvest($id,payload(['gross_weight_kg'=>1200]),$user);check((float)sql('SELECT net_weight_kg FROM agricultural_harvests WHERE id=?',[$id])->fetchColumn()===1100.0,'Non-administrateur modifie une récolte soumise');check(!sql('SELECT id FROM agricultural_stocks WHERE harvest_id=?',[$id])->fetch(),'Pas de stock avant validation');
refuses(['gross_weight_kg'=>-1],'poids');refuses(['gross_weight_kg'=>'abc'],'poids');refuses(['tare_weight_kg'=>5000],'poids brut');refuses(['moisture_before'=>101],'humidité');refuses(['harvested_at'=>'2026-02-30T10:00'],'date');refuses(['drying_ended_at'=>'2026-09-11T10:00'],'séchage');refuses(['reason'=>''],'motif');refuses(['campaign_plot_id'=>999999],'parcelle');refuses(['version'=>'old'],'a changé');Auth::$allowed=false;refuses([],'Droit refusé');Auth::$allowed=true;Auth::$site++;refuses([],'Site interdit');Auth::$site--;
Auth::$admin=true;$stock=$m->validateHarvest($id,$user);Auth::$admin=false;refuses([],'administrateur');Auth::$admin=true;
$m->updateHarvest($id,payload(['gross_weight_kg'=>1400]),$user);check((float)sql('SELECT physical_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn()===1300.0,'Correction validée ajuste le stock');check(sql('SELECT status FROM agricultural_harvests WHERE id=?',[$id])->fetchColumn()==='validated','Validation conservée');check((float)sql('SELECT yield_tons_per_ha FROM agricultural_harvests WHERE id=?',[$id])->fetchColumn()===0.13,'Rendement recalculé');
$m->updateHarvest($id,payload(['gross_weight_kg'=>1350]),$user);check((int)sql("SELECT COUNT(*) FROM agricultural_stock_movements WHERE stock_id=? AND reference_type='activity_logs'",[$stock])->fetchColumn()===2,'Corrections successives tracées sans collision');
sql("UPDATE agricultural_stocks SET physical_quantity_kg=250,reserved_quantity_kg=150,status='reserved' WHERE id=?",[$stock]);refuses(['gross_weight_kg'=>1100],'expédiée ou réservée');
$m->updateHarvest($id,payload(['gross_weight_kg'=>1400]),$user);check((float)sql('SELECT physical_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn()===300.0,'Après expédition : correction du seul stock restant');check((float)sql('SELECT reserved_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn()===150.0,'Réservations conservées');
$dest=sql("SELECT id FROM sites WHERE code='SILO'")->fetchColumn();sql("INSERT INTO agricultural_transports(stock_id,source_site_id,destination_site_id,transport_number,quantity_kg,status,created_by) VALUES(?,?,?, ?,100,'draft',?)",[$stock,Auth::$site,$dest,'HCT-'.$tag,$user['id']]);refuses(['gross_weight_kg'=>1300],'brouillon');
$before=(float)sql('SELECT physical_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn();$data=payload(['gross_weight_kg'=>1400,'moisture_after'=>12]);$m->updateHarvest($id,$data,$user);check($before===(float)sql('SELECT physical_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn(),'Correction humidité sans mouvement de stock');check((int)sql("SELECT COUNT(*) FROM activity_logs WHERE entity_type='agricultural_harvests' AND entity_id=? AND action='update_harvest'",[$id])->fetchColumn()===5,'Motifs et anciennes/nouvelles valeurs audités');
sql("UPDATE agricultural_harvests SET status='cancelled' WHERE id=?",[$id]);refuses([],'annulée');sql("UPDATE agricultural_harvests SET status='validated' WHERE id=?",[$id]);echo "Tests terminés.\n";
