<?php
require __DIR__.'/integration/TestBootstrap.php';$db=DagrilIntegrationTest::boot();$user=DagrilIntegrationTest::loginRole('administrateur','all');require dirname(__DIR__).'/app/models/MachineFeed.php';require dirname(__DIR__).'/app/models/ProductionBatch.php';$feeds=new MachineFeed();$m=new ProductionBatch();$machine=$feeds->machinesForSelect()[0];$silo=array_values(array_filter($feeds->silosForSelect(),fn($s)=>(float)$s['current_stock_kg']>=100))[0];$fid=$feeds->createFeed(['machine_id'=>$machine['id'],'silo_id'=>$silo['id'],'quantity_kg'=>100,'authorized_quantity_kg'=>100,'fed_at'=>date('Y-m-d H:i:s'),'ended_at'=>'','observation'=>'Test résultats production'],$user);$id=DagrilIntegrationTest::scalar('SELECT id FROM production_batches WHERE machine_feed_id=?',[$fid]);$type=$m->wasteTypes()[0]['id'];
$payload=function($patch=[])use($m,$id,$type){return array_replace(['production_batch_id'=>$id,'version'=>ProductionBatch::version($m->findDetailed($id)),'output_quantity_kg'=>80,'waste_lines'=>[$type=>19],'variance_tolerance_percent'=>2,'variance_justification'=>'','ended_at'=>date('Y-m-d H:i:s')],$patch);};
DagrilIntegrationTest::check(count($m->pendingForSelect())>0,'Lots disponibles en vue consolidée');
DagrilIntegrationTest::expectException(fn()=>$m->submitResults($payload(['ended_at'=>'2000-01-01T00:00']),$user),'Fin antérieure au début refusée');
DagrilIntegrationTest::expectException(fn()=>$m->submitResults($payload(['ended_at'=>'2026-02-30T10:00']),$user),'Date impossible refusée');
DagrilIntegrationTest::expectException(fn()=>$m->submitResults($payload(['output_quantity_kg'=>INF]),$user),'Quantité non finie refusée');
$old=$payload();$m->submitResults($old,$user);DagrilIntegrationTest::check($m->findDetailed($id)['status']==='results_submitted','Soumission dans la tolérance → à valider');DagrilIntegrationTest::check(!DagrilIntegrationTest::scalar('SELECT id FROM bulk_flour_stocks WHERE production_batch_id=?',[$id]),'Aucun stock avant validation');
DagrilIntegrationTest::expectException(fn()=>$m->submitResults($old,$user),'Soumission obsolète refusée');DagrilIntegrationTest::expectException(fn()=>$m->submitResults($payload(),$user),'Correction sans motif refusée');
$m->submitResults($payload(['output_quantity_kg'=>70,'variance_justification'=>'Perte mesurée','correction_reason'=>'Correction pesée farine']),$user);DagrilIntegrationTest::check($m->findDetailed($id)['status']==='pending_additional_approval','Correction recalcule l’écart et impose approbation complémentaire');
DagrilIntegrationTest::expectException(fn()=>$m->validateProduction(['production_batch_id'=>$id],$user),'Déclarant ne peut pas approuver son propre écart');
$validator=DagrilIntegrationTest::loginRole('direction',$machine['site_id']);$m->validateProduction(['production_batch_id'=>$id],$validator);$b=$m->findDetailed($id);DagrilIntegrationTest::check($b['status']==='validated'&&(int)$b['additional_approved_by']===(int)$validator['id']&&$b['additional_approved_at'],'Validation et approbation complémentaire correctement tracées');DagrilIntegrationTest::check((float)DagrilIntegrationTest::scalar('SELECT quantity_kg FROM bulk_flour_stocks WHERE production_batch_id=?',[$id])===70.0,'Stock farine créé après validation');DagrilIntegrationTest::expectException(fn()=>$m->submitResults($payload(['correction_reason'=>'Interdit']),$validator),'Lot validé non modifiable');DagrilIntegrationTest::expectException(fn()=>$m->validateProduction(['production_batch_id'=>$id],$validator),'Double validation refusée');DagrilIntegrationTest::finish();
