<section class="dashboard-hero"><span class="hero-icon"><i class="bi bi-truck"></i></span><div><p class="section-label">Transport</p><h2>BT et mise en transit</h2><p>Enregistrez l’origine, le chargement et le transport avant la première pesée.</p></div></section>
<?php if($success):?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif;?>
<?php if($error):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?>
<section class="form-panel"><form method="post" action="<?=e(base_url('weighbridge-transports'))?>" class="enterprise-form"><?=csrf_field()?>
<div class="form-grid">
<label><span>Origine</span><select name="origin_type" required><option value="external_supplier">Fournisseur externe</option><option value="internal_farm">Ferme DAGRIL</option></select><?php if(isset($errors['origin_type'])):?><small><?=e($errors['origin_type'])?></small><?php endif;?></label>
<label><span>Fournisseur (externe)</span><select name="supplier_id"><option value="">—</option><?php foreach($references['suppliers'] as $r):?><option value="<?=e($r['id'])?>"><?=e($r['name'])?></option><?php endforeach;?></select><?php if(isset($errors['supplier_id'])):?><small><?=e($errors['supplier_id'])?></small><?php endif;?></label>
<label><span>Ferme d’origine (interne)</span><select name="origin_site_id"><option value="">—</option><?php foreach($references['sites'] as $r):?><option value="<?=e($r['id'])?>"><?=e($r['code'].' — '.$r['name'])?></option><?php endforeach;?></select><?php if(isset($errors['origin_site_id'])):?><small><?=e($errors['origin_site_id'])?></small><?php endif;?></label>
<label><span>Produit</span><select name="product_id" required><option value="">Sélectionner</option><?php foreach($references['products'] as $r):?><option value="<?=e($r['id'])?>"><?=e($r['name'])?></option><?php endforeach;?></select></label>
<label><span>Quantité expédiée (kg)</span><input type="number" step="0.001" min="0.001" name="shipped_quantity_kg" required></label>
<label><span>Camion</span><input name="truck_plate_number" required></label><label><span>Chauffeur</span><input name="driver_name"></label><label><span>Téléphone</span><input name="driver_phone"></label>
<label><span>Trajet</span><input name="route_description"></label><label><span>Péages</span><input type="number" step="0.01" min="0" name="toll_amount" value="0"></label><label><span>Détail péages</span><input name="toll_details"></label>
</div><div class="form-actions"><button class="btn-primary"><i class="bi bi-send"></i><span>Créer BT et mettre en transit</span></button></div></form></section>
<section class="table-panel"><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>BT</th><th>Origine</th><th>Camion</th><th>Produit</th><th>Expédié</th><th>Statut</th><th>Pesée</th></tr></thead><tbody><?php foreach($transports as $t):?><tr><td><?=e($t['bt_number']?:$t['transport_reference'])?></td><td><?=e($t['origin_type']==='internal_farm'?($t['origin_site_name']?:'-'):($t['supplier_name']?:'-'))?></td><td><?=e($t['plate_number'].' / '.($t['driver_name']?:'-'))?></td><td><?=e($t['product_name'])?></td><td><?=e(number_format((float)$t['shipped_quantity_kg'],3,',',' '))?> kg</td><td><?=e($t['status'])?></td><td><?=e($t['weighing_reference']?:'-')?></td></tr><?php endforeach;?></tbody></table></div></section>
