<?php $canProcess=Auth::currentSiteId()!==null&&$availableStock>0&&!empty($machines); ?>
<section id="wasteProcess" class="entity-modal workspace-entity-modal feed-editor" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="wasteProcessTitle">
<header><div><p class="page-kicker">DÉCHETS ET COPRODUITS</p><h2 id="wasteProcessTitle">Traiter des déchets</h2><p>Renseignez les déchets consommés et l’aliment pour bétail obtenu.</p></div><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header>
<form method="post" action="<?=e(base_url('waste/process'))?>" class="enterprise-form" data-waste-process-form data-confirm="Valider ce traitement ? Les déchets seront consommés et l’aliment pour bétail sera ajouté au stock immédiatement."><?=csrf_field()?>
<div class="feed-form-body"><p class="app-alert app-alert-error" data-feed-error hidden role="alert"></p>
<?php if(Auth::currentSiteId()===null):?><p class="app-alert">Sélectionnez un site précis dans le menu de l’application avant de traiter les déchets.</p><?php else:?><p class="waste-sale-summary">Stock utilisable du site : <strong><?=e(number_format($availableStock,3,',',' '))?> kg</strong><br>Les lots les plus anciens sont consommés en premier, stock tampon inclus.</p><?php if($availableStock<=0):?><p class="app-alert">Aucun stock utilisable sur ce site.</p><?php endif;?><?php if(!$machines):?><p class="app-alert">Aucune machine de traitement active sur ce site.</p><?php endif;?><?php endif;?>
<div class="form-grid"><label class="form-wide">Machine de traitement *<select name="machine_id" required <?=!$canProcess?'disabled':''?>><option value="">Sélectionner une machine</option><?php foreach($machines as$m):?><option value="<?=e($m['id'])?>"><?=e($m['name'])?></option><?php endforeach;?></select></label>
<label>Déchets consommés (kg) *<input type="number" name="input_quantity_kg" min="0.001" max="<?=e($availableStock)?>" step="0.001" required></label><label>Aliment pour bétail produit (kg) *<input type="number" name="output_quantity_kg" min="0" step="0.001" required></label>
<label class="form-wide">Date et heure du traitement *<input type="datetime-local" name="processed_at" value="<?=e(date('Y-m-d\TH:i'))?>" required></label></div>
<p class="waste-sale-summary" data-process-yield aria-live="polite">Renseignez les quantités pour afficher le rendement.</p></div>
<footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary" <?=!$canProcess?'disabled':''?>>Valider le traitement</button></footer></form></section>
