<?php

require_once dirname(__DIR__) . '/app/helpers/functions.php';
require_once dirname(__DIR__) . '/app/helpers/icons.php';

$autoloadFile = dirname(__DIR__) . '/vendor/autoload.php';
if (file_exists($autoloadFile)) {
    require_once $autoloadFile;
}

date_default_timezone_set(config('app.timezone', 'UTC'));

if (config('app.debug', false)) {
    error_reporting(E_ALL);
    ini_set('display_errors', '1');
} else {
    error_reporting(0);
    ini_set('display_errors', '0');
}

require_once dirname(__DIR__) . '/app/core/Database.php';
require_once dirname(__DIR__) . '/app/core/Model.php';
require_once dirname(__DIR__) . '/app/core/Controller.php';
require_once dirname(__DIR__) . '/app/core/Auth.php';
require_once dirname(__DIR__) . '/app/core/Router.php';
require_once dirname(__DIR__) . '/app/services/PdfService.php';
require_once dirname(__DIR__) . '/app/services/AuthorizationService.php';

$router = new Router();

$router->get('/silo-administration', 'Silo@administration', ['auth' => true, 'permission' => ['silos', 'administer']]);
$router->get('/silo-administration/create', 'Silo@create', ['auth' => true, 'permission' => ['silos', 'administer']]);
$router->post('/silo-administration', 'Silo@store', ['auth' => true, 'permission' => ['silos', 'administer']]);
$router->get('/silo-administration/{id}/edit', 'Silo@edit', ['auth' => true, 'permission' => ['silos', 'administer']]);
$router->post('/silo-administration/{id}/update', 'Silo@update', ['auth' => true, 'permission' => ['silos', 'administer']]);
$router->post('/silo-administration/{id}/status', 'Silo@setStatus', ['auth' => true, 'permission' => ['silos', 'administer']]);

$router->get('/', 'Dashboard@index', ['auth' => true]);
$router->get('/login', 'Auth@showLogin');
$router->post('/login', 'Auth@login');
$router->post('/logout', 'Auth@logout', ['auth' => true]);
$router->post('/context/site', 'Site@selectContext', ['auth' => true]);

$router->get('/dashboard', 'Dashboard@index', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/direction', 'Dashboard@direction', ['auth' => true, 'roles' => ['direction', 'administrateur']]);
$router->get('/terrain/pont-bascule', 'Dashboard@pontBasculeHome', ['auth' => true, 'roles' => ['agent-pont-bascule']]);
$router->get('/terrain/silo', 'Dashboard@siloHome', ['auth' => true, 'roles' => ['agent-silo']]);
$router->get('/terrain/production', 'Dashboard@productionHome', ['auth' => true, 'roles' => ['agent-production']]);
$router->get('/terrain/emballage', 'Dashboard@packagingHome', ['auth' => true, 'roles' => ['agent-emballage']]);
$router->get('/terrain/distribution', 'Dashboard@distributionHome', ['auth' => true, 'roles' => ['agent-distribution']]);
$router->get('/reports', 'Report@index', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/analytics', 'Analytics@index', ['auth' => true, 'permission' => ['analytics','read']]);
$router->get('/analytics/{code}', 'Analytics@detail', ['auth' => true, 'permission' => ['analytics','read']]);
$router->get('/reports/daily', 'Report@daily', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/supplier', 'Report@supplier', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/production', 'Report@production', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/waste', 'Report@waste', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/yield', 'Report@yield', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/stocks', 'Report@stocks', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/distribution', 'Report@distribution', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/reports/packaging', 'Report@packaging', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/suppliers', 'Supplier@index', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->get('/suppliers/create', 'Supplier@create', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->post('/suppliers', 'Supplier@store', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->get('/suppliers/{id}/edit', 'Supplier@edit', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->post('/suppliers/{id}/update', 'Supplier@update', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->post('/suppliers/{id}/delete', 'Supplier@destroy', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/trucks', 'Truck@index', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->get('/trucks/create', 'Truck@create', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->post('/trucks', 'Truck@store', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->get('/trucks/{id}/edit', 'Truck@edit', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->post('/trucks/{id}/update', 'Truck@update', ['auth' => true, 'roles' => ['administrateur', 'direction', 'agent-pont-bascule']]);
$router->post('/trucks/{id}/delete', 'Truck@destroy', ['auth' => true, 'roles' => ['administrateur', 'direction']]);
$router->get('/weighings', 'Weighing@index', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->get('/weighbridge-transports', 'WeighbridgeTransport@index', ['auth' => true, 'permission' => ['weighings','read']]);
$router->post('/weighbridge-transports', 'WeighbridgeTransport@store', ['auth' => true, 'permission' => ['weighings','create']]);
$router->get('/weighings/entry', 'Weighing@entry', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->post('/weighings/entry', 'Weighing@storeEntry', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->get('/weighings/exit', 'Weighing@exitList', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->get('/weighings/{id}/exit', 'Weighing@exitForm', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->post('/weighings/{id}/exit/prepare', 'Weighing@prepareExit', ['auth' => true, 'permission' => ['weighings','update']]);
$router->post('/weighings/{id}/exit', 'Weighing@validateExit', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->get('/weighings/{id}/ticket', 'Weighing@ticket', ['auth' => true, 'roles' => ['agent-pont-bascule', 'direction', 'administrateur']]);
$router->post('/weighings/{id}/return', 'Weighing@progressReturn', ['auth' => true, 'permission' => ['weighings','update']]);
$router->get('/agriculture','Agriculture@index',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/campaigns','Agriculture@campaigns',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/plots','Agriculture@plots',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/planning','Agriculture@planning',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/inputs','Agriculture@inputs',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/works/data','Agriculture@workData',['auth'=>true,'permission'=>['agriculture','read']]);
$router->post('/agriculture/works/{id}/correct','Agriculture@correctWork',['auth'=>true,'permission'=>['agriculture','update']]);
$router->post('/agriculture/works/{id}/cancel','Agriculture@cancelWork',['auth'=>true,'permission'=>['agriculture','delete']]);
$router->get('/agriculture/works','Agriculture@works',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/harvests','Agriculture@harvests',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/stocks','Agriculture@stocks',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/transports','Agriculture@transports',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/workers','Agriculture@workers',['auth'=>true,'permission'=>['agriculture','read']]);
$router->get('/agriculture/equipment','Agriculture@equipmentDirectory',['auth'=>true,'permission'=>['agriculture','read']]);
$router->post('/agriculture/campaigns/{id}/update','Agriculture@updateCampaign',['auth'=>true,'roles'=>['administrateur'],'permission'=>['agriculture','update']]);
$router->post('/agriculture/campaigns','Agriculture@campaign',['auth'=>true,'permission'=>['agriculture','create']]);
$router->post('/agriculture/plots','Agriculture@plot',['auth'=>true,'permission'=>['agriculture','administer']]);
$router->post('/agriculture/campaign-plots','Agriculture@planPlot',['auth'=>true,'permission'=>['agriculture','create']]);
$router->post('/agriculture/inputs','Agriculture@input',['auth'=>true,'permission'=>['agriculture','update']]);
$router->post('/agriculture/workers','Agriculture@worker',['auth'=>true,'permission'=>['agriculture','administer']]);
$router->post('/agriculture/equipment','Agriculture@equipment',['auth'=>true,'permission'=>['agriculture','administer']]);
$router->post('/agriculture/works','Agriculture@work',['auth'=>true,'permission'=>['agriculture','update']]);
$router->post('/agriculture/harvests','Agriculture@harvest',['auth'=>true,'permission'=>['agriculture','create']]);
$router->post('/agriculture/harvests/{id}/update','Agriculture@updateHarvest',['auth'=>true,'permission'=>['agriculture','update']]);
$router->post('/agriculture/harvests/{id}/validate','Agriculture@validateHarvest',['auth'=>true,'permission'=>['agriculture','validate']]);
$router->post('/agriculture/transports','Agriculture@transport',['auth'=>true,'permission'=>['agriculture','create']]);
$router->post('/agriculture/transports/{id}/approve','Agriculture@approveTransport',['auth'=>true,'permission'=>['agriculture','validate']]);
$router->post('/agriculture/transports/{id}/dispatch','Agriculture@dispatchTransport',['auth'=>true,'permission'=>['agriculture','update']]);
$router->get('/livestock','Livestock@index',['auth'=>true,'permission'=>['livestock','read']]);
$router->get('/livestock/lots','Livestock@lots',['auth'=>true,'permission'=>['livestock','read']]);
$router->get('/livestock/species/{id}','Livestock@speciesLots',['auth'=>true,'permission'=>['livestock','read']]);
$router->get('/livestock/daily','Livestock@daily',['auth'=>true,'permission'=>['livestock','read']]);
$router->get('/livestock/conversions','Livestock@conversionsPage',['auth'=>true,'permission'=>['livestock','read']]);
$router->get('/livestock/transfers','Livestock@transfersPage',['auth'=>true,'permission'=>['livestock','read']]);
$router->get('/livestock/facilities','Livestock@facilitiesPage',['auth'=>true,'permission'=>['livestock','administer']]);
$router->post('/livestock/facilities/{id}/update','Livestock@updateFacility',['auth'=>true,'permission'=>['livestock','administer']]);
$router->post('/livestock/facilities','Livestock@facility',['auth'=>true,'permission'=>['livestock','administer']]);
$router->post('/livestock/batches','Livestock@batch',['auth'=>true,'permission'=>['livestock','create']]);
$router->post('/livestock/feedings','Livestock@feed',['auth'=>true,'permission'=>['livestock','update']]);
$router->post('/livestock/weighings','Livestock@weigh',['auth'=>true,'permission'=>['livestock','update']]);
$router->post('/livestock/poultry','Livestock@poultry',['auth'=>true,'permission'=>['livestock','update']]);
$router->post('/livestock/conversions','Livestock@conversion',['auth'=>true,'permission'=>['livestock','create']]);
$router->post('/livestock/fish-catches','Livestock@fishCatch',['auth'=>true,'permission'=>['livestock','create']]);
$router->post('/livestock/conversions/{id}/validate','Livestock@validateConversion',['auth'=>true,'permission'=>['livestock','validate']]);
$router->post('/livestock/transfers','Livestock@transfer',['auth'=>true,'permission'=>['livestock','create']]);
$router->post('/livestock/transfers/{id}/approve','Livestock@approveTransfer',['auth'=>true,'permission'=>['livestock','validate']]);
$router->post('/livestock/transfers/{id}/dispatch','Livestock@dispatchTransfer',['auth'=>true,'permission'=>['livestock','update']]);
$router->get('/butchery','Butchery@index',['auth'=>true,'permission'=>['butchery','read']]);
$router->get('/butchery/{section}','Butchery@index',['auth'=>true,'permission'=>['butchery','read']]);
$router->post('/butchery/receipts','Butchery@receipt',['auth'=>true,'permission'=>['butchery','create']]);
$router->post('/butchery/receipts/{id}/control','Butchery@control',['auth'=>true,'permission'=>['butchery','validate']]);
$router->post('/butchery/slaughters','Butchery@slaughter',['auth'=>true,'permission'=>['butchery','create']]);
$router->post('/butchery/slaughters/{id}/validate','Butchery@validateSlaughter',['auth'=>true,'permission'=>['butchery','validate']]);
$router->post('/butchery/recipes','Butchery@recipe',['auth'=>true,'permission'=>['butchery','administer']]);
$router->post('/butchery/orders','Butchery@order',['auth'=>true,'permission'=>['butchery','create']]);
$router->post('/butchery/orders/{id}/results','Butchery@results',['auth'=>true,'permission'=>['butchery','update']]);
$router->post('/butchery/orders/{id}/validate','Butchery@validateOrder',['auth'=>true,'permission'=>['butchery','validate']]);
$router->post('/butchery/sales','Butchery@sale',['auth'=>true,'permission'=>['butchery','create']]);
$router->post('/butchery/transfers','Butchery@transfer',['auth'=>true,'permission'=>['butchery','create']]);
$router->post('/butchery/transfers/{id}/approve','Butchery@approveTransfer',['auth'=>true,'permission'=>['butchery','validate']]);
$router->post('/butchery/transfers/{id}/dispatch','Butchery@dispatchTransfer',['auth'=>true,'permission'=>['butchery','update']]);
$router->get('/budgets','Budget@index',['auth'=>true,'permission'=>['budgets','read']]);
$router->post('/budgets/fiscal-years','Budget@year',['auth'=>true,'permission'=>['budgets','administer']]);
$router->post('/budgets','Budget@budget',['auth'=>true,'permission'=>['budgets','create']]);
$router->post('/budgets/{id}/submit','Budget@submit',['auth'=>true,'permission'=>['budgets','create']]);
$router->post('/budgets/{id}/approve-df','Budget@df',['auth'=>true,'permission'=>['budgets','validate']]);
$router->post('/budgets/{id}/approve-dg','Budget@dg',['auth'=>true,'permission'=>['budgets','validate']]);
$router->post('/budgets/{id}/revisions','Budget@revise',['auth'=>true,'permission'=>['budgets','update']]);
$router->post('/budgets/commitments','Budget@commitment',['auth'=>true,'permission'=>['budgets','update']]);
$router->post('/budgets/expenses','Budget@expense',['auth'=>true,'permission'=>['budgets','create']]);
$router->post('/budgets/expenses/{id}/approve-df','Budget@expenseDf',['auth'=>true,'permission'=>['budgets','validate']]);
$router->post('/budgets/derogations/{id}/approve','Budget@derogation',['auth'=>true,'permission'=>['budgets','validate']]);
$router->post('/budgets/delegations','Budget@delegation',['auth'=>true,'permission'=>['budgets','administer']]);
$router->post('/budgets/delegations/{id}/approve','Budget@approveDelegation',['auth'=>true,'permission'=>['budgets','administer']]);
$router->get('/fuel-logistics','FuelLogistics@index',['auth'=>true,'permission'=>['fuel-logistics','read']]);
$router->get('/cancellations','Cancellation@index',['auth'=>true,'permission'=>['cancellations','read']]);
$router->get('/traceability','Traceability@index',['auth'=>true,'permission'=>['traceability','read']]);
$router->get('/traceability/{chain}/{id}','Traceability@show',['auth'=>true,'permission'=>['traceability','read']]);
$router->post('/cancellations','Cancellation@store',['auth'=>true,'permission'=>['cancellations','create']]);
$router->post('/cancellations/{id}/approve','Cancellation@approve',['auth'=>true,'permission'=>['cancellations','validate']]);
$router->post('/cancellations/{id}/reject','Cancellation@reject',['auth'=>true,'permission'=>['cancellations','validate']]);
$router->post('/fuel-logistics/suppliers','FuelLogistics@supplier',['auth'=>true,'permission'=>['fuel-logistics','administer']]);
$router->post('/fuel-logistics/assets','FuelLogistics@asset',['auth'=>true,'permission'=>['fuel-logistics','administer']]);
$router->post('/fuel-logistics/people','FuelLogistics@person',['auth'=>true,'permission'=>['fuel-logistics','administer']]);
$router->post('/fuel-logistics/norms','FuelLogistics@norm',['auth'=>true,'permission'=>['fuel-logistics','administer']]);
$router->post('/fuel-logistics/routes','FuelLogistics@route',['auth'=>true,'permission'=>['fuel-logistics','administer']]);
$router->post('/fuel-logistics/orders','FuelLogistics@order',['auth'=>true,'permission'=>['fuel-logistics','create']]);
$router->post('/fuel-logistics/orders/{id}/submit','FuelLogistics@submit',['auth'=>true,'permission'=>['fuel-logistics','create']]);
$router->post('/fuel-logistics/orders/{id}/approve','FuelLogistics@approve',['auth'=>true,'permission'=>['fuel-logistics','validate']]);
$router->post('/fuel-logistics/orders/{id}/receive','FuelLogistics@receive',['auth'=>true,'permission'=>['fuel-logistics','update']]);
$router->post('/fuel-logistics/distributions','FuelLogistics@distribution',['auth'=>true,'permission'=>['fuel-logistics','update']]);
$router->post('/fuel-logistics/missions','FuelLogistics@mission',['auth'=>true,'permission'=>['fuel-logistics','create']]);
$router->post('/fuel-logistics/missions/{id}/approve','FuelLogistics@approveMission',['auth'=>true,'permission'=>['fuel-logistics','validate']]);
$router->post('/fuel-logistics/missions/{id}/start','FuelLogistics@startMission',['auth'=>true,'permission'=>['fuel-logistics','update']]);
$router->post('/fuel-logistics/missions/{id}/complete','FuelLogistics@completeMission',['auth'=>true,'permission'=>['fuel-logistics','update']]);
$router->post('/fuel-logistics/missions/{id}/advances','FuelLogistics@advance',['auth'=>true,'permission'=>['fuel-logistics','create']]);
$router->post('/fuel-logistics/missions/{id}/settle','FuelLogistics@settle',['auth'=>true,'permission'=>['fuel-logistics','validate']]);
$router->post('/fuel-logistics/justifications','FuelLogistics@justification',['auth'=>true,'permission'=>['fuel-logistics','update']]);
$router->post('/fuel-logistics/adjustments','FuelLogistics@adjustment',['auth'=>true,'permission'=>['fuel-logistics','validate']]);
$router->post('/fuel-logistics/tolls','FuelLogistics@toll',['auth'=>true,'permission'=>['fuel-logistics','update']]);
$router->get('/silos', 'Silo@index', ['auth' => true, 'roles' => ['agent-silo', 'direction', 'administrateur']]);
$router->get('/silos/movements', 'Silo@movements', ['auth' => true, 'roles' => ['agent-silo', 'direction', 'administrateur']]);
$router->get('/silos/{id}', 'Silo@show', ['auth' => true, 'roles' => ['agent-silo', 'direction', 'administrateur']]);
$router->get('/machines', 'Machine@index', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->get('/machines/create', 'Machine@create', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/machines', 'Machine@store', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->get('/machines/{id}/edit', 'Machine@edit', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/machines/{id}/update', 'Machine@update', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/machines/{id}/toggle', 'Machine@toggle', ['auth' => true, 'roles' => ['direction', 'administrateur']]);
$router->get('/machine-feeds', 'MachineFeed@index', ['auth' => true, 'roles' => ['agent-silo', 'agent-production', 'direction', 'administrateur']]);
$router->get('/machine-feeds/create', 'MachineFeed@create', ['auth' => true, 'roles' => ['agent-silo', 'agent-production', 'direction', 'administrateur']]);
$router->post('/machine-feeds', 'MachineFeed@store', ['auth' => true, 'roles' => ['agent-silo', 'agent-production', 'direction', 'administrateur']]);
$router->get('/machine-feeds/{id}', 'MachineFeed@show', ['auth' => true, 'roles' => ['agent-silo', 'agent-production', 'direction', 'administrateur']]);
$router->get('/production', 'Production@index', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->get('/production/create', 'Production@create', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/production', 'Production@store', ['auth' => true, 'permission' => ['production', 'update']]);
$router->get('/production/export', 'Production@export', ['auth'=>true,'permission'=>['production','read']]);
$router->get('/production/{id}', 'Production@show', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/production/{id}/validate', 'Production@validateBatch', ['auth' => true, 'permission' => ['production','validate']]);
$router->post('/production/tolerance', 'Production@updateTolerance', ['auth' => true, 'permission' => ['production','administer']]);
$router->get('/waste', 'Waste@index', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->get('/waste/export', 'Waste@export', ['auth' => true, 'permission' => ['waste','read']]);
$router->get('/waste/process', 'Waste@process', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/waste/process', 'Waste@store', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->get('/waste/history', 'Waste@history', ['auth' => true, 'roles' => ['agent-production', 'direction', 'administrateur']]);
$router->post('/waste/{id}/buffer','Waste@buffer',['auth'=>true,'permission'=>['waste','update']]);
$router->post('/waste/sell','Waste@sell',['auth'=>true,'permission'=>['waste','validate']]);
$router->get('/pelletization','Pelletization@index',['auth'=>true,'permission'=>['pelletization','read']]);
$router->post('/pelletization/waste-transfers','Pelletization@wasteTransfer',['auth'=>true,'permission'=>['pelletization','create']]);
$router->post('/pelletization/waste-transfers/{id}/ship','Pelletization@shipTransfer',['auth'=>true,'permission'=>['pelletization','validate']]);
$router->post('/pelletization/waste-transfers/{id}/receive','Pelletization@receiveTransfer',['auth'=>true,'permission'=>['pelletization','validate']]);
$router->post('/pelletization/additives','Pelletization@additivePurchase',['auth'=>true,'permission'=>['pelletization','create']]);
$router->post('/pelletization/additives/{id}/receive','Pelletization@receiveAdditive',['auth'=>true,'permission'=>['pelletization','validate']]);
$router->post('/pelletization/recipes','Pelletization@recipe',['auth'=>true,'permission'=>['pelletization','administer']]);
$router->post('/pelletization/orders','Pelletization@order',['auth'=>true,'permission'=>['pelletization','create']]);
$router->post('/pelletization/orders/{id}/results','Pelletization@results',['auth'=>true,'permission'=>['pelletization','update']]);
$router->post('/pelletization/orders/{id}/validate','Pelletization@validateOrder',['auth'=>true,'permission'=>['pelletization','validate']]);
$router->post('/pelletization/orders/{id}/package','Pelletization@package',['auth'=>true,'permission'=>['pelletization','update']]);
$router->get('/packaging', 'Packaging@index', ['auth' => true, 'roles' => ['agent-emballage', 'direction', 'administrateur']]);
$router->get('/empty-packaging','EmptyPackaging@index',['auth'=>true,'permission'=>['empty-packaging','read']]);
$router->post('/empty-packaging/purchases','EmptyPackaging@storePurchase',['auth'=>true,'permission'=>['empty-packaging','create']]);
$router->post('/empty-packaging/purchases/{id}/approve','EmptyPackaging@approvePurchase',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->post('/empty-packaging/purchases/{id}/receive','EmptyPackaging@receivePurchase',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->post('/empty-packaging/requests','EmptyPackaging@storeRequest',['auth'=>true,'permission'=>['empty-packaging','create']]);
$router->post('/empty-packaging/requests/{id}/approve','EmptyPackaging@approveRequest',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->post('/empty-packaging/requests/{id}/issue','EmptyPackaging@issue',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->post('/empty-packaging/defects','EmptyPackaging@defect',['auth'=>true,'permission'=>['empty-packaging','update']]);
$router->post('/empty-packaging/stocks/{id}/minimum','EmptyPackaging@minimum',['auth'=>true,'permission'=>['empty-packaging','administer']]);
$router->post('/empty-packaging/transfers','EmptyPackaging@transfer',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->post('/empty-packaging/transfers/{id}/approve','EmptyPackaging@approveTransfer',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->post('/empty-packaging/transfers/{id}/receive','EmptyPackaging@receiveTransfer',['auth'=>true,'permission'=>['empty-packaging','validate']]);
$router->get('/packaging/create', 'Packaging@create', ['auth' => true, 'roles' => ['agent-emballage', 'direction', 'administrateur']]);
$router->post('/packaging', 'Packaging@store', ['auth' => true, 'roles' => ['agent-emballage', 'direction', 'administrateur']]);
$router->get('/packaging/history', 'Packaging@history', ['auth' => true, 'roles' => ['agent-emballage', 'direction', 'administrateur']]);
$router->get('/finished-stocks', 'FinishedStock@index', ['auth' => true, 'roles' => ['agent-emballage', 'agent-distribution', 'direction', 'administrateur']]);
$router->get('/finished-stocks/movements', 'FinishedStock@movements', ['auth' => true, 'roles' => ['agent-emballage', 'agent-distribution', 'direction', 'administrateur']]);
$router->get('/distributions', 'Distribution@index', ['auth' => true, 'roles' => ['agent-distribution', 'direction', 'administrateur']]);
$router->get('/distributions/create', 'Distribution@create', ['auth' => true, 'roles' => ['agent-distribution', 'direction', 'administrateur']]);
$router->post('/distributions', 'Distribution@store', ['auth' => true, 'roles' => ['agent-distribution', 'direction', 'administrateur']]);
$router->get('/distributions/{id}', 'Distribution@show', ['auth' => true, 'roles' => ['agent-distribution', 'direction', 'administrateur']]);
$router->get('/distributions/{id}/print', 'Distribution@print', ['auth' => true, 'roles' => ['agent-distribution', 'direction', 'administrateur']]);
$router->get('/alerts', 'Alert@index', ['auth' => true, 'roles' => ['direction', 'administrateur']]);
$router->post('/alerts/mark-all-read', 'Alert@markAllRead', ['auth' => true, 'roles' => ['direction', 'administrateur']]);
$router->post('/alerts/{id}/read', 'Alert@markRead', ['auth' => true, 'roles' => ['direction', 'administrateur']]);
$router->post('/alerts/{id}/resolve', 'Alert@resolve', ['auth' => true, 'permission' => ['alerts','validate']]);
$router->post('/activity-logs/{id}/review', 'ActivityLog@review', ['auth'=>true,'permission'=>['activity-logs','read']]);
$router->get('/activity-logs', 'ActivityLog@index', ['auth' => true, 'roles' => ['direction', 'administrateur']]);
$router->get('/users', 'User@index', ['auth' => true, 'permission' => ['users', 'administer']]);
$router->post('/users', 'User@store', ['auth' => true, 'permission' => ['users', 'administer']]);
$router->post('/users/{id}/update', 'User@update', ['auth' => true, 'permission' => ['users', 'administer']]);
$router->get('/sites', 'Site@index', ['auth' => true, 'roles' => ['administrateur']]);
$router->get('/sites/create', 'Site@create', ['auth' => true, 'roles' => ['administrateur']]);
$router->post('/sites', 'Site@store', ['auth' => true, 'roles' => ['administrateur']]);
$router->get('/sites/{id}/edit', 'Site@edit', ['auth' => true, 'roles' => ['administrateur']]);
$router->post('/sites/{id}/update', 'Site@update', ['auth' => true, 'roles' => ['administrateur']]);
$router->post('/sites/references/{type}', 'Site@storeReference', ['auth' => true, 'roles' => ['administrateur']]);
$router->post('/sites/users/{id}/assign', 'Site@assignUser', ['auth' => true, 'permission' => ['sites', 'administer']]);
$router->get('/access-control', 'AccessControl@index', ['auth' => true, 'permission' => ['rbac', 'administer']]);
$router->post('/access-control/assignments', 'AccessControl@storeAssignment', ['auth' => true, 'permission' => ['rbac', 'administer']]);
$router->post('/access-control/assignments/{id}/approve', 'AccessControl@approve', ['auth' => true, 'permission' => ['rbac', 'administer']]);
$router->post('/access-control/assignments/{id}/reject', 'AccessControl@reject', ['auth' => true, 'permission' => ['rbac', 'administer']]);
$router->post('/access-control/assignments/{id}/revoke', 'AccessControl@revoke', ['auth' => true, 'permission' => ['rbac', 'administer']]);
$router->post('/access-control/roles/{id}/permissions', 'AccessControl@updatePermissions', ['auth' => true, 'permission' => ['rbac', 'administer']]);
$router->get('/documents', 'Document@index', ['auth' => true, 'permission' => ['documents', 'read']]);
$router->get('/documents/{id}', 'Document@show', ['auth' => true, 'permission' => ['documents', 'read']]);
$router->post('/documents/{id}/attachments', 'Document@attach', ['auth' => true, 'permission' => ['documents', 'create']]);
$router->get('/documents/attachments/{id}/download', 'Document@download', ['auth' => true, 'permission' => ['documents', 'read']]);
$router->post('/documents/{id}/submit', 'Document@submit', ['auth' => true, 'permission' => ['workflows', 'create']]);
$router->post('/documents/{id}/request-approval', 'Document@requestApproval', ['auth' => true, 'permission' => ['workflows', 'create']]);
$router->post('/documents/{id}/approve', 'Document@approve', ['auth' => true, 'permission' => ['workflows', 'validate']]);
$router->post('/documents/{id}/reject', 'Document@reject', ['auth' => true, 'permission' => ['workflows', 'validate']]);
$router->post('/documents/{id}/start', 'Document@start', ['auth' => true, 'permission' => ['workflows', 'update']]);
$router->post('/documents/{id}/receive', 'Document@receive', ['auth' => true, 'permission' => ['workflows', 'update']]);
$router->post('/documents/{id}/close', 'Document@close', ['auth' => true, 'permission' => ['workflows', 'update']]);
$router->post('/documents/{id}/cancel', 'Document@cancel', ['auth' => true, 'permission' => ['workflows', 'delete']]);
$router->get('/transfers', 'Transfer@index', ['auth' => true, 'permission' => ['transfers', 'read']]);
$router->get('/transfers/create', 'Transfer@create', ['auth' => true, 'permission' => ['transfers', 'create']]);
$router->post('/transfers', 'Transfer@store', ['auth' => true, 'permission' => ['transfers', 'create']]);
$router->get('/transfers/{id}', 'Transfer@show', ['auth' => true, 'permission' => ['transfers', 'read']]);
$router->post('/transfers/{id}/submit', 'Transfer@submit', ['auth' => true, 'permission' => ['transfers', 'create']]);
$router->post('/transfers/{id}/approve', 'Transfer@approve', ['auth' => true, 'permission' => ['transfers', 'validate']]);
$router->post('/transfers/{id}/reserve', 'Transfer@reserve', ['auth' => true, 'permission' => ['transfers', 'validate']]);
$router->post('/transfers/{id}/ship', 'Transfer@ship', ['auth' => true, 'permission' => ['transfers', 'update']]);
$router->post('/transfers/{id}/receive', 'Transfer@receive', ['auth' => true, 'permission' => ['transfers', 'update']]);
$router->post('/transfers/{id}/returns/{returnId}/dispatch', 'Transfer@dispatchReturn', ['auth' => true, 'permission' => ['transfers', 'update']]);
$router->post('/transfers/{id}/returns/{returnId}/receive', 'Transfer@receiveReturn', ['auth' => true, 'permission' => ['transfers', 'update']]);
$router->post('/transfers/{id}/close', 'Transfer@close', ['auth' => true, 'permission' => ['transfers', 'update']]);

require_once dirname(__DIR__).'/app/services/AuditService.php';
AuditService::watchRequest();
$router->dispatch($_SERVER['REQUEST_METHOD'], $_SERVER['REQUEST_URI']);
