<?php
$depotHarvests=array_column($harvests,null,'id');$depotPlans=array_column($campaignPlots,null,'id');$depotCampaigns=array_column($campaigns,null,'id');$depotTransports=[];
foreach($transports as$t)$depotTransports[$t['stock_id']][]=$t;
$depots=[];foreach($refs['farm_sites'] as$farm){if(Auth::currentSiteId()&&(int)$farm['id']!==(int)Auth::currentSiteId())continue;$depots[$farm['id']]=['site'=>$farm,'lots'=>[],'physical'=>0,'reserved'=>0,'available'=>0];}
foreach($stocks as$stock){$harvest=$depotHarvests[$stock['harvest_id']]??null;if(!isset($depots[$stock['site_id']])||!$harvest||$harvest['status']!=='validated'||$stock['status']==='cancelled')continue;$depots[$stock['site_id']]['lots'][]=$stock;foreach(['physical','reserved','available'] as$key)$depots[$stock['site_id']][$key]+=(float)$stock[$key.'_quantity_kg'];}
$depotKg=fn($n)=>number_format((float)$n,3,',',' ').' kg';
$depotTransportStates=['draft'=>'Brouillon','approved'=>'Réservé','in_transit'=>'En transit','received'=>'Réceptionné','cancelled'=>'Annulé'];
?>
<section id="agriExtraDirectory" class="campaign-directory depot-directory" data-depot-directory data-context="<?=e(Auth::currentSiteId()??'all')?>">
<header class="campaign-heading"><div><p class="page-kicker">AGRICULTURE · STOCKAGE</p><h2>Dépôts des fermes</h2><p>Consultez les stocks de chaque ferme et préparez vos expéditions.</p></div><a class="btn-secondary" href="<?=e(base_url('agriculture/transports'))?>">Voir les transports</a></header>
<div class="campaign-list"><div class="campaign-filters depot-filters" role="search" aria-label="Filtrer les dépôts"><label>Recherche<input type="search" data-depot-search placeholder="Nom ou code de la ferme"></label><label>Disponibilité<select data-depot-state><option value="">Tous les dépôts</option><option value="available">Stock disponible</option><option value="reserved">Avec réservations</option><option value="empty">Sans stock physique</option></select></label><button type="button" class="btn-secondary" data-depot-reset>Réinitialiser</button></div></div>

<div class="depot-grid">
<?php foreach($depots as$id=>$depot):$farm=$depot['site'];
$products=array_values(array_unique(array_filter(array_column(array_filter($depot['lots'],fn($s)=>(float)$s['physical_quantity_kg']>0),'product_name'))));
$availablePercent=$depot['physical']>0?max(0,min(100,100*$depot['available']/$depot['physical'])):0;
$reservedPercent=$depot['physical']>0?max(0,min(100-$availablePercent,100*$depot['reserved']/$depot['physical'])):0;
$percentLabel=fn($n)=>number_format($n,1,',',' ').' %';
?>
<article class="depot-card" data-depot-card data-search="<?=e($farm['name'].' '.$farm['code'])?>" data-available="<?=e($depot['available'])?>" data-reserved="<?=e($depot['reserved'])?>" data-physical="<?=e($depot['physical'])?>">
<div class="depot-card-body">
<header class="depot-card-heading"><div class="depot-visual"><?php require view_path('agriculture.depot_illustration');?></div><div><small><?=e($farm['code'])?></small><h3><?=e($farm['name'])?></h3><p><?=e($products?implode(' · ',array_slice($products,0,2)).(count($products)>2?' · +'.(count($products)-2).' produits':''):'Aucun stock')?></p></div></header>
<div class="depot-total"><span>Stock en dépôt</span><strong><?=e($depotKg($depot['physical']))?></strong></div>
<div class="depot-distribution" role="img" aria-label="<?=e($depot['physical']>0?'Répartition du stock : '.$percentLabel($availablePercent).' disponible, '.$percentLabel($reservedPercent).' réservé.':'Aucun stock en dépôt')?>"><span class="is-available" style="width:<?=e($availablePercent)?>%"></span><span class="is-reserved" style="width:<?=e($reservedPercent)?>%"></span></div>
<dl class="depot-balance"><div class="is-available"><dt><span aria-hidden="true"></span>Disponible</dt><dd><?=e($depotKg($depot['available']))?></dd><small><?=e($percentLabel($availablePercent))?></small></div><div class="is-reserved"><dt><span aria-hidden="true"></span>Réservé</dt><dd><?=e($depotKg($depot['reserved']))?></dd><small><?=e($percentLabel($reservedPercent))?></small></div></dl>
<button type="button" class="btn-primary" data-depot-open="<?=e($id)?>" aria-haspopup="dialog"><?=count($depot['lots'])?(count($depot['lots'])===1?'Voir le lot':'Voir les '.count($depot['lots']).' lots'):'Voir le dépôt'?><i class="bi bi-arrow-right" aria-hidden="true"></i></button></div></article>
<template data-depot-detail="<?=e($id)?>"><header class="campaign-drawer-heading"><div><p class="page-kicker">DÉPÔT · <?=e($farm['code'])?></p><h2 id="depotDetailTitle"><?=e($farm['name'])?></h2><small><?=e($depotKg($depot['available']))?> disponibles · <?=e($depotKg($depot['reserved']))?> réservés</small></div><button type="button" class="modal-close" data-depot-close aria-label="Fermer">×</button></header>
<div class="campaign-drawer-body"><div class="depot-lot-filters"><label>Rechercher un lot<input type="search" data-depot-lot-search placeholder="Récolte, produit, variété, campagne…"></label><label>Afficher<select data-depot-lot-state><option value="physical">Avec stock physique</option><option value="all">Tous les lots</option><option value="available">Avec stock disponible</option><option value="empty">Lots épuisés</option></select></label></div>
<div class="depot-lots">
<?php foreach($depot['lots'] as$stock):$h=$depotHarvests[$stock['harvest_id']];$plan=$depotPlans[$h['campaign_plot_id']]??[];$c=$depotCampaigns[$plan['campaign_id']??0]??[];$links=$depotTransports[$stock['id']]??[];$canTransport=(float)$stock['available_quantity_kg']>0&&in_array($stock['status'],['available','reserved'],true)&&empty($h['has_draft_transport'])&&Auth::can('agriculture','create',$farm['id']);?>
<article class="depot-lot" data-depot-lot data-search="<?=e($h['harvest_number'].' '.$stock['product_name'].' '.$stock['variety_name'].' '.($c['name']??'').' '.($plan['plot_name']??''))?>" data-physical="<?=e($stock['physical_quantity_kg'])?>" data-available="<?=e($stock['available_quantity_kg'])?>"><header><strong><?=e($stock['variety_name'])?></strong><span class="campaign-status"><?=(float)$stock['physical_quantity_kg']<=0?'Épuisé':((float)$stock['available_quantity_kg']>0?'Disponible':'Réservé')?></span></header><small><?=e($stock['product_name'].' · '.$h['harvest_number'])?></small><p><?=e(($c['name']??$h['campaign_code']).' · '.($plan['plot_name']??$h['plot_code']))?><br>Récolté le <?=e(date('d/m/Y',strtotime($h['harvested_at'])))?></p>
<dl class="depot-quantities"><div><dt>Physique</dt><dd><?=e($depotKg($stock['physical_quantity_kg']))?></dd></div><div class="is-reserved"><dt>Réservé</dt><dd><?=e($depotKg($stock['reserved_quantity_kg']))?></dd></div><div class="is-available"><dt>Disponible</dt><dd><?=e($depotKg($stock['available_quantity_kg']))?></dd></div></dl>
<?php if($canTransport):?><button type="button" class="btn-primary" data-depot-transport data-depot-stock="<?=e($stock['id'])?>" data-workspace-modal-open="transportModal">Créer un transport</button><?php elseif(!empty($h['has_draft_transport'])):?><p class="depot-lot-note">Un transport en brouillon existe déjà pour ce lot.</p><?php endif;?>
<?php if($links):?><details><summary>Transports associés · <?=count($links)?></summary><?php foreach($links as$t):?><p><strong><?=e($t['document_number']?:$t['transport_number'])?></strong> · <?=e($depotTransportStates[$t['status']]??$t['status'])?><br><?=e($depotKg($t['quantity_kg']))?></p><?php endforeach;?><a href="<?=e(base_url('agriculture/transports'))?>">Consulter les transports</a></details><?php endif;?></article>
<?php endforeach;?></div><p class="campaign-empty-note" data-depot-lot-empty hidden>Aucun lot pour cette sélection. Choisissez « Tous les lots » pour consulter les lots épuisés.</p>
<footer class="campaign-pagination"><span data-depot-lot-count role="status"></span><div><button type="button" class="btn-secondary" data-depot-page="-1">Précédent</button><span data-depot-page-label></span><button type="button" class="btn-secondary" data-depot-page="1">Suivant</button></div></footer></div></template>
<?php endforeach;?></div><p class="plot-empty" data-depot-empty hidden>Aucun dépôt ne correspond à votre sélection.</p><p class="plot-visual-note" data-depot-count role="status"></p>
<dialog class="campaign-drawer depot-detail" data-depot-drawer aria-labelledby="depotDetailTitle"></dialog>
</section>
