<section class="works-page" data-work-directory data-api="<?=e(base_url('agriculture/works/data'))?>" data-create="<?=e(base_url('agriculture/works'))?>" data-context="<?=e(Auth::currentSiteId()??'all')?>">
    <header class="campaign-heading"><div><p class="page-kicker">AGRICULTURE · INTERVENTIONS RÉALISÉES</p><h2>Travaux agricoles</h2><p>Équipe, matériel et coûts par parcelle. Les devises sont suivies séparément.</p></div><div class="work-heading-actions"><button type="button" class="btn-secondary" data-work-refresh>Actualiser</button><?php if(Auth::can('agriculture','update')):?><button type="button" class="btn-primary" data-work-new>+ Enregistrer un travail</button><?php endif;?></div></header>
    <p class="work-context-note" data-work-no-plans hidden>Aucune parcelle de campagne ouverte n’est disponible pour la saisie. <a href="<?=e(base_url('agriculture/planning'))?>">Ouvrir la planification des parcelles</a>.</p>
    <div class="work-page-error app-alert app-alert-error" hidden role="alert"></div>
    <div class="campaign-summary work-summary"><div><span>Interventions réalisées</span><strong data-work-kpi="count">—</strong><small>Les annulations sont exclues</small></div><div><span>Coût total</span><strong data-work-kpi="total">—</strong><small>Main-d’œuvre, matériel et autres coûts</small></div><div><span>Main-d’œuvre</span><strong data-work-kpi="labor">—</strong><small>Jours × tarifs déclarés</small></div><div><span>Matériel</span><strong data-work-kpi="equipment">—</strong><small>Heures × tarifs déclarés</small></div></div>
    <div class="campaign-list"><div class="campaign-filters work-filters" role="search" aria-label="Filtrer les travaux"><label>Recherche<input type="search" data-work-filter="search" placeholder="Travail, responsable, parcelle…"></label><label>Ferme<select data-work-filter="site"></select></label><label>Campagne<select data-work-filter="campaign"></select></label><button type="button" class="btn-secondary work-filter-toggle" data-work-filter-toggle aria-expanded="false" aria-controls="work-extra-filters"><i class="bi bi-sliders" aria-hidden="true"></i> Plus de filtres <span data-work-filter-count hidden></span></button><button type="button" class="btn-secondary" data-work-reset>Réinitialiser</button><div id="work-extra-filters" class="work-extra-filters" hidden><label>Parcelle<select data-work-filter="plot"></select></label><label>Type<select data-work-filter="type"></select></label><label>Du<input type="date" data-work-filter="from"></label><label>Au<input type="date" data-work-filter="to"></label><label>Statut<select data-work-filter="status"><option value="">Tous les statuts</option><option value="completed">Réalisés</option><option value="cancelled">Annulés</option><option value="planned">Planifiés (anciens)</option></select></label></div></div>
    <div class="table-responsive"><table class="enterprise-table work-table" data-datatable="false"><thead><tr><th>Date</th><th>Parcelle / campagne</th><th>Travail</th><th>Responsable</th><th>Coût</th><th>Statut</th><th>Action</th></tr></thead><tbody data-work-rows></tbody></table></div><footer class="campaign-pagination"><span data-work-count role="status"></span><div><button type="button" class="btn-secondary" data-work-page="-1">Précédent</button><span data-work-page-label></span><button type="button" class="btn-secondary" data-work-page="1">Suivant</button></div></footer></div>
    <details class="work-campaign-costs"><summary>Coûts agricoles par campagne · travaux et intrants</summary><p>Travaux réalisés cumulés sur toute la campagne. Les intrants historiques sont exprimés en USD. Les travaux restent présentés par devise. Ce suivi représente des coûts déclarés, pas des paiements.</p><div data-work-campaign-costs></div></details>
    <dialog class="work-editor" data-work-editor aria-labelledby="workEditorTitle">
        <header class="work-dialog-heading"><div><p class="page-kicker">DÉCLARATION D’INTERVENTION</p><h2 id="workEditorTitle">Enregistrer un travail</h2></div><button type="button" class="modal-close" data-work-close aria-label="Fermer">×</button></header>
        <form data-work-form data-ajax="false" method="post" action="<?=e(base_url('agriculture/works'))?>">
            <?=csrf_field()?><input type="hidden" name="_return_to" value="agriculture/works"><input type="hidden" name="submission_key"><input type="hidden" name="revision">
            <div class="work-editor-body"><div class="app-alert app-alert-error" data-work-errors role="alert" hidden></div>
                <fieldset><legend>1. Localiser l’intervention</legend><div class="work-form-grid"><label>Ferme *<select data-work-site required></select></label><label>Campagne *<select data-work-campaign required></select></label><label class="wide">Parcelle planifiée *<select name="campaign_plot_id" required></select></label></div><p class="work-context-note" data-work-context></p></fieldset>
                <fieldset><legend>2. Décrire le travail réalisé</legend><div class="work-form-grid"><label>Type *<select name="work_type" required><?php foreach($workData['types'] as$type):?><option value="<?=e($type)?>"><?=e($type)?></option><?php endforeach;?></select></label><label data-work-custom hidden>Précisez le travail *<input name="custom_type" maxlength="85"></label><label>Date et heure *<input type="datetime-local" name="worked_at" step="60" required aria-describedby="work-date-help work-date-error"><small id="work-date-help" data-work-date-help></small><small id="work-date-error" class="work-field-error" data-work-date-error role="alert" hidden></small></label><label>Responsable du travail *<input name="responsible_name" maxlength="160" required placeholder="Chef d’équipe ou responsable terrain"></label><label>Devise des coûts *<select name="currency" required><option value="USD">USD — Dollar américain</option><option value="CDF">CDF — Franc congolais</option></select></label><label>Taux de change *<input name="exchange_rate" type="number" min="0.000001" max="999999999" step="0.000001" value="1" required readonly aria-describedby="work-rate-help"><small id="work-rate-help" data-work-rate-help>USD : taux fixe de 1.</small></label><label class="wide">Description<textarea name="description" maxlength="2000" rows="2" placeholder="Nature de l’intervention, zone traitée, observations…"></textarea></label></div></fieldset>
                <fieldset><legend>3. Ressources et coûts</legend><p class="work-context-note">Saisissez chaque tarif dans la devise choisie. Les tarifs historiques du répertoire sont en USD. Saisissez les tarifs en CDF si cette devise est sélectionnée.</p>
                    <div class="work-resource-heading"><h3>Main-d’œuvre</h3><button type="button" class="btn-secondary" data-work-add="labor">+ Travailleur</button></div><div data-work-lines="labor"></div><p class="work-context-note" data-work-no-labor>Aucun travailleur ajouté.</p>
                    <div class="work-resource-heading"><h3>Matériel</h3><button type="button" class="btn-secondary" data-work-add="equipment">+ Matériel</button></div><div data-work-lines="equipment"></div><p class="work-context-note" data-work-no-equipment>Aucun matériel ajouté.</p>
                    <div class="work-form-grid"><label>Autres coûts<input name="other_cost" type="number" min="0" max="9999999999" step="0.0001" value="0" required></label><label>Justification des autres coûts<textarea name="other_cost_reason" maxlength="500" rows="2" placeholder="Obligatoire si le montant est supérieur à zéro"></textarea></label></div>
                    <div class="work-total" aria-live="polite"><span>Total de l’intervention</span><strong data-work-total>0,00 USD</strong></div><p class="work-context-note" data-work-conversion aria-live="polite"></p>
                </fieldset>
                <label class="work-correction-reason" hidden>Motif de correction *<textarea name="reason" maxlength="500" rows="2"></textarea></label>
            </div><footer class="work-dialog-footer"><button type="button" class="btn-secondary" data-work-close>Retour</button><button type="submit" class="btn-primary" data-work-submit>Vérifier et enregistrer</button></footer>
        </form>
    </dialog>
    <dialog class="campaign-drawer work-detail" data-work-detail aria-labelledby="workDetailTitle"></dialog>
    <script type="application/json" data-work-data><?=json_encode($workData,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)?></script>
</section>
