ALTER TABLE waste_stocks ADD COLUMN quality_grade VARCHAR(50) NOT NULL DEFAULT 'standard' AFTER quantity_kg,ADD COLUMN average_unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0 AFTER quality_grade,ADD COLUMN available_at DATETIME NULL AFTER average_unit_cost,ADD COLUMN storage_status ENUM('available','buffer','reserved','in_transit','sold','consumed','inactive') NOT NULL DEFAULT 'available' AFTER available_at;
UPDATE waste_stocks SET available_at=COALESCE(available_at,created_at),storage_status=IF(quantity_kg>0,'available','inactive');
CREATE TABLE waste_stock_movements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,waste_stock_id INT UNSIGNED NOT NULL,movement_type ENUM('production_in','buffer','sale','transfer_out','transfer_in','processing','pellet_consumption','reversal') NOT NULL,quantity_kg DECIMAL(12,3) NOT NULL,stock_before_kg DECIMAL(12,3) NOT NULL,stock_after_kg DECIMAL(12,3) NOT NULL,reference_type VARCHAR(80) NOT NULL,reference_id BIGINT UNSIGNED NOT NULL,movement_at DATETIME NOT NULL,created_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_wsm_effect(waste_stock_id,movement_type,reference_type,reference_id),KEY idx_wsm_stock_date(waste_stock_id,movement_at),CONSTRAINT fk_wsm_stock FOREIGN KEY(waste_stock_id) REFERENCES waste_stocks(id),CONSTRAINT fk_wsm_user FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT INTO waste_stock_movements(waste_stock_id,movement_type,quantity_kg,stock_before_kg,stock_after_kg,reference_type,reference_id,movement_at,created_by) SELECT ws.id,'production_in',ws.quantity_kg,0,ws.quantity_kg,'production_batches',COALESCE(ws.production_batch_id,0),ws.created_at,pb.validated_by FROM waste_stocks ws LEFT JOIN production_batches pb ON pb.id=ws.production_batch_id WHERE NOT EXISTS(SELECT 1 FROM waste_stock_movements m WHERE m.waste_stock_id=ws.id);

CREATE TABLE waste_transfers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,transfer_number VARCHAR(100) UNIQUE NOT NULL,source_site_id INT UNSIGNED NOT NULL,destination_site_id INT UNSIGNED NOT NULL,status ENUM('draft','in_transit','received','cancelled') DEFAULT 'draft',created_by INT UNSIGNED NOT NULL,approved_by INT UNSIGNED NULL,shipped_at DATETIME NULL,received_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,CONSTRAINT fk_wt_source FOREIGN KEY(source_site_id) REFERENCES sites(id),CONSTRAINT fk_wt_dest FOREIGN KEY(destination_site_id) REFERENCES sites(id),CONSTRAINT fk_wt_creator FOREIGN KEY(created_by) REFERENCES users(id),CONSTRAINT fk_wt_approver FOREIGN KEY(approved_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE waste_transfer_lines(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,transfer_id BIGINT UNSIGNED NOT NULL,source_waste_stock_id INT UNSIGNED NOT NULL,destination_waste_stock_id INT UNSIGNED NULL,quantity_kg DECIMAL(12,3) NOT NULL,CONSTRAINT fk_wtl_transfer FOREIGN KEY(transfer_id) REFERENCES waste_transfers(id),CONSTRAINT fk_wtl_source FOREIGN KEY(source_waste_stock_id) REFERENCES waste_stocks(id),CONSTRAINT fk_wtl_dest FOREIGN KEY(destination_waste_stock_id) REFERENCES waste_stocks(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE waste_sales(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,waste_stock_id INT UNSIGNED NOT NULL,sale_number VARCHAR(100) UNIQUE NOT NULL,customer_name VARCHAR(180) NOT NULL,quantity_kg DECIMAL(12,3) NOT NULL,unit_price DECIMAL(14,4) NOT NULL,sold_at DATETIME NOT NULL,status ENUM('validated','cancelled') NOT NULL DEFAULT 'validated',created_by INT UNSIGNED NOT NULL,CONSTRAINT fk_ws_stock FOREIGN KEY(waste_stock_id) REFERENCES waste_stocks(id),CONSTRAINT fk_ws_user FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pellet_additives(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) UNIQUE NOT NULL,name VARCHAR(150) NOT NULL,unit VARCHAR(20) DEFAULT 'kg',status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
INSERT IGNORE INTO pellet_additives(code,name) VALUES('LIANT','Liant'),('PREMIX','Prémix minéral'),('MELASSE','Mélasse');
CREATE TABLE pellet_additive_stocks(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,additive_id INT UNSIGNED NOT NULL,quantity_kg DECIMAL(12,3) NOT NULL DEFAULT 0,average_unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,UNIQUE KEY uq_pas_site_additive(site_id,additive_id),CONSTRAINT fk_pas_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_pas_additive FOREIGN KEY(additive_id) REFERENCES pellet_additives(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_additive_purchases(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,additive_id INT UNSIGNED NOT NULL,purchase_number VARCHAR(100) UNIQUE NOT NULL,quantity_kg DECIMAL(12,3) NOT NULL,unit_cost DECIMAL(14,4) NOT NULL,status ENUM('draft','approved','received','cancelled') DEFAULT 'draft',created_by INT UNSIGNED NOT NULL,approved_by INT UNSIGNED NULL,received_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,received_at DATETIME NULL,CONSTRAINT fk_pap_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_pap_additive FOREIGN KEY(additive_id) REFERENCES pellet_additives(id),CONSTRAINT fk_pap_creator FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_additive_movements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,stock_id BIGINT UNSIGNED NOT NULL,movement_type ENUM('purchase_in','production_out','reversal') NOT NULL,quantity_kg DECIMAL(12,3) NOT NULL,stock_before_kg DECIMAL(12,3) NOT NULL,stock_after_kg DECIMAL(12,3) NOT NULL,reference_type VARCHAR(80) NOT NULL,reference_id BIGINT UNSIGNED NOT NULL,created_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_pam_effect(stock_id,movement_type,reference_type,reference_id),CONSTRAINT fk_pam_stock FOREIGN KEY(stock_id) REFERENCES pellet_additive_stocks(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pellet_recipes(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) UNIQUE NOT NULL,name VARCHAR(150) NOT NULL,status ENUM('active','inactive') DEFAULT 'active',created_by INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_recipe_versions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,recipe_id INT UNSIGNED NOT NULL,version_number INT UNSIGNED NOT NULL,status ENUM('draft','active','retired') DEFAULT 'draft',effective_from DATE NOT NULL,notes TEXT NULL,created_by INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_prv_recipe_version(recipe_id,version_number),CONSTRAINT fk_prv_recipe FOREIGN KEY(recipe_id) REFERENCES pellet_recipes(id),CONSTRAINT fk_prv_creator FOREIGN KEY(created_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_recipe_wastes(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,recipe_version_id BIGINT UNSIGNED NOT NULL,waste_type_id INT UNSIGNED NOT NULL,percentage DECIMAL(8,3) NOT NULL,UNIQUE KEY uq_prw_type(recipe_version_id,waste_type_id),CONSTRAINT fk_prw_version FOREIGN KEY(recipe_version_id) REFERENCES pellet_recipe_versions(id),CONSTRAINT fk_prw_type FOREIGN KEY(waste_type_id) REFERENCES waste_types(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_recipe_additives(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,recipe_version_id BIGINT UNSIGNED NOT NULL,additive_id INT UNSIGNED NOT NULL,percentage DECIMAL(8,3) NOT NULL,UNIQUE KEY uq_pra_additive(recipe_version_id,additive_id),CONSTRAINT fk_pra_version FOREIGN KEY(recipe_version_id) REFERENCES pellet_recipe_versions(id),CONSTRAINT fk_pra_additive FOREIGN KEY(additive_id) REFERENCES pellet_additives(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE pellet_orders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,recipe_version_id BIGINT UNSIGNED NOT NULL,order_number VARCHAR(100) UNIQUE NOT NULL,theoretical_input_kg DECIMAL(12,3) NOT NULL,actual_input_kg DECIMAL(12,3) NOT NULL DEFAULT 0,output_quantity_kg DECIMAL(12,3) NOT NULL DEFAULT 0,loss_quantity_kg DECIMAL(12,3) NOT NULL DEFAULT 0,yield_percent DECIMAL(8,3) NOT NULL DEFAULT 0,cost_total DECIMAL(16,4) NOT NULL DEFAULT 0,cost_per_kg DECIMAL(14,4) NOT NULL DEFAULT 0,status ENUM('draft','in_progress','results_submitted','validated','cancelled') DEFAULT 'draft',started_at DATETIME NULL,ended_at DATETIME NULL,created_by INT UNSIGNED NOT NULL,validated_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,CONSTRAINT fk_po_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_po_recipe FOREIGN KEY(recipe_version_id) REFERENCES pellet_recipe_versions(id),CONSTRAINT fk_po_creator FOREIGN KEY(created_by) REFERENCES users(id),CONSTRAINT fk_po_validator FOREIGN KEY(validated_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_order_waste_consumptions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,pellet_order_id BIGINT UNSIGNED NOT NULL,waste_stock_id INT UNSIGNED NOT NULL,theoretical_quantity_kg DECIMAL(12,3) NOT NULL,actual_quantity_kg DECIMAL(12,3) NOT NULL DEFAULT 0,unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,UNIQUE KEY uq_powc_order_stock(pellet_order_id,waste_stock_id),CONSTRAINT fk_powc_order FOREIGN KEY(pellet_order_id) REFERENCES pellet_orders(id),CONSTRAINT fk_powc_stock FOREIGN KEY(waste_stock_id) REFERENCES waste_stocks(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_order_additive_consumptions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,pellet_order_id BIGINT UNSIGNED NOT NULL,additive_stock_id BIGINT UNSIGNED NOT NULL,theoretical_quantity_kg DECIMAL(12,3) NOT NULL,actual_quantity_kg DECIMAL(12,3) NOT NULL DEFAULT 0,unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,UNIQUE KEY uq_poac_order_stock(pellet_order_id,additive_stock_id),CONSTRAINT fk_poac_order FOREIGN KEY(pellet_order_id) REFERENCES pellet_orders(id),CONSTRAINT fk_poac_stock FOREIGN KEY(additive_stock_id) REFERENCES pellet_additive_stocks(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_stocks(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,pellet_order_id BIGINT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,quantity_kg DECIMAL(12,3) NOT NULL,status ENUM('active','depleted','cancelled') DEFAULT 'active',UNIQUE KEY uq_ps_order(pellet_order_id),CONSTRAINT fk_ps_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_ps_order FOREIGN KEY(pellet_order_id) REFERENCES pellet_orders(id),CONSTRAINT fk_ps_product FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE pellet_packaging(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,pellet_order_id BIGINT UNSIGNED NOT NULL,pellet_stock_id BIGINT UNSIGNED NOT NULL,packaging_item_id INT UNSIGNED NOT NULL,finished_stock_id INT UNSIGNED NOT NULL,bags_count INT UNSIGNED NOT NULL,total_weight_kg DECIMAL(12,3) NOT NULL,packaged_at DATETIME NOT NULL,created_by INT UNSIGNED NOT NULL,CONSTRAINT fk_pp_order FOREIGN KEY(pellet_order_id) REFERENCES pellet_orders(id),CONSTRAINT fk_pp_stock FOREIGN KEY(pellet_stock_id) REFERENCES pellet_stocks(id),CONSTRAINT fk_pp_item FOREIGN KEY(packaging_item_id) REFERENCES empty_packaging_items(id),CONSTRAINT fk_pp_finished FOREIGN KEY(finished_stock_id) REFERENCES finished_stocks(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO permissions(component,action,description) VALUES('pelletization','read','Consulter pelletisation'),('pelletization','create','Créer pelletisation'),('pelletization','validate','Valider pelletisation'),('pelletization','update','Modifier pelletisation'),('pelletization','delete','Supprimer pelletisation'),('pelletization','administer','Administrer pelletisation');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='pelletization' WHERE r.slug='administrateur';
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='pelletization' AND p.action IN('read','create','update') WHERE r.slug IN('agent-production','operateur-production','gestionnaire-stock');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='pelletization' AND p.action IN('read','validate') WHERE r.slug IN('direction','directeur-general','directeur-site','responsable-site');

DELIMITER $$
CREATE TRIGGER trg_pellet_recipe_wastes_used_update BEFORE UPDATE ON pellet_recipe_wastes FOR EACH ROW BEGIN IF EXISTS(SELECT 1 FROM pellet_orders WHERE recipe_version_id=OLD.recipe_version_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Recette utilisée: créez une nouvelle version'; END IF; END$$
CREATE TRIGGER trg_pellet_recipe_wastes_used_delete BEFORE DELETE ON pellet_recipe_wastes FOR EACH ROW BEGIN IF EXISTS(SELECT 1 FROM pellet_orders WHERE recipe_version_id=OLD.recipe_version_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Recette utilisée: créez une nouvelle version'; END IF; END$$
CREATE TRIGGER trg_pellet_recipe_additives_used_update BEFORE UPDATE ON pellet_recipe_additives FOR EACH ROW BEGIN IF EXISTS(SELECT 1 FROM pellet_orders WHERE recipe_version_id=OLD.recipe_version_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Recette utilisée: créez une nouvelle version'; END IF; END$$
CREATE TRIGGER trg_pellet_recipe_additives_used_delete BEFORE DELETE ON pellet_recipe_additives FOR EACH ROW BEGIN IF EXISTS(SELECT 1 FROM pellet_orders WHERE recipe_version_id=OLD.recipe_version_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Recette utilisée: créez une nouvelle version'; END IF; END$$
DELIMITER ;
