CREATE TABLE agricultural_seasons (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,start_month TINYINT UNSIGNED NULL,end_month TINYINT UNSIGNED NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_campaigns (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,season_id INT UNSIGNED NOT NULL,code VARCHAR(80) NOT NULL,name VARCHAR(160) NOT NULL,start_date DATE NOT NULL,end_date DATE NOT NULL,status ENUM('draft','planned','in_progress','harvesting','closed','cancelled') NOT NULL DEFAULT 'draft',created_by INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,UNIQUE KEY uq_ag_campaign_site_code(site_id,code),KEY idx_ag_campaign_site_status(site_id,status),CONSTRAINT fk_ag_campaign_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_ag_campaign_season FOREIGN KEY(season_id) REFERENCES agricultural_seasons(id),CONSTRAINT fk_ag_campaign_creator FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_varieties (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id INT UNSIGNED NOT NULL,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL,cycle_days INT UNSIGNED NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,CONSTRAINT fk_ag_variety_product FOREIGN KEY(product_id) REFERENCES products(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_plots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,code VARCHAR(60) NOT NULL,name VARCHAR(150) NOT NULL,total_area_ha DECIMAL(12,3) NOT NULL,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,UNIQUE KEY uq_ag_plot_site_code(site_id,code),CONSTRAINT fk_ag_plot_site FOREIGN KEY(site_id) REFERENCES sites(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_campaign_plots (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,campaign_id BIGINT UNSIGNED NOT NULL,plot_id BIGINT UNSIGNED NOT NULL,variety_id INT UNSIGNED NOT NULL,planned_area_ha DECIMAL(12,3) NOT NULL,actual_area_ha DECIMAL(12,3) NOT NULL DEFAULT 0,target_tons_per_ha DECIMAL(10,3) NOT NULL,status ENUM('planned','in_progress','harvested','closed') DEFAULT 'planned',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_ag_campaign_plot(campaign_id,plot_id),CONSTRAINT fk_ag_cp_campaign FOREIGN KEY(campaign_id) REFERENCES agricultural_campaigns(id),CONSTRAINT fk_ag_cp_plot FOREIGN KEY(plot_id) REFERENCES agricultural_plots(id),CONSTRAINT fk_ag_cp_variety FOREIGN KEY(variety_id) REFERENCES agricultural_varieties(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_inputs (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(150) NOT NULL,input_type ENUM('seed','fertilizer','pesticide') NOT NULL,unit VARCHAR(20) NOT NULL DEFAULT 'kg',status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_input_allocations (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,campaign_plot_id BIGINT UNSIGNED NOT NULL,input_id INT UNSIGNED NOT NULL,planned_quantity DECIMAL(14,3) NOT NULL DEFAULT 0,actual_quantity DECIMAL(14,3) NOT NULL DEFAULT 0,unit_cost DECIMAL(14,4) NOT NULL DEFAULT 0,applied_at DATETIME NULL,created_by INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,CONSTRAINT fk_ag_ia_cp FOREIGN KEY(campaign_plot_id) REFERENCES agricultural_campaign_plots(id),CONSTRAINT fk_ag_ia_input FOREIGN KEY(input_id) REFERENCES agricultural_inputs(id),CONSTRAINT fk_ag_ia_user FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_workers (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,worker_number VARCHAR(60) NOT NULL,name VARCHAR(160) NOT NULL,worker_type ENUM('permanent','daily') NOT NULL,daily_rate DECIMAL(14,4) NOT NULL DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,UNIQUE KEY uq_ag_worker_site_number(site_id,worker_number),CONSTRAINT fk_ag_worker_site FOREIGN KEY(site_id) REFERENCES sites(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_equipment (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,code VARCHAR(60) NOT NULL,name VARCHAR(150) NOT NULL,hourly_cost DECIMAL(14,4) NOT NULL DEFAULT 0,status ENUM('active','maintenance','inactive') DEFAULT 'active',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,UNIQUE KEY uq_ag_equipment_site_code(site_id,code),CONSTRAINT fk_ag_equipment_site FOREIGN KEY(site_id) REFERENCES sites(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_works (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,campaign_plot_id BIGINT UNSIGNED NOT NULL,work_type VARCHAR(100) NOT NULL,description TEXT NULL,worked_at DATETIME NOT NULL,status ENUM('planned','completed','cancelled') DEFAULT 'planned',other_cost DECIMAL(14,4) NOT NULL DEFAULT 0,created_by INT UNSIGNED NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,CONSTRAINT fk_ag_work_cp FOREIGN KEY(campaign_plot_id) REFERENCES agricultural_campaign_plots(id),CONSTRAINT fk_ag_work_user FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_work_labor (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,work_id BIGINT UNSIGNED NOT NULL,worker_id BIGINT UNSIGNED NOT NULL,days_worked DECIMAL(8,2) NOT NULL,cost DECIMAL(14,4) NOT NULL,CONSTRAINT fk_ag_wl_work FOREIGN KEY(work_id) REFERENCES agricultural_works(id),CONSTRAINT fk_ag_wl_worker FOREIGN KEY(worker_id) REFERENCES agricultural_workers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_work_equipment (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,work_id BIGINT UNSIGNED NOT NULL,equipment_id BIGINT UNSIGNED NOT NULL,hours_used DECIMAL(10,2) NOT NULL,cost DECIMAL(14,4) NOT NULL,CONSTRAINT fk_ag_we_work FOREIGN KEY(work_id) REFERENCES agricultural_works(id),CONSTRAINT fk_ag_we_equipment FOREIGN KEY(equipment_id) REFERENCES agricultural_equipment(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE agricultural_harvests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,campaign_plot_id BIGINT UNSIGNED NOT NULL,harvest_number VARCHAR(100) NOT NULL UNIQUE,harvested_at DATETIME NOT NULL,gross_weight_kg DECIMAL(14,3) NOT NULL,tare_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,drying_loss_kg DECIMAL(14,3) NOT NULL DEFAULT 0,net_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,moisture_before DECIMAL(7,3) NULL,moisture_after DECIMAL(7,3) NULL,drying_started_at DATETIME NULL,drying_ended_at DATETIME NULL,yield_tons_per_ha DECIMAL(12,4) NOT NULL DEFAULT 0,status ENUM('draft','drying','submitted','validated','cancelled') DEFAULT 'draft',created_by INT UNSIGNED NOT NULL,validated_by INT UNSIGNED NULL,validated_at DATETIME NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,deleted_at TIMESTAMP NULL,UNIQUE KEY uq_ag_harvest_cp(campaign_plot_id),KEY idx_ag_harvest_site_status(site_id,status),CONSTRAINT fk_ag_harvest_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_ag_harvest_cp FOREIGN KEY(campaign_plot_id) REFERENCES agricultural_campaign_plots(id),CONSTRAINT fk_ag_harvest_creator FOREIGN KEY(created_by) REFERENCES users(id),CONSTRAINT fk_ag_harvest_validator FOREIGN KEY(validated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_stocks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,site_id INT UNSIGNED NOT NULL,harvest_id BIGINT UNSIGNED NOT NULL,product_id INT UNSIGNED NOT NULL,variety_id INT UNSIGNED NOT NULL,physical_quantity_kg DECIMAL(14,3) NOT NULL,reserved_quantity_kg DECIMAL(14,3) NOT NULL DEFAULT 0,status ENUM('available','reserved','in_transit','depleted','cancelled') DEFAULT 'available',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_ag_stock_harvest(harvest_id),KEY idx_ag_stock_site_product(site_id,product_id,status),CONSTRAINT fk_ag_stock_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_ag_stock_harvest FOREIGN KEY(harvest_id) REFERENCES agricultural_harvests(id),CONSTRAINT fk_ag_stock_product FOREIGN KEY(product_id) REFERENCES products(id),CONSTRAINT fk_ag_stock_variety FOREIGN KEY(variety_id) REFERENCES agricultural_varieties(id),CONSTRAINT chk_ag_stock_nonnegative CHECK(physical_quantity_kg>=0 AND reserved_quantity_kg>=0 AND reserved_quantity_kg<=physical_quantity_kg)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_stock_movements (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,stock_id BIGINT UNSIGNED NOT NULL,movement_type ENUM('harvest_in','reserve','release','transport_out','reversal') NOT NULL,quantity_kg DECIMAL(14,3) NOT NULL,physical_before_kg DECIMAL(14,3) NOT NULL,physical_after_kg DECIMAL(14,3) NOT NULL,reserved_before_kg DECIMAL(14,3) NOT NULL,reserved_after_kg DECIMAL(14,3) NOT NULL,reference_type VARCHAR(80) NOT NULL,reference_id BIGINT UNSIGNED NOT NULL,movement_at DATETIME NOT NULL,created_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_ag_stock_effect(stock_id,movement_type,reference_type,reference_id),CONSTRAINT fk_ag_sm_stock FOREIGN KEY(stock_id) REFERENCES agricultural_stocks(id),CONSTRAINT fk_ag_sm_user FOREIGN KEY(created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE agricultural_transports (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,stock_id BIGINT UNSIGNED NOT NULL,source_site_id INT UNSIGNED NOT NULL,destination_site_id INT UNSIGNED NOT NULL,transport_number VARCHAR(100) NOT NULL UNIQUE,quantity_kg DECIMAL(14,3) NOT NULL,status ENUM('draft','approved','in_transit','received','cancelled') DEFAULT 'draft',truck_plate VARCHAR(40) NULL,driver_name VARCHAR(150) NULL,route_description VARCHAR(255) NULL,created_by INT UNSIGNED NOT NULL,approved_by INT UNSIGNED NULL,dispatched_by INT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,dispatched_at DATETIME NULL,received_at DATETIME NULL,deleted_at TIMESTAMP NULL,UNIQUE KEY uq_ag_transport_stock(stock_id),CONSTRAINT fk_ag_transport_stock FOREIGN KEY(stock_id) REFERENCES agricultural_stocks(id),CONSTRAINT fk_ag_transport_source FOREIGN KEY(source_site_id) REFERENCES sites(id),CONSTRAINT fk_ag_transport_destination FOREIGN KEY(destination_site_id) REFERENCES sites(id),CONSTRAINT fk_ag_transport_creator FOREIGN KEY(created_by) REFERENCES users(id),CONSTRAINT fk_ag_transport_approver FOREIGN KEY(approved_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO agricultural_seasons(code,name,start_month,end_month) VALUES('SAISON-A','Saison A',9,1),('SAISON-B','Saison B',2,6);
INSERT IGNORE INTO agricultural_inputs(code,name,input_type,unit) VALUES('SEM-MAIS','Semences de maïs','seed','kg'),('ENG-NPK','Engrais NPK','fertilizer','kg'),('PEST-GEN','Pesticide général','pesticide','litre');
INSERT IGNORE INTO agricultural_varieties(product_id,code,name) SELECT id,'MAIS-LOCAL','Maïs local' FROM products WHERE code='MAIS-BRUT';
INSERT IGNORE INTO permissions(component,action,description) VALUES('agriculture','read','Consulter fermes'),('agriculture','create','Créer opérations agricoles'),('agriculture','validate','Valider récoltes et transports'),('agriculture','update','Modifier opérations agricoles'),('agriculture','delete','Annuler opérations agricoles'),('agriculture','administer','Administrer référentiels agricoles');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='agriculture' WHERE r.slug IN('administrateur','administrateur-systeme');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='agriculture' AND p.action IN('read','create','update') WHERE r.slug IN('responsable-site','directeur-site','operateur-saisie','gestionnaire-stock');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='agriculture' AND p.action IN('read','validate') WHERE r.slug IN('direction','directeur-general','directeur-site');
