CREATE TABLE IF NOT EXISTS cancellation_policies(entity_type VARCHAR(80) PRIMARY KEY,label VARCHAR(150) NOT NULL,component VARCHAR(80) NOT NULL,allowed_statuses VARCHAR(500) NOT NULL,requires_approval_after_validation TINYINT(1) NOT NULL DEFAULT 1,authorized_action VARCHAR(30) NOT NULL DEFAULT 'read',stock_effects TEXT NULL,blocking_dependencies TEXT NULL,document_types VARCHAR(255) NULL,status ENUM('active','inactive') NOT NULL DEFAULT 'active',updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cancellation_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,request_number VARCHAR(100) NOT NULL UNIQUE,entity_type VARCHAR(80) NOT NULL,entity_id BIGINT UNSIGNED NOT NULL,site_id INT UNSIGNED NOT NULL,original_status VARCHAR(50) NOT NULL,reason VARCHAR(1000) NOT NULL,status ENUM('pending_approval','approved','rejected','completed') NOT NULL,requested_by INT UNSIGNED NOT NULL,requested_at DATETIME NOT NULL,approved_by INT UNSIGNED NULL,approved_at DATETIME NULL,rejected_by INT UNSIGNED NULL,rejected_at DATETIME NULL,rejection_reason VARCHAR(1000) NULL,completed_at DATETIME NULL,KEY idx_cancel_request_scope(site_id,status,requested_at),KEY idx_cancel_request_entity(entity_type,entity_id),CONSTRAINT fk_cancel_request_site FOREIGN KEY(site_id) REFERENCES sites(id),CONSTRAINT fk_cancel_request_user FOREIGN KEY(requested_by) REFERENCES users(id),CONSTRAINT fk_cancel_request_approver FOREIGN KEY(approved_by) REFERENCES users(id),CONSTRAINT fk_cancel_request_rejecter FOREIGN KEY(rejected_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cancellation_reversals(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,request_id BIGINT UNSIGNED NOT NULL UNIQUE,entity_type VARCHAR(80) NOT NULL,entity_id BIGINT UNSIGNED NOT NULL,original_status VARCHAR(50) NOT NULL,reversal_number VARCHAR(100) NOT NULL UNIQUE,executed_by INT UNSIGNED NOT NULL,executed_at DATETIME NOT NULL,UNIQUE KEY uq_cancel_reversal_entity(entity_type,entity_id),CONSTRAINT fk_cancel_reversal_request FOREIGN KEY(request_id) REFERENCES cancellation_requests(id),CONSTRAINT fk_cancel_reversal_user FOREIGN KEY(executed_by) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cancellation_stock_effects(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,reversal_id BIGINT UNSIGNED NOT NULL,stock_table VARCHAR(80) NOT NULL,stock_id BIGINT UNSIGNED NOT NULL,quantity_field VARCHAR(80) NOT NULL,quantity_delta DECIMAL(16,3) NOT NULL,quantity_before DECIMAL(16,3) NOT NULL,quantity_after DECIMAL(16,3) NOT NULL,original_movement_table VARCHAR(80) NULL,original_movement_id BIGINT UNSIGNED NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,KEY idx_cancel_effect_stock(stock_table,stock_id),CONSTRAINT fk_cancel_effect_reversal FOREIGN KEY(reversal_id) REFERENCES cancellation_reversals(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS cancellation_events(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,request_id BIGINT UNSIGNED NOT NULL,event_type ENUM('requested','approved','rejected','executed','blocked') NOT NULL,actor_id INT UNSIGNED NULL,details TEXT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_cancel_event_request FOREIGN KEY(request_id) REFERENCES cancellation_requests(id),CONSTRAINT fk_cancel_event_actor FOREIGN KEY(actor_id) REFERENCES users(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='waste_sales') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='waste_sales' AND column_name='status'),"ALTER TABLE waste_sales ADD COLUMN status ENUM('validated','cancelled') NOT NULL DEFAULT 'validated' AFTER sold_at",'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='empty_packaging_receipts') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='empty_packaging_receipts' AND column_name='status'),"ALTER TABLE empty_packaging_receipts ADD COLUMN status ENUM('received','cancelled') NOT NULL DEFAULT 'received' AFTER received_at",'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='fuel_receipts') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='fuel_receipts' AND column_name='status'),"ALTER TABLE fuel_receipts ADD COLUMN status ENUM('received','cancelled') NOT NULL DEFAULT 'received' AFTER received_at",'SELECT 1'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
INSERT IGNORE INTO cancellation_policies(entity_type,label,component,allowed_statuses,stock_effects,blocking_dependencies,document_types) VALUES
('weighing','Pesée et BRS','weighings','pending,validated,rejected','Retrait du stock silo si BRS validé','BSS ou alimentation machine liée','BRS'),
('brs','Bon de réception silo','silos','validated','Retrait du stock silo','BSS ou alimentation machine liée','BRS'),
('bss','Bon de sortie silo','machine-feeds','pending,validated','Réintégration au silo','Lot de production non annulé','BSS'),
('transfer','Transfert inter-sites','transfers','draft,submitted,approved,reserved','Libération des réservations','Toute expédition ou réception; utiliser le retour complet','BTR,BTI,BR,BS'),
('production','Production ROOF','production','pending,in_progress,results_submitted,pending_additional_approval,validated','Retrait farine/déchets et réintégration matière','Conditionnement ou consommation des sorties','OF'),
('packaging','Conditionnement','packaging','pending,validated','Retrait stock fini, restitution vrac et sacs','Distribution, réservation ou transfert du stock fini',NULL),
('distribution','Distribution','distributions','pending,validated','Réintégration du stock fini','Aucune dépendance aval','BS,BL'),
('waste_sale','Vente de déchets','waste','validated','Réintégration du lot de déchets','Aucune dépendance aval',NULL),
('waste_transfer','Transfert de déchets','pelletization','draft','Aucun effet avant expédition','Expédition ou réception; utiliser un retour BTI','BTI'),
('pelletization','Pelletisation','pelletization','draft,in_progress,results_submitted,validated','Retrait pellets, restitution déchets et additifs','Conditionnement ou transfert des pellets','OF'),
('empty_packaging_receipt','Réception emballages','empty-packaging','received','Retrait des emballages reçus','Tout mouvement sortant postérieur','BRA'),
('fuel_receipt','Réception carburant','fuel-logistics','received','Retrait du carburant reçu','Toute distribution postérieure','BRA'),
('butchery_receipt','Réception boucherie','butchery','sanitary_pending,accepted,rejected','Retrait du lot matière accepté','Transformation, vente ou réservation du lot','BRA,BR');
INSERT IGNORE INTO permissions(component,action,description) VALUES('cancellations','read','Consulter annulations'),('cancellations','create','Demander une annulation'),('cancellations','validate','Approuver une annulation'),('cancellations','update','Exécuter une correction'),('cancellations','delete','Rejeter une demande'),('cancellations','administer','Administrer les politiques');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='cancellations' WHERE r.slug IN('administrateur','administrateur-systeme');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='cancellations' AND p.action IN('read','create') WHERE r.slug IN('directeur-site','responsable-site','gestionnaire-stock');
INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.component='cancellations' AND p.action IN('read','validate','update') WHERE r.slug IN('direction','directeur-general','directeur-financier','auditeur');
