<?php
$labels=['draft'=>'Brouillon','submitted'=>'Soumis','pending_approval'=>'À approuver','pending_validation'=>'À valider','approved'=>'Approuvé','validated'=>'Validé','in_progress'=>'En cours','received'=>'Reçu','rejected'=>'Refusé','cancelled'=>'Annulé','closed'=>'Clôturé'];
$types=[];foreach($documents as $d)$types[(string)$d['document_type_id']]=$d['display_code'].' · '.$d['type_name'];asort($types);
$typeOptions=[];foreach($types as $id=>$label)$typeOptions[]= [(string)$id,$label];
$groups=['all'=>['Documents du périmètre',$documents],'pending'=>['En attente de validation',array_values(array_filter($documents,static function($d){return in_array($d['status'],['submitted','pending_approval','pending_validation'],true);}))],'rejected'=>['Documents refusés',array_values(array_filter($documents,static function($d){return $d['status']==='rejected';}))],'unattached'=>['Sans pièce jointe',array_values(array_filter($documents,static function($d){return (int)$d['attachment_count']===0;}))]];
$date=static function($v){return $v?date('d/m/Y H:i',strtotime($v)):'—';};
$pendingDates=array_filter(array_column($groups['pending'][1],'document_date'));
?>
<div class="butchery-workspace transfer-workspace documents-workspace">
<header class="butchery-heading"><span class="butchery-heading-icon"><i class="bi bi-files" aria-hidden="true"></i></span><div><p>Gouvernance documentaire</p><h2>Documents officiels</h2></div></header>
<?php if($success):?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?>
<div class="butchery-metrics"><?php foreach($groups as $key=>$group):?><button type="button" class="butchery-kpi" data-workspace-modal-open="documents-kpi-<?=e($key)?>"><strong><?=count($group[1])?></strong><span><?=e($group[0])?></span><i class="bi bi-chevron-right" aria-hidden="true"></i></button><?php endforeach;?></div>
<section class="trace-brief"><h3>Lecture de direction</h3><?php if(!$documents):?><p>Aucun document dans le périmètre de sites sélectionné.</p><?php else:?><p><?=count($groups['pending'][1])?> document(s) attendent une validation ou une approbation. <?=count($groups['rejected'][1])?> document(s) refusé(s) sont à examiner.</p><?php if($pendingDates):?><p>Le plus ancien document actuellement en attente est daté du <?=e($date(min($pendingDates)))?>.</p><?php endif;?><small><?=count($types)?> type(s) de document représenté(s). L’absence de pièce jointe n’indique pas à elle seule une non-conformité. Les indicateurs couvrent tout le périmètre ; les filtres ci-dessous s’appliquent au registre.</small><?php endif;?></section>
<section class="table-panel butchery-history"><header class="fuel-section-heading"><h3>Registre documentaire</h3></header><?php $rows=$documents;$filters=true;require __DIR__.'/table.php';?></section>
<?php foreach($groups as $key=>$group):?>
<section id="documents-kpi-<?=e($key)?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="documents-kpi-title-<?=e($key)?>"><header><h2 id="documents-kpi-title-<?=e($key)?>"><?=e($group[0])?></h2><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header><div class="feed-form-body"><?php $rows=$group[1];$filters=false;require __DIR__.'/table.php';?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer></section>
<?php endforeach;?>
<?php foreach($documents as $d):?>
<section id="document-detail-<?=e($d['id'])?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="document-title-<?=e($d['id'])?>"><header><h2 id="document-title-<?=e($d['id'])?>">Détail du document</h2><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header><div class="feed-form-body"><div class="butchery-detail-banner"><strong><?=e($d['document_number'])?></strong><span class="butchery-status"><?=e($labels[$d['status']]??$d['status'])?></span></div><dl class="butchery-history-details"><?php foreach(['Type'=>$d['display_code'].' · '.$d['type_name'],'Site'=>$d['site_code'],'Date du document'=>$date($d['document_date']),'Créé par'=>$d['creator_name']?:'Non renseigné','Validé par'=>$d['validator_name']?:'Non renseigné','Pièces jointes'=>(int)$d['attachment_count']] as $label=>$value):?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl><details class="document-origin"><summary>Référence de l’opération source</summary><p><?=e($d['entity_type'].' #'.$d['entity_id'])?></p></details></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button><a class="btn-primary" href="<?=e(base_url('documents/'.$d['id']))?>">Ouvrir le dossier</a></footer></section>
<?php endforeach;?></div>
