<?php require __DIR__.'/workspace.php'; ?>
<div class="butchery-workspace" data-butchery-workspace>
<header class="butchery-heading"><span class="butchery-heading-icon"><i class="bi bi-shop" aria-hidden="true"></i></span><div><p>Boucherie</p><h2><?=e($butcherySections[$section][1])?></h2></div><span class="butchery-site">BOUCH</span></header><?php if($success):?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?><?php if(!empty($siteRequired)):?><div class="app-alert alert-info"><i class="bi bi-buildings"></i><span>Vue BOUCH en lecture. Sélectionnez le site BOUCH dans le sélecteur de site avant toute opération.</span></div><?php endif;?>

<p class="butchery-guide"><?=e($butcheryGuides[$section])?></p>
<div class="butchery-metrics"><?php foreach($butcheryMetrics[$section] as $metricIndex=>[$value,$label]):?><?php if(in_array($section,['slaughters','production','stocks','outgoing','recipes'],true)):?><button type="button" class="butchery-kpi" data-workspace-modal-open="<?= $section==='recipes'?'butchery-recipes-kpi-':($section==='outgoing'?'butchery-outgoing-kpi-':($section==='stocks'?'butchery-stock-kpi-':($section==='production'?'butchery-production-kpi-':'butchery-kpi-'))) ?><?=$metricIndex?>" aria-haspopup="dialog"><strong><?=e($value)?></strong><span><?=e($label)?></span><i class="bi bi-chevron-right" aria-hidden="true"></i></button><?php else:?><div><strong><?=e($value)?></strong><span><?=e($label)?></span></div><?php endif;?><?php endforeach;?></div>
<div class="butchery-receipt-grid" <?=$section!=='receipts'?'hidden':''?>><section data-butchery-panel="receipts" <?=$section!=='receipts'?'hidden':''?> class="form-panel"><h3><i class="bi bi-heart-pulse" aria-hidden="true"></i> Depuis un élevage</h3><p class="butchery-empty">Réceptionnez un transfert déjà expédié par une ferme.</p><?php ob_start(); ?><form data-butchery-form data-confirm="Confirmer cette opération ?" method="post" action="<?=e(base_url('butchery/receipts'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="<?=e($section)?>"><div class="feed-form-body"><p data-feed-error class="app-alert app-alert-error" role="alert" hidden></p><div class="form-grid"><input type="hidden" name="source_type" value="internal_btr"><label class="butchery-transfer-select"><span>Transfert attendu *</span><select name="livestock_transfer_id" aria-describedby="butchery-transfer-help" required><option value="">Choisir un transfert à recevoir…</option><?php foreach($incoming as $x):
$transferDetails = [
    'reference' => $x['transfer_number'],
    'source' => $x['source_site_name'],
    'destination' => $x['destination_site_name'],
    'batch' => $x['batch_number'],
    'species' => $x['species_name'],
    'quantity' => $x['source_unit']==='head' ? number_format((int)$x['quantity_heads'],0,',',' ').' têtes' : number_format((float)$x['quantity_kg'],3,',',' ').' kg',
    'dispatched' => !empty($x['dispatched_at']) ? date('d/m/Y à H:i',strtotime($x['dispatched_at'])) : 'Non renseignée',
    'truck' => $x['truck_plate'] ?: 'Non renseigné',
    'driver' => $x['driver_name'] ?: 'Non renseigné',
    'unit' => $x['source_unit'],
];
?><option value="<?=e($x['id'])?>" data-transfer-details="<?=e(json_encode($transferDetails,JSON_UNESCAPED_UNICODE))?>"><?=e($x['transfer_number'].' — '.$x['source_site_name'].' — '.$transferDetails['quantity'])?></option><?php endforeach;?></select></label>
<?php require __DIR__.'/transfer_summary.php'; ?>
<label><span>Date et heure *</span><input type="datetime-local" name="received_at" required value="<?=e(date('Y-m-d\TH:i'))?>"></label><label><span data-transfer-cost-label>Coût unitaire</span><input type="number" step="0.0001" name="unit_cost" placeholder="Coût unitaire" min="0"></label></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Recevoir le transfert</button></footer></form><?php $butcheryDrawer('Recevoir le transfert',ob_get_clean(),'create'); ?></section><section data-butchery-panel="receipts" <?=$section!=='receipts'?'hidden':''?> class="form-panel"><h3><i class="bi bi-building" aria-hidden="true"></i> Depuis un fournisseur</h3><p class="butchery-empty">Enregistrez la livraison et son poids reçu.</p><?php ob_start(); ?><form data-butchery-form data-confirm="Confirmer cette opération ?" method="post" action="<?=e(base_url('butchery/receipts'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="<?=e($section)?>"><div class="feed-form-body"><p data-feed-error class="app-alert app-alert-error" role="alert" hidden></p><div class="form-grid"><input type="hidden" name="source_type" value="external_bra"><label><span>Fournisseur *</span><select name="supplier_id" required><?php foreach($suppliers as$x):?><option value="<?=$x['id']?>"><?=e($x['name'])?></option><?php endforeach;?></select></label><label><span>Référence fournisseur *</span><input name="source_reference" placeholder="Référence fournisseur" required></label><label><span>Poids reçu (kg) *</span><input type="number" step="0.001" name="received_weight_kg" placeholder="Poids kg" required min="0"></label><label><span>Coût unitaire</span><input type="number" step="0.0001" name="unit_cost" placeholder="Coût/kg" min="0"></label><label><span>Date et heure *</span><input type="datetime-local" name="received_at" required value="<?=e(date('Y-m-d\TH:i'))?>"></label></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Nouvelle réception fournisseur</button></footer></form><?php $butcheryDrawer('Nouvelle réception fournisseur',ob_get_clean(),'create'); ?></section></div>
<section data-butchery-panel="receipts" <?=$section!=='receipts'?'hidden':''?> class="table-panel"><h3>Contrôles sanitaires en attente</h3><?php if(!$receipts):?><p class="butchery-empty">Aucune réception en attente de contrôle.</p><?php endif;?><table <?=!$receipts?'hidden':''?> class="enterprise-table"><thead><tr><th>Réception</th><th>Origine</th><th>Quantité</th><th>Actions</th></tr></thead><tbody><?php foreach($receipts as$r):?><tr><td><?=e($r['receipt_number'])?></td><td><?=e($r['supplier_name']?:$r['transfer_number'])?></td><td><?=e($r['received_unit']==='head'?$r['received_heads'].' têtes':$r['received_weight_kg'].' kg')?></td><td><?php ob_start(); ?><form data-butchery-form data-confirm="Confirmer ce contrôle sanitaire ?" method="post" action="<?=e(base_url('butchery/receipts/'.$r['id'].'/control'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="<?=e($section)?>"><div class="feed-form-body"><p data-feed-error class="app-alert app-alert-error" role="alert" hidden></p><div class="form-grid"><label><span>Température (°C)</span><input type="number" step="0.1" name="temperature_c" placeholder="°C"></label><label><span>Contrôle visuel</span><select name="visual_status"><option value="conform">Visuel conforme</option><option value="non_conform">Non conforme</option></select></label><label><span>Documents</span><select name="document_status"><option value="conform">Documents conformes</option><option value="non_conform">Non conformes</option></select></label><label><span>Décision</span><select name="decision"><option value="accept">Accepter</option><option value="reject">Refuser</option></select></label><label><span>Article réceptionné</span><select name="item_id"><?php foreach($items as$i):if(!in_array($i['item_kind'],['raw_material','additive']))continue;?><option value="<?=$i['id']?>"><?=e($i['name'])?></option><?php endforeach;?></select></label><label><span>Date de production *</span><input type="date" name="production_date" value="<?=date('Y-m-d')?>" required></label><label><span>Date limite de consommation *</span><input type="date" name="expiry_date" required></label><label><span>Observations</span><input name="notes" placeholder="Observations"></label></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Valider le contrôle</button></footer></form><?php $butcheryDrawer('Contrôler · '.$r['receipt_number'],ob_get_clean(),'validate'); ?></td></tr><?php endforeach;?></tbody></table></section>
<section data-butchery-panel="slaughters" <?=$section!=='slaughters'?'hidden':''?> class="form-panel butchery-slaughter-actions"><div class="butchery-slaughter-toolbar"><h3>Abattages</h3><?php ob_start(); ?><form data-butchery-form data-confirm="Confirmer cette opération ?" method="post" action="<?=e(base_url('butchery/slaughters'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="<?=e($section)?>"><div class="feed-form-body"><p data-feed-error class="app-alert app-alert-error" role="alert" hidden></p><div class="form-grid"><label class="butchery-transfer-select"><span>Lot vivant *</span><select name="live_lot_id" aria-describedby="butchery-live-help" required><option value="">Choisir un lot vivant…</option><?php foreach($availableLive as $x):
$liveDetails=['reference'=>$x['lot_number'],'batch'=>$x['batch_number'] ?: 'Non renseigné','species'=>$x['species_name'] ?: 'Non renseignée','source'=>$x['source_site_name'] ?: 'Non renseignée','receipt'=>$x['receipt_number'] ?: 'Non renseignée','transfer'=>$x['transfer_number'] ?: 'Non renseigné','received'=>date('d/m/Y à H:i',strtotime($x['received_at'])),'heads'=>(int)$x['available_heads'],'status'=>$x['status']==='partially_slaughtered'?'Partiellement abattu':'Disponible'];
?><option value="<?=e($x['id'])?>" data-live-details="<?=e(json_encode($liveDetails,JSON_UNESCAPED_UNICODE))?>"><?=e($x['lot_number'].' — '.($x['species_name'] ?: 'Lot vivant').' — '.$x['available_heads'].' têtes')?></option><?php endforeach;?></select></label>
<?php require __DIR__.'/live_summary.php'; ?>
<label><span>Matière première *</span><select name="raw_item_id" required><?php foreach($items as$i):if($i['item_kind']==='raw_material'):?><option value="<?=$i['id']?>"><?=e($i['name'])?></option><?php endif;endforeach;?></select></label><label><span>Animaux à abattre *</span><input type="number" name="input_heads" placeholder="Nombre de têtes" required min="1" step="1"></label><label><span>Poids brut (kg) *</span><input type="number" step="0.001" name="gross_weight_kg" placeholder="Poids brut kg" required min="0"></label><label><span>Tare (kg)</span><input type="number" step="0.001" name="tare_weight_kg" placeholder="Tare kg" min="0"></label><label><span>Date et heure *</span><input type="datetime-local" name="slaughtered_at" required value="<?=e(date('Y-m-d\TH:i'))?>"></label></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Enregistrer un abattage</button></footer></form><?php $butcheryDrawer('Enregistrer un abattage',ob_get_clean(),'create','Nouvel abattage'); ?>
<button type="button" class="btn-secondary butchery-pending-action" data-workspace-modal-open="butchery-kpi-1" aria-haspopup="dialog">À valider <span><?=count($slaughters)?></span><i class="bi bi-chevron-right" aria-hidden="true"></i></button>
</div></section>
<?php $slaughterValidationButtons=[]; foreach($slaughters as $s): ?>
<?php ob_start(); require __DIR__.'/validate_slaughter.php'; ?><?php $validationForm=ob_get_clean(); ob_start(); $butcheryDrawer('Valider l’abattage',$validationForm,'validate','Valider'); $slaughterValidationButtons[$s['id']]=ob_get_clean(); endforeach; ?>
<?php if(Auth::can('butchery','administer')):?><section data-butchery-panel="recipes" <?=$section!=='recipes'?'hidden':''?> class="form-panel butchery-slaughter-actions"><div class="butchery-slaughter-toolbar"><h3>Fiches de transformation</h3><?php ob_start(); ?><form data-butchery-form data-confirm="Confirmer cette opération ?" method="post" action="<?=e(base_url('butchery/recipes'))?>"><?=csrf_field()?><input type="hidden" name="_section" value="<?=e($section)?>"><div class="feed-form-body"><p data-feed-error class="app-alert app-alert-error" role="alert" hidden></p><div class="form-grid"><label><span>Code de la fiche *</span><input name="code" placeholder="Ex. DEC-PORC" maxlength="60" required><small>Nouveau code : nouvelle fiche. Code existant : nouvelle version de cette fiche.</small></label><label><span>Nom de la fiche *</span><input name="name" placeholder="Ex. Découpe de porc" maxlength="160" required><small>Pour un code existant, le nom de la fiche est conservé.</small></label><label><span>Matière première *</span><select name="raw_item_id" required><?php foreach($items as$i):if($i['item_kind']==='raw_material'):?><option value="<?=$i['id']?>"><?=e($i['name'])?></option><?php endif;endforeach;?></select></label></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Enregistrer la fiche</button></footer></form><?php $butcheryDrawer('Créer une fiche ou une version',ob_get_clean(),'administer','Nouvelle fiche / version','butchery-recipe-editor'); ?></div></section><?php endif;?>
<?php require __DIR__.'/production.php'; ?>

<?php require __DIR__.'/outgoing.php'; ?>
<?php if($section==='stocks') require __DIR__.'/stocks.php'; ?>
<?php if($section==='recipes') require __DIR__.'/recipes.php'; ?>
<?php if(in_array($section,['receipts','slaughters'],true)) require __DIR__.'/history.php'; ?>
<?php if($section==='slaughters') require __DIR__.'/slaughter_kpis.php'; ?>
<?=implode('', $butcheryModals)?>
</div>