<section id="production-detail-<?=e($o['id'])?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="production-title-<?=e($o['id'])?>">
<header><h2 id="production-title-<?=e($o['id'])?>">Détail de la fabrication</h2><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header>
<div class="feed-form-body">
<div class="butchery-detail-banner"><strong><?=e($o['order_number'])?></strong><span class="butchery-status"><?=e($butcheryStatuses[$o['status']]??$o['status'])?></span></div>
<dl class="butchery-history-details">
<?php foreach(['Fiche'=>$o['recipe_name'].' · '.$o['recipe_code'].' · v'.$o['version_number'],'Date de production'=>date('d/m/Y',strtotime($o['production_date'])),'Créé par'=>$o['creator_name']?:'—','Validé par'=>$o['validator_name']?:'—','Créé le'=>!empty($o['created_at'])?date('d/m/Y H:i',strtotime($o['created_at'])):'—','Validé le'=>!empty($o['validated_at'])?date('d/m/Y H:i',strtotime($o['validated_at'])):'—'] as $name=>$value):?><div><dt><?=e($name)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl>
<div class="butchery-detail-balance">
<?php foreach(['Quantité prévue'=>$o['planned_input_kg'],'Entrée réelle'=>$hasResults?$o['actual_input_kg']:null,'Produit obtenu'=>$hasResults?$o['output_kg']:null,'Coproduits'=>$hasResults?$o['co_product_kg']:null,'Pertes'=>$hasResults?$o['loss_kg']:null] as $name=>$value):?><div><span><?=e($name)?></span><strong><?=$value!==null?e(number_format((float)$value,3,',',' ')).' kg':'—'?></strong></div><?php endforeach;?><div><span>Rendement</span><strong><?=$hasResults?e(number_format((float)$o['yield_percent'],2,',',' ')).' %':'—'?></strong></div></div>
<?php if(!$hasResults):?><p class="butchery-detail-note">Les consommations et les produits obtenus apparaîtront après la saisie des résultats. La planification ne réserve pas le stock.</p><?php else:?>
<h3>Matières consommées</h3>
<table class="enterprise-table"><thead><tr><th>Matière</th><th>Lot</th><th>Quantité</th><th>Coût / kg</th></tr></thead><tbody><?php foreach($productionLines['inputs'][$o['id']]??[] as $line):?><tr><td><?=e($line['item_name'])?></td><td><?=e($line['lot_number']?:'—')?></td><td><?=e($line['quantity_kg'])?> kg</td><td><?=e($line['unit_cost'])?></td></tr><?php endforeach;?></tbody></table>
<h3>Produits et lots</h3>
<table class="enterprise-table"><thead><tr><th>Produit</th><th>Type</th><th>Quantité produite</th><th>DLC</th><th>Lot créé</th><th>Stock actuel</th></tr></thead><tbody><?php foreach($productionLines['outputs'][$o['id']]??[] as $line):?><tr><td><?=e($line['item_name'])?></td><td><?=$line['output_type']==='co_product'?'Coproduit':'Produit fini'?></td><td><?=e($line['quantity_kg'])?> kg</td><td><?=e(date('d/m/Y',strtotime($line['expiry_date'])))?></td><td><?=e($line['lot_number']?:'À créer après validation')?></td><td><?=$line['remaining_kg']!==null?e($line['remaining_kg']).' kg':'—'?></td></tr><?php endforeach;?></tbody></table>
<dl class="butchery-history-details"><?php foreach(['Main-d’œuvre'=>$o['labor_cost'],'Énergie'=>$o['energy_cost'],'Frais imputés'=>$o['allocated_cost'],'Coût total validé'=>$o['status']==='validated'?$o['total_cost']:null,'Coût validé / kg'=>$o['status']==='validated'?$o['cost_per_kg']:null] as $name=>$value):?><div><dt><?=e($name)?></dt><dd><?=$value!==null?e(number_format((float)$value,2,',',' ')):'À calculer à la validation'?></dd></div><?php endforeach;?></dl>
<?php endif;?>
</div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer></section>
