<?php
$directory=$recipeDirectory['versions'];$components=$recipeDirectory['components'];
$recipeStatus=static function($v){return $v['recipe_status']!=='active'?'inactive':($v['status']==='active'?'active':'retired');};
$recipeLabels=['active'=>'Active','retired'=>'Ancienne version','inactive'=>'Fiche inactive'];
$activeVersions=array_values(array_filter($directory,static function($v)use($recipeStatus){return $recipeStatus($v)==='active';}));
?>
<section class="table-panel butchery-history" data-butchery-panel="recipes"><header class="butchery-history-heading"><div><h3>Fiches et versions</h3><p>Composition des matières en entrée · Les versions antérieures restent consultables</p></div><span class="butchery-status"><?=count($directory)?> versions</span></header>
<?php if(!$directory):?><p class="butchery-empty">Aucune fiche enregistrée. Créez votre première fiche pour planifier une fabrication.</p><?php else:$recipeRows=$directory;$recipeFilters=true;require __DIR__.'/recipe_table.php';endif;?></section>
<?php foreach($directory as $version):$state=$recipeStatus($version);$lines=$components[$version['id']]??[];?>
<section id="recipe-detail-<?=e($version['id'])?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="recipe-title-<?=e($version['id'])?>"><header><h2 id="recipe-title-<?=e($version['id'])?>">Détail de la fiche</h2><button class="modal-close" type="button" data-workspace-modal-close aria-label="Fermer">×</button></header><div class="feed-form-body">
<div class="butchery-detail-banner"><div><small><?=e($version['code'])?> · Version <?=e($version['version_number'])?></small><strong><?=e($version['name'])?></strong></div><span class="butchery-status <?= $state==='active'?'butchery-status-success':'butchery-status-muted' ?>"><?=e($recipeLabels[$state])?></span></div>
<dl class="butchery-history-details"><?php foreach(['Applicable depuis'=>date('d/m/Y',strtotime($version['effective_from'])),'Créée le'=>date('d/m/Y H:i',strtotime($version['created_at'])),'Créée par'=>$version['creator_name']?:'—'] as $name=>$value):?><div><dt><?=e($name)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl>
<h3 class="butchery-recipe-composition-title">Composition de cette version</h3>
<?php if(!$lines):?><p class="butchery-empty">Aucun composant renseigné.</p><?php else:?><table class="enterprise-table" data-datatable="false"><thead><tr><th>Article</th><th>Type</th><th>Proportion</th></tr></thead><tbody><?php foreach($lines as $line):?><tr><td><?=e($line['item_name'])?><small><?=e($line['item_code'])?></small></td><td><?=$line['component_type']==='raw_material'?'Matière première':'Additif'?></td><td><?=e(number_format((float)$line['percentage'],3,',',' '))?> %</td></tr><?php endforeach;?></tbody></table><?php endif;?>
<p class="butchery-detail-note">Les proportions décrivent les matières en entrée, pas le rendement. Les produits obtenus, les pertes et les DLC sont renseignés lors de la fabrication.</p>
<h3 class="butchery-recipe-composition-title">Versions de cette fiche</h3>
<table class="enterprise-table" data-datatable="false"><thead><tr><th>Version</th><th>Applicable depuis</th><th>Statut</th></tr></thead><tbody><?php foreach($directory as $other):if($other['recipe_id']!=$version['recipe_id'])continue;?><tr><td>v<?=e($other['version_number'])?><?=$other['id']==$version['id']?' · consultée':''?></td><td><?=e(date('d/m/Y',strtotime($other['effective_from'])))?></td><td><?=e($recipeLabels[$recipeStatus($other)])?></td></tr><?php endforeach;?></tbody></table>
</div><footer><button class="btn-secondary" type="button" data-workspace-modal-close>Fermer</button></footer></section>
<?php endforeach;?>
<section id="butchery-recipes-kpi-0" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="recipes-kpi-title"><header><h2 id="recipes-kpi-title">Fiches actives</h2><button class="modal-close" type="button" data-workspace-modal-close aria-label="Fermer">×</button></header><div class="feed-form-body"><?php if(!$activeVersions):?><p class="butchery-empty">Aucune fiche active.</p><?php else:$recipeRows=$activeVersions;$recipeFilters=false;require __DIR__.'/recipe_table.php';endif;?></div><footer><button class="btn-secondary" type="button" data-workspace-modal-close>Fermer</button></footer></section>
