<?php $detailKg=fn($v)=>number_format((float)$v,3,',',' ').' kg';$detailDate=fn($v)=>$v?date('d/m/Y à H:i',strtotime($v)):'Non renseignée';$detailState=$item['status']==='cancelled'?'Annulée':($batchStates[$item['batch_status']]??$states[$item['status']]??$item['status']); ?>
<header class="campaign-drawer-heading"><div><p class="page-kicker">ALIMENTATION · <?=e($item['bss_number']?:'BSS non référencé')?></p><h2 id="feedDetailTitle"><?=e($item['machine_name'])?></h2><small>Depuis <?=e($item['silo_name'])?> · <?=e($detailDate($item['fed_at']))?></small></div><button type="button" class="modal-close" data-feed-detail-close aria-label="Fermer les détails">×</button></header>
<div class="campaign-drawer-body">
<div class="feed-detail-state"><span class="campaign-status feed-status-<?=e($item['status'])?>"><?=e($detailState)?></span><span><?=e($item['product_name'])?></span></div>
<section class="feed-detail-route" aria-label="Parcours du chargement"><div><i class="bi bi-box-seam" aria-hidden="true"></i><small>Silo source</small><strong><?=e($item['silo_name'])?></strong></div><i class="bi bi-arrow-right" aria-hidden="true"></i><div><i class="bi bi-gear" aria-hidden="true"></i><small>Machine destinataire</small><strong><?=e($item['machine_name'])?></strong></div></section>
<dl class="feed-detail-quantities"><div><dt>Quantité chargée</dt><dd><?=e($detailKg($item['quantity_kg']))?></dd></div><div><dt>Autorisée sur le BSS</dt><dd><?=e($detailKg($item['authorized_quantity_kg']))?></dd></div></dl>
<section class="feed-detail-section"><h3>Traçabilité</h3><dl class="feed-detail-facts"><div><dt>Bon de sortie silo</dt><dd><?=e($item['bss_number']?:'Non référencé')?></dd></div><div><dt>Lot de production</dt><dd><?=e($item['batch_number']?:'Non référencé')?></dd></div><div><dt>Début du chargement</dt><dd><?=e($detailDate($item['fed_at']))?></dd></div><div><dt>Fin du chargement</dt><dd><?=e($detailDate($item['ended_at']))?></dd></div><div><dt>Agent responsable</dt><dd><?=e($item['agent_name']?:'Non renseigné')?></dd></div><div><dt>Site de production</dt><dd><?=e($sites[$item['site_id']]['name']??'Non renseigné')?></dd></div></dl></section>
<section class="feed-detail-section"><h3>Observation</h3><p class="feed-detail-observation"><?=e($item['observation']?:'Aucune observation pour cette alimentation.')?></p></section>
</div><footer class="feed-detail-footer"><button type="button" class="btn-secondary" data-feed-detail-close>Fermer</button></footer>
