<?php
$groups=[];$units=[];
foreach($batches as $batch){$groups[$batch['species_id']]['name']=$batch['species_name'];$groups[$batch['species_id']]['lots'][]=$batch;$units[$batch['facility_id']]=$batch['facility_name'];}
uasort($groups,fn($a,$b)=>strnatcasecmp($a['name'],$b['name']));asort($units);
$lotStates=['active'=>'Actif','completed'=>'Terminé','cancelled'=>'Annulé'];
?>
<section data-livestock-space="batches" data-lot-directory>
<div class="lot-toolbar"><div class="lot-view-switch" role="group" aria-label="Affichage des lots"><button type="button" class="btn-secondary" data-lot-view="cards" aria-pressed="true"><i class="bi bi-grid" aria-hidden="true"></i> Cartes</button><button type="button" class="btn-secondary" data-lot-view="table" aria-pressed="false"><i class="bi bi-table" aria-hidden="true"></i> Tableau</button></div><p class="finished-help">Une illustration identifie l’espèce ; l’effectif affiché indique le nombre réel d’animaux.</p></div>
<div class="lot-filters" role="search" aria-label="Filtrer les lots"><label>Rechercher un lot<input type="search" data-lot-search placeholder="Numéro du lot"></label><label <?= $selectedSpecies?'hidden':'' ?>>Espèce<select data-lot-filter="species"><option value="">Toutes</option><?php foreach($groups as $id=>$group): ?><option value="<?=e($id)?>"><?=e($group['name'])?></option><?php endforeach; ?></select></label><label>Bâtiment / étang<select data-lot-filter="facility"><option value="">Tous</option><?php foreach($units as $id=>$name): ?><option value="<?=e($id)?>"><?=e($name)?></option><?php endforeach; ?></select></label><label>Objectif<select data-lot-filter="purpose"><option value="">Tous</option><?php foreach($purposeLabels as $key=>$label): ?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach; ?></select></label><label>Statut<select data-lot-filter="status"><option value="">Tous</option><?php foreach($lotStates as $key=>$label): ?><option value="<?=e($key)?>"><?=e($label)?></option><?php endforeach; ?></select></label><button type="button" class="btn-secondary" data-lot-reset aria-label="Réinitialiser les filtres"><i class="bi bi-arrow-counterclockwise" aria-hidden="true"></i> Réinitialiser</button></div>
<p class="finished-help" data-lot-count aria-live="polite"></p>
<?php if(!$batches): ?><p class="livestock-guide">Aucun lot sur ce périmètre. Créez une unité d’accueil puis un lot pour commencer.</p><?php endif; ?>
<div data-lot-cards class="lot-card-grid"><?php foreach($groups as $group): foreach($group['lots'] as $b): ?>
<article class="lot-card <?=preg_match('/bovin|vache|boeuf|bœuf|cattle/',mb_strtolower($b['species_name']))?'lot-card-cattle':''?>" data-lot-card="<?=e($b['id'])?>" data-animal-category="<?=e($b['category'])?>" data-species="<?=e($b['species_id'])?>" data-facility="<?=e($b['facility_id'])?>" data-purpose="<?=e($b['purpose'])?>" data-status="<?=e($b['status'])?>" data-search="<?=e($b['batch_number'])?>">
<header><div class="lot-card-heading"><h3><?=e($b['species_name'])?></h3><strong><?=e($b['batch_number'])?></strong></div><span class="status-badge status-<?=$b['status']==='active'?'validated':($b['status']==='cancelled'?'cancelled':'pending')?>"><?=e($lotStates[$b['status']]??$b['status'])?></span></header>
<div class="lot-card-visual"><?php require __DIR__.'/animal.php'; ?><div><small>Effectif vivant</small><strong><?=e(number_format((int)$b['current_heads'],0,',',' '))?></strong><span><?=$b['category']==='fish'?'poissons':'têtes'?></span></div></div>
<dl><div><dt>Unité</dt><dd><?=e($b['facility_name'])?></dd></div><div><dt>Objectif</dt><dd><?=e($purposeLabels[$b['purpose']]??$b['purpose'])?></dd></div><div><dt>Entrée du lot</dt><dd><?=e($b['started_at'])?></dd></div><?php if($b['current_average_weight_kg']!==null): ?><div><dt>Poids moyen / animal</dt><dd><?=e(number_format((float)$b['current_average_weight_kg'],3,',',' '))?> kg</dd></div><?php endif; ?></dl>
<footer><button type="button" class="btn-secondary" data-workspace-modal-open="livestock-detail-<?=e($b['id'])?>" aria-label="Consulter le lot <?=e($b['batch_number'])?>"><i class="bi bi-eye" aria-hidden="true"></i> Consulter</button></footer>
</article><?php endforeach; endforeach; ?></div>
<div data-lot-table class="table-panel" hidden><table class="enterprise-table" data-datatable="false"><thead><tr><th>Lot</th><th>Espèce</th><th>Unité</th><th>Vivant</th><th>Poids moyen</th><th>Aliment</th><th>Œufs</th><th>Actions</th></tr></thead><tbody><?php foreach($batches as$b):?><tr data-lot-row="<?=e($b['id'])?>"><td><?=e($b['batch_number'])?></td><td><?=e($b['species_name'].' / '.($purposeLabels[$b['purpose']]??$b['purpose']))?></td><td><?=e($b['facility_name'])?></td><td><strong><?=e($b['current_heads'])?> têtes</strong></td><td><?=e($b['current_average_weight_kg']?:'-')?> kg</td><td><?=e($b['feed_kg'])?> kg</td><td><?=e($b['eggs_count'])?> unités</td><td><button type="button" class="btn-secondary" data-workspace-modal-open="livestock-detail-<?=e($b['id'])?>"><i class="bi bi-eye" aria-hidden="true"></i> Consulter</button></td></tr><?php endforeach;?></tbody></table></div>
<p class="app-alert" data-lot-empty hidden>Aucun lot ne correspond à ces filtres.</p><div class="lot-pagination"><button type="button" class="btn-secondary" data-lot-prev>Précédent</button><span data-lot-page aria-live="polite"></span><button type="button" class="btn-secondary" data-lot-next>Suivant</button></div>
</section>