<?php $statusLabels=['submitted'=>'À valider','validated'=>'Validé','draft'=>'Brouillon','approved'=>'Approuvé','in_transit'=>'En transit','received'=>'Reçu','cancelled'=>'Annulé'];$purposeLabels=['meat'=>'Chair','laying'=>'Ponte','fattening'=>'Engraissement','breeding'=>'Reproduction']; ?>
<div class="livestock-directory <?= $space==='conversions'?'livestock-conversions-page':'' ?>" data-livestock-directory data-selected-species="<?=e($selectedSpecies['id']??'')?>" data-site-scope="<?=e(Auth::currentSiteId()??'all')?>">
<section class="dashboard-hero"><span class="hero-icon"><i class="bi bi-<?=e($pageIcon)?>" aria-hidden="true"></i></span><div><p class="section-label">ÉLEVAGE · MUTALA & DIKAPA</p><h2><?=e($title)?></h2><p><?=e($pageHelp)?></p></div><?php if(in_array($space,['batches','species'],true)): ?><?php if(Auth::can('livestock','create')): ?><button type="button" class="btn-secondary" data-workspace-modal-open="livestock-batches"><i class="bi bi-plus-circle" aria-hidden="true"></i> <?= $selectedSpecies?'Nouveau lot · '.e($selectedSpecies['name']):'Nouveau lot vivant' ?></button><?php endif; ?><?php endif; ?><?php if($space!=='species'): ?><a class="page-action" href="<?=e(base_url('livestock'))?>"><i class="bi bi-arrow-left" aria-hidden="true"></i> Espèces</a><?php endif; ?></section>
<?php if($success): ?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif; ?><?php if($error): ?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif; ?>
<?php require __DIR__.'/'.$space.'.php'; ?>
<?php foreach($modalKinds as $kind) require __DIR__.'/modal_'.$kind.'.php'; ?>
<?php if(in_array($space,['batches','species'],true)) require __DIR__.'/details.php'; ?>
<script type="application/json" data-livestock-batches><?=json_encode($formRefs['batches'],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?></script>
</div>
