<?php
$speciesGroups=[];
foreach($refs['species'] as $species)$speciesGroups[$species['id']]=['name'=>$species['name'],'category'=>$species['category'],'heads'=>0,'active'=>0,'total'=>0];
foreach($batches as $batch){$id=$batch['species_id'];if(!isset($speciesGroups[$id]))$speciesGroups[$id]=['name'=>$batch['species_name'],'category'=>$batch['category'],'heads'=>0,'active'=>0,'total'=>0];$speciesGroups[$id]['total']++;if($batch['status']==='active'){$speciesGroups[$id]['active']++;$speciesGroups[$id]['heads']+=(int)$batch['current_heads'];}}
uasort($speciesGroups,fn($a,$b)=>strnatcasecmp($a['name'],$b['name']));
?>
<section data-livestock-space="species"><div class="lot-toolbar"><p class="finished-help">Effectifs des lots actifs du site sélectionné, ou cumul en vue « Tous les sites ».</p><a class="btn-secondary" href="<?=e(base_url('livestock/lots'))?>"><i class="bi bi-table" aria-hidden="true"></i> Tous les lots</a></div>
<div class="lot-card-grid"><?php foreach($speciesGroups as $id=>$group): $b=['species_name'=>$group['name'],'category'=>$group['category']]; ?>
<article class="lot-card species-card <?=preg_match('/bovin|vache|boeuf|bœuf|cattle/',mb_strtolower($group['name']))?'lot-card-cattle':''?>" data-species-card="<?=e($id)?>" data-animal-category="<?=e($group['category'])?>"><header><div class="lot-card-heading"><h3><?=e($group['name'])?></h3><small><?=e($group['active'])?> lot(s) actif(s)</small></div></header><div class="lot-card-visual"><?php require __DIR__.'/animal.php'; ?><div><small>Effectif vivant</small><strong data-species-heads><?=e(number_format($group['heads'],0,',',' '))?></strong><span><?=$group['category']==='fish'?'poissons':'têtes'?></span></div></div><p class="species-card-caption"><?=$group['total']?e($group['total']).' lot(s) au total, historique inclus.':'Aucun lot enregistré dans ce périmètre.'?></p><footer><button type="button" class="btn-secondary" data-workspace-modal-open="livestock-species-<?=e($id)?>" aria-label="Voir les lots : <?=e($group['name'])?>"><i class="bi bi-arrow-right" aria-hidden="true"></i> Voir les lots</button></footer></article>
<?php endforeach; ?></div><?php if(!$speciesGroups): ?><p class="app-alert">Aucune espèce disponible.</p><?php endif; ?></section>

<?php foreach($speciesGroups as $id=>$group): $speciesLots=array_filter($batches,fn($lot)=>(int)$lot['species_id']===(int)$id); ?>
<section id="livestock-species-<?=e($id)?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor livestock-species-detail" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="livestock-species-title-<?=e($id)?>">
<header><div><p class="page-kicker">ÉLEVAGE · LOTS PAR ESPÈCE</p><h2 id="livestock-species-title-<?=e($id)?>"><?=e($group['name'])?></h2></div><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header>
<div class="feed-form-body"><p class="livestock-guide"><strong><?=e(number_format($group['heads'],0,',',' '))?> <?=$group['category']==='fish'?'poissons':'têtes vivantes'?></strong> · <?=e($group['active'])?> lot(s) actif(s). Les lots ci-dessous correspondent au périmètre du site sélectionné.</p>
<?php if(!$speciesLots): ?><p class="app-alert">Aucun lot pour cette espèce sur ce périmètre.</p><?php else: ?>
<table class="enterprise-table"><thead><tr><th>Lot</th><th>Unité</th><th>Objectif</th><th>Effectif vivant</th><th>Entrée</th><th>Statut</th><th>Actions</th></tr></thead><tbody><?php foreach($speciesLots as $lot): ?><tr data-species-lot="<?=e($lot['id'])?>"><td><strong><?=e($lot['batch_number'])?></strong></td><td><?=e($lot['facility_name'])?></td><td><?=e($purposeLabels[$lot['purpose']]??$lot['purpose'])?></td><td><?=e(number_format((int)$lot['current_heads'],0,',',' '))?></td><td><?=e($lot['started_at'])?></td><td><?=e(['active'=>'Actif','completed'=>'Terminé','cancelled'=>'Annulé'][$lot['status']]??$lot['status'])?></td><td><button type="button" class="btn-secondary" data-workspace-modal-open="livestock-detail-<?=e($lot['id'])?>"><i class="bi bi-eye" aria-hidden="true"></i> Consulter</button></td></tr><?php endforeach; ?></tbody></table>
<?php endif; ?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button><?php if(Auth::can('livestock','create')): ?><button type="button" class="btn-primary" data-workspace-modal-open="livestock-batches" data-livestock-species="<?=e($id)?>"><i class="bi bi-plus-circle" aria-hidden="true"></i> Nouveau lot · <?=e($group['name'])?></button><?php endif; ?></footer></section>
<?php endforeach; ?>
