<?php
require_once dirname(__DIR__).'/tests/integration/TestBootstrap.php';$db=DagrilIntegrationTest::boot();require_once dirname(__DIR__).'/app/models/FuelLogistics.php';
$site=(int)DagrilIntegrationTest::scalar("SELECT id FROM sites WHERE code='DEP-DEV'");$center=(int)DagrilIntegrationTest::scalar('SELECT id FROM cost_centers WHERE site_id=? AND status=\'active\' LIMIT 1',[$site]);$fuel=(int)DagrilIntegrationTest::scalar("SELECT id FROM fuel_types WHERE status='active' LIMIT 1");if(!$site||!$center||!$fuel)throw new RuntimeException('Fixtures carburant/site/centre absentes.');
$user=DagrilIntegrationTest::loginRole('administrateur',$site);$suffix=strtoupper(bin2hex(random_bytes(4)));
$db->prepare("INSERT INTO trucks(plate_number,driver_name,status) VALUES(?,?,'active')")->execute(['TST-FUEL-'.$suffix,'Chauffeur intégration']);$truck=(int)$db->lastInsertId();
$db->prepare("INSERT INTO logistics_assets(site_id,truck_id,code,name,asset_type,meter_type,current_meter,status) VALUES(?,?,?,?,'vehicle','odometer',1000,'active')")->execute([$site,$truck,'TST-A-'.$suffix,'Véhicule test']);$asset=(int)$db->lastInsertId();
$db->prepare("INSERT INTO logistics_people(site_id,code,name,person_type,status) VALUES(?,?,?,'driver','active')")->execute([$site,'TST-P-'.$suffix,'Conducteur test']);$person=(int)$db->lastInsertId();
$db->prepare('INSERT INTO fuel_stocks(site_id,fuel_type_id,physical_quantity,reserved_quantity,average_unit_cost) VALUES(?,?,500,0,2) ON DUPLICATE KEY UPDATE physical_quantity=500,reserved_quantity=0,average_unit_cost=2')->execute([$site,$fuel]);$stock=DagrilIntegrationTest::row('SELECT * FROM fuel_stocks WHERE site_id=? AND fuel_type_id=?',[$site,$fuel]);
$m=new FuelLogistics();$key='fuel-'.$suffix;$data=['cost_center_id'=>$center,'fuel_type_id'=>$fuel,'asset_id'=>$asset,'person_id'=>$person,'mission_id'=>'','idempotency_key'=>$key,'quantity'=>50,'meter_before'=>1000,'meter_after'=>1100,'distributed_at'=>date('Y-m-d H:i:s')];$id=$m->distribute($data,$user);
DagrilIntegrationTest::check(abs((float)DagrilIntegrationTest::scalar('SELECT physical_quantity FROM fuel_stocks WHERE id=?',[$stock['id']])-450)<0.001,'Distribution diminue le stock carburant');
DagrilIntegrationTest::check((int)DagrilIntegrationTest::scalar("SELECT COUNT(*) FROM fuel_stock_movements WHERE stock_id=? AND movement_type='distribution' AND source_id=?",[$stock['id'],$id])===1,'Mouvement carburant traçable créé');
DagrilIntegrationTest::check((int)DagrilIntegrationTest::scalar("SELECT COUNT(*) FROM activity_logs WHERE module='fuel-logistics' AND entity_id=?",[$id])===1,'Distribution carburant auditée');
$same=$m->distribute($data,$user);DagrilIntegrationTest::check((int)$same===$id&&(int)DagrilIntegrationTest::scalar('SELECT COUNT(*) FROM fuel_distributions WHERE idempotency_key=?',[$key])===1,'Distribution carburant idempotente');
DagrilIntegrationTest::expectException(function()use($m,$data,$user,$suffix){$bad=$data;$bad['idempotency_key']='neg-'.$suffix;$bad['quantity']=1000;$bad['meter_before']=1100;$bad['meter_after']=1200;$m->distribute($bad,$user);},'Stock carburant négatif interdit');
DagrilIntegrationTest::check(abs((float)DagrilIntegrationTest::scalar('SELECT physical_quantity FROM fuel_stocks WHERE id=?',[$stock['id']])-450)<0.001,'Erreur de stock sans effet partiel');
DagrilIntegrationTest::expectException(function()use($m,$data,$user,$suffix){$bad=$data;$bad['idempotency_key']='chrono-'.$suffix;$bad['meter_before']=900;$bad['meter_after']=950;$m->distribute($bad,$user);},'Chronologie compteur incohérente refusée');
DagrilIntegrationTest::check((int)DagrilIntegrationTest::scalar('SELECT COUNT(*) FROM documents WHERE entity_type=\'fuel_distributions\' AND entity_id=?',[$id])===0,'Aucun document officiel requis pour une distribution simple');
DagrilIntegrationTest::finish();
