<?php
require dirname(__DIR__).'/app/helpers/functions.php';
require dirname(__DIR__).'/app/core/Database.php';
require dirname(__DIR__).'/app/core/Model.php';
require dirname(__DIR__).'/app/core/Auth.php';
require dirname(__DIR__).'/app/models/WeighbridgeTransport.php';
require dirname(__DIR__).'/app/models/Weighing.php';
Auth::start(); ob_start(); $_SERVER['HTTP_USER_AGENT']='WeighbridgeTransportTest';
$db=Database::getInstance()->connection(); $fail=[]; $created=['weighings'=>[],'weighbridge_transports'=>[],'silos'=>[],'trucks'=>[],'suppliers'=>[]];
function wtq($db,$sql,$p=[]){$s=$db->prepare($sql);$s->execute($p);return$s;}
function wtok($condition,$message){global$fail;echo($condition?'OK  - ':'FAIL - ').$message."\n";if(!$condition)$fail[]=$message;}
function wtuser($db,$exclude=0){return wtq($db,"SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id<>? AND u.status='active' AND u.deleted_at IS NULL AND r.slug IN('administrateur','direction') ORDER BY FIELD(r.slug,'administrateur','direction') LIMIT 1",[$exclude])->fetch();}
function wtcleanup($db,$created){
  $entities=['weighings'=>$created['weighings'],'weighbridge_transports'=>$created['weighbridge_transports']];
  $nc=wtq($db,"SELECT id FROM weighbridge_non_conformities WHERE weighing_id IN (".implode(',',array_map('intval',$created['weighings']?:[0])).")")->fetchAll(PDO::FETCH_COLUMN);
  $ret=wtq($db,"SELECT id FROM weighbridge_returns WHERE weighing_id IN (".implode(',',array_map('intval',$created['weighings']?:[0])).")")->fetchAll(PDO::FETCH_COLUMN);
  $entities['weighbridge_non_conformities']=$nc;$entities['weighbridge_returns']=$ret;
  foreach($entities as$type=>$ids){if(!$ids)continue;$ph=implode(',',array_fill(0,count($ids),'?'));$docs=wtq($db,"SELECT id FROM documents WHERE entity_type=? AND entity_id IN ($ph)",array_merge([$type],$ids))->fetchAll(PDO::FETCH_COLUMN);if($docs){$dp=implode(',',array_fill(0,count($docs),'?'));$wf=wtq($db,"SELECT id FROM workflow_instances WHERE document_id IN ($dp)",$docs)->fetchAll(PDO::FETCH_COLUMN);if($wf){$wp=implode(',',array_fill(0,count($wf),'?'));foreach(['workflow_notifications','workflow_level_approvals','workflow_transitions']as$t)wtq($db,"DELETE FROM $t WHERE workflow_instance_id IN ($wp)",$wf);wtq($db,"DELETE FROM workflow_instances WHERE id IN ($wp)",$wf);}wtq($db,"DELETE FROM document_status_history WHERE document_id IN ($dp)",$docs);wtq($db,"DELETE FROM documents WHERE id IN ($dp)",$docs);}}
  wtq($db,"DELETE FROM activity_logs WHERE user_agent='WeighbridgeTransportTest'");
  $w=$created['weighings'];if($w){$p=implode(',',array_fill(0,count($w),'?'));wtq($db,"DELETE FROM silo_movements WHERE weighing_id IN ($p)",$w);wtq($db,"DELETE FROM weighbridge_returns WHERE weighing_id IN ($p)",$w);wtq($db,"DELETE FROM weighbridge_non_conformities WHERE weighing_id IN ($p)",$w);wtq($db,"DELETE FROM weighings WHERE id IN ($p)",$w);}
  foreach(['weighbridge_transports','silos','trucks','suppliers']as$t){$ids=$created[$t];if($ids){$p=implode(',',array_fill(0,count($ids),'?'));wtq($db,"DELETE FROM $t WHERE id IN ($p)",$ids);}}
}
try{
 $creator=wtuser($db);$validator=wtuser($db,$creator['id']);if(!$creator||!$validator)throw new RuntimeException('Deux utilisateurs de test sont requis.');
 $site=(int)wtq($db,"SELECT id FROM sites WHERE code='SILO'")->fetchColumn();$farm=(int)wtq($db,"SELECT id FROM sites WHERE code='FARM-MUT'")->fetchColumn();$product=(int)wtq($db,"SELECT id FROM products WHERE category='raw_material' AND deleted_at IS NULL LIMIT 1")->fetchColumn();$other=(int)wtq($db,"SELECT id FROM products WHERE id<>? AND deleted_at IS NULL LIMIT 1",[$product])->fetchColumn();
 Auth::login($creator);Auth::selectSite((string)$site);$creator=Auth::user();
 wtq($db,"INSERT INTO suppliers(name,status) VALUES('TST Pont transport','active')");$supplier=(int)$db->lastInsertId();$created['suppliers'][]=$supplier;
 wtq($db,"INSERT INTO silos(site_id,name,code,product_id,capacity_kg,current_stock_kg,status) VALUES(?,? ,?, ?,5000,500,'active')",[$site,'TST Silo transport','TST-WBT-'.random_int(1000,9999),$product]);$silo=(int)$db->lastInsertId();$created['silos'][]=$silo;
 wtq($db,"INSERT INTO silos(site_id,name,code,product_id,capacity_kg,current_stock_kg,status) VALUES(?,? ,?, ?,5000,0,'active')",[$site,'TST Silo incompatible','TST-WBI-'.random_int(1000,9999),$other]);$wrong=(int)$db->lastInsertId();$created['silos'][]=$wrong;
 wtq($db,"INSERT INTO silos(site_id,name,code,product_id,capacity_kg,current_stock_kg,status) VALUES(?,? ,?, ?,600,500,'active')",[$site,'TST Silo plein','TST-WBC-'.random_int(1000,9999),$product]);$full=(int)$db->lastInsertId();$created['silos'][]=$full;
 $tm=new WeighbridgeTransport();$wm=new Weighing();
 $make=function($origin,$qualityReject=false)use(&$created,$tm,$wm,$creator,$supplier,$farm,$product){$plate='TST-WB-'.random_int(10000,99999);$tid=$tm->createTransport(['origin_type'=>'external_supplier','origin_site_id'=>$farm,'supplier_id'=>$supplier,'product_id'=>$product,'truck_plate_number'=>$plate,'driver_name'=>'Test chauffeur','driver_phone'=>'','shipped_quantity_kg'=>1000,'route_description'=>'Ferme - Silo','toll_amount'=>10,'toll_details'=>'Péage test'],$creator);if($origin==='internal_farm'){wtq(Database::getInstance()->connection(),"UPDATE weighbridge_transports SET origin_type='internal_farm',origin_site_id=? WHERE id=?",[$farm,$tid]);}$created['weighbridge_transports'][]=$tid;$created['trucks'][]=(int)wtq(Database::getInstance()->connection(),'SELECT truck_id FROM weighbridge_transports WHERE id=?',[$tid])->fetchColumn();$wid=$wm->createEntry(['transport_id'=>$tid,'poids_brut'=>1300],$creator);$created['weighings'][]=$wid;return$wid;};
 try{$tm->createTransport(['origin_type'=>'internal_farm'],$creator);$blocked=false;}catch(Exception$e){$blocked=true;}wtok($blocked,'Création directe de BT agricole interdite; origine interne réservée au circuit agricole');
 $accepted=$make('external_supplier');wtok((float)wtq($db,'SELECT current_stock_kg FROM silos WHERE id=?',[$silo])->fetchColumn()===500.0,'Première pesée sans entrée silo');
 Auth::login($validator);Auth::selectSite((string)$site);$validator=Auth::user();$quality=['poids_tare'=>300,'silo_id'=>$silo,'humidity_percent'=>12,'impurities_percent'=>1,'weight_tolerance_percent'=>2,'max_humidity_percent'=>14,'max_impurities_percent'=>2,'quality_notes'=>'Conforme','decision'=>'accept'];$wm->validateExit($accepted,$quality,$validator);
 wtok((float)wtq($db,'SELECT current_stock_kg FROM silos WHERE id=?',[$silo])->fetchColumn()===1500.0,'Validation augmente atomiquement le stock silo');wtok((int)wtq($db,"SELECT COUNT(*) FROM documents d JOIN document_types dt ON dt.id=d.document_type_id WHERE dt.code='BRS' AND d.entity_type='weighings' AND d.entity_id=?",[$accepted])->fetchColumn()===1,'BRS créé avec la validation');
 try{$wm->validateExit($accepted,$quality,$validator);$double=false;}catch(Exception$e){$double=true;}wtok($double,'Double validation refusée');
 Auth::login($creator);Auth::selectSite((string)$site);$creator=Auth::user();$external=$make('external_supplier');Auth::login($validator);Auth::selectSite((string)$site);$validator=Auth::user();$bad=$quality;$bad['humidity_percent']=20;$bad['quality_notes']='Humidité excessive';$bad['decision']='reject';$before=(float)wtq($db,'SELECT current_stock_kg FROM silos WHERE id=?',[$silo])->fetchColumn();$wm->validateExit($external,$bad,$validator);wtok((float)wtq($db,'SELECT current_stock_kg FROM silos WHERE id=?',[$silo])->fetchColumn()===$before,'Refus externe sans mouvement ni réintégration DAGRIL');
 Auth::login($creator);Auth::selectSite((string)$site);$creator=Auth::user();$internal=$make('internal_farm');Auth::login($validator);Auth::selectSite((string)$site);$validator=Auth::user();$wm->validateExit($internal,$bad,$validator);wtok((int)wtq($db,"SELECT COUNT(*) FROM weighbridge_returns WHERE weighing_id=? AND status='planned'",[$internal])->fetchColumn()===1,'Refus interne crée un retour traçable');wtok((int)wtq($db,"SELECT COUNT(*) FROM weighbridge_non_conformities WHERE weighing_id IN (?,?)",[$external,$internal])->fetchColumn()===2,'Non-conformités et écarts conservés');
 $wm->progressReturn($internal,'dispatch',$validator);$wm->progressReturn($internal,'receive',$validator);$wm->progressReturn($internal,'close',$validator);wtok(wtq($db,'SELECT status FROM weighings WHERE id=?',[$internal])->fetchColumn()==='returned','Retour interne expédié, reçu puis clôturé sans mouvement silo');
 Auth::login($creator);Auth::selectSite((string)$site);$creator=Auth::user();$incompatible=$make('external_supplier');Auth::login($validator);Auth::selectSite((string)$site);$validator=Auth::user();$x=$quality;$x['silo_id']=$wrong;try{$wm->validateExit($incompatible,$x,$validator);$blocked=false;}catch(Exception$e){$blocked=true;}wtok($blocked,'Compatibilité produit/silo contrôlée sous verrou');
 Auth::login($creator);Auth::selectSite((string)$site);$creator=Auth::user();$overCapacity=$make('external_supplier');Auth::login($validator);Auth::selectSite((string)$site);$validator=Auth::user();$x=$quality;$x['silo_id']=$full;try{$wm->validateExit($overCapacity,$x,$validator);$blocked=false;}catch(Exception$e){$blocked=true;}wtok($blocked,'Capacité du silo contrôlée sous verrou');
}catch(Exception$e){echo'ERREUR - '.$e->getMessage()."\n";$fail[]=$e->getMessage();}finally{wtcleanup($db,$created);}ob_end_flush();if($fail){exit(1);}echo"\nProcessus pont-bascule conforme.\n";
