<?php
require_once dirname(__DIR__).'/app/helpers/functions.php';require_once dirname(__DIR__).'/app/core/Database.php';require_once dirname(__DIR__).'/app/core/Model.php';require_once dirname(__DIR__).'/app/core/Auth.php';require_once dirname(__DIR__).'/app/services/DocumentService.php';require_once dirname(__DIR__).'/app/services/WorkflowService.php';
ob_start();Auth::start();$db=Database::getInstance()->connection();$documentIds=[];$definitionIds=[];$assignmentIds=[];$delegationIds=[];
function wf_ok($v,$m){if(!$v){throw new RuntimeException('ECHEC: '.$m);}echo"[OK] {$m}\n";}function wf_one($db,$sql,$p=[]){$s=$db->prepare($sql);$s->execute($p);return$s->fetch();}function wf_forbidden($call,$m){$blocked=false;try{$call();}catch(Exception$e){$blocked=true;}wf_ok($blocked,$m);}
try{
 $creator=wf_one($db,"SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id WHERE r.slug='administrateur' AND u.status='active' LIMIT 1");$validator=wf_one($db,"SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id WHERE r.slug='direction' AND u.status='active' LIMIT 1");$fieldUsers=$db->query("SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id WHERE r.slug NOT IN('administrateur','direction') AND u.status='active' LIMIT 2")->fetchAll();if(count($fieldUsers)<2){throw new RuntimeException('Deux utilisateurs terrain sont requis.');}$validator2=$fieldUsers[0];$delegate=$fieldUsers[1];$site=wf_one($db,"SELECT id FROM sites WHERE code='MINO'");$type=wf_one($db,"SELECT id FROM document_types WHERE code='BT'");$directionRole=wf_one($db,"SELECT id FROM roles WHERE slug='direction'");Auth::login($creator);Auth::selectSite((string)$site['id']);
 $docService=new DocumentService($db);$workflow=new WorkflowService($db);$key=random_int(1000000,9000000);
 $doc=$docService->register('BT',$site['id'],'workflow_qa',$key,'draft',date('Y-m-d H:i:s'),$creator);$documentIds[]=$doc['id'];$instance=wf_one($db,'SELECT * FROM workflow_instances WHERE document_id=:id',['id'=>$doc['id']]);
 wf_forbidden(function()use($workflow,$instance,$validator){$workflow->transition($instance['id'],'approve',$validator);},'Approbation interdite depuis draft');
 $instance=$workflow->transition($instance['id'],'submit',$creator);wf_ok($instance['current_state']==='submitted','draft vers submitted');
 $instance=$workflow->transition($instance['id'],'request_approval',$creator);wf_ok($instance['current_state']==='pending_approval','submitted vers pending_approval');
 wf_forbidden(function()use($workflow,$instance,$creator){$workflow->transition($instance['id'],'approve',$creator);},'Séparation créateur-validateur');
 wf_forbidden(function()use($workflow,$instance,$validator){$workflow->transition($instance['id'],'reject',$validator,'');},'Refus sans motif interdit');
 $instance=$workflow->transition($instance['id'],'reject',$validator,'Dossier incomplet');wf_ok($instance['current_state']==='rejected','Refus motivé');
 $instance=$workflow->transition($instance['id'],'submit',$creator);$instance=$workflow->transition($instance['id'],'request_approval',$creator);$instance=$workflow->transition($instance['id'],'approve',$validator);wf_ok($instance['current_state']==='approved','Resoumission puis approbation');
 wf_forbidden(function()use($workflow,$instance,$validator){$workflow->transition($instance['id'],'approve',$validator);},'Double approbation interdite');
 wf_forbidden(function()use($workflow,$instance,$creator){$workflow->transition($instance['id'],'cancel',$creator,'');},'Annulation approuvée sans motif interdite');
 $instance=$workflow->transition($instance['id'],'start',$validator);wf_ok($instance['current_state']==='in_progress','approved vers in_progress');$instance=$workflow->transition($instance['id'],'receive',$validator);wf_ok($instance['current_state']==='received','in_progress vers received');$instance=$workflow->transition($instance['id'],'close',$validator);wf_ok($instance['current_state']==='closed','received vers closed');wf_forbidden(function()use($workflow,$instance,$creator){$workflow->transition($instance['id'],'cancel',$creator,'Après clôture');},'Annulation après clôture interdite');

 $db->prepare("INSERT INTO workflow_definitions(name,document_type_id,site_id,min_amount,max_amount,approval_levels,priority) VALUES('QA deux niveaux',:type,:site,100,200,2,100)")->execute(['type'=>$type['id'],'site'=>$site['id']]);$twoDef=(int)$db->lastInsertId();$definitionIds[]=$twoDef;$db->prepare("INSERT INTO workflow_steps(workflow_definition_id,level_number,name) VALUES(:id,1,'Niveau 1'),(:id2,2,'Niveau 2')")->execute(['id'=>$twoDef,'id2'=>$twoDef]);
 $db->prepare("INSERT INTO user_role_assignments(user_id,role_id,site_id,assignment_type,starts_at,approval_status,requested_by,approved_by,approved_at,reason) VALUES(:user,:role,:site,'direct',NOW(),'approved',:creator,:creator2,NOW(),'QA workflow')")->execute(['user'=>$validator2['id'],'role'=>$directionRole['id'],'site'=>$site['id'],'creator'=>$creator['id'],'creator2'=>$creator['id']]);$assignmentIds[]=(int)$db->lastInsertId();
 $doc2=$docService->register('BT',$site['id'],'workflow_qa',$key+1,'draft',date('Y-m-d H:i:s'),$creator,150);$documentIds[]=$doc2['id'];$i2=wf_one($db,'SELECT * FROM workflow_instances WHERE document_id=:id',['id'=>$doc2['id']]);wf_ok((int)$i2['required_levels']===2,'Règle montant/site à deux niveaux sélectionnée');$i2=$workflow->transition($i2['id'],'submit',$creator);$i2=$workflow->transition($i2['id'],'request_approval',$creator);$i2=$workflow->transition($i2['id'],'approve',$validator);wf_ok($i2['current_state']==='pending_approval'&&(int)$i2['current_level']===1,'Premier niveau sans validation finale');wf_forbidden(function()use($workflow,$i2,$validator){$workflow->transition($i2['id'],'approve',$validator);},'Même approbateur interdit sur deux niveaux');$i2=$workflow->transition($i2['id'],'approve',$validator2);wf_ok($i2['current_state']==='approved','Deuxième niveau par un autre approbateur');

 $db->prepare("INSERT INTO workflow_definitions(name,document_type_id,site_id,min_amount,max_amount,approval_levels,priority) VALUES('QA délégation',:type,:site,300,400,1,200)")->execute(['type'=>$type['id'],'site'=>$site['id']]);$delDef=(int)$db->lastInsertId();$definitionIds[]=$delDef;$db->prepare("INSERT INTO workflow_steps(workflow_definition_id,level_number,name,required_role_id) VALUES(:id,1,'Direction déléguée',:role)")->execute(['id'=>$delDef,'role'=>$directionRole['id']]);$delegationIds[]=$workflow->delegate(['delegator_id'=>$validator['id'],'delegate_id'=>$delegate['id'],'document_type_id'=>$type['id'],'site_id'=>$site['id'],'starts_at'=>date('Y-m-d H:i:s',time()-60),'expires_at'=>date('Y-m-d H:i:s',time()+3600),'reason'=>'QA'],$creator);
 $doc3=$docService->register('BT',$site['id'],'workflow_qa',$key+2,'draft',date('Y-m-d H:i:s'),$creator,350);$documentIds[]=$doc3['id'];$i3=wf_one($db,'SELECT * FROM workflow_instances WHERE document_id=:id',['id'=>$doc3['id']]);$i3=$workflow->transition($i3['id'],'submit',$creator);$i3=$workflow->transition($i3['id'],'request_approval',$creator);$i3=$workflow->transition($i3['id'],'approve',$delegate);wf_ok($i3['current_state']==='approved','Délégation temporaire effective');$decision=wf_one($db,'SELECT delegated_by FROM workflow_level_approvals WHERE workflow_instance_id=:id',['id'=>$i3['id']]);wf_ok((int)$decision['delegated_by']===(int)$validator['id'],'Délégant tracé');
 $notifications=(int)$db->query('SELECT COUNT(*) FROM workflow_notifications')->fetchColumn();wf_ok($notifications>0,'Notifications créées');$history=wf_one($db,'SELECT COUNT(*) total FROM workflow_transitions WHERE workflow_instance_id=:id',['id'=>$instance['id']]);wf_ok((int)$history['total']>=8,'Historique complet des transitions');echo"Tous les tests du moteur de validation sont conformes.\n";
}finally{
 if($documentIds){$p=implode(',',array_fill(0,count($documentIds),'?'));$wi=$db->prepare("SELECT id FROM workflow_instances WHERE document_id IN ({$p})");$wi->execute($documentIds);$instanceIds=$wi->fetchAll(PDO::FETCH_COLUMN);if($instanceIds){$q=implode(',',array_fill(0,count($instanceIds),'?'));foreach(['workflow_notifications','workflow_level_approvals','workflow_transitions']as$t){$s=$db->prepare("DELETE FROM {$t} WHERE workflow_instance_id IN ({$q})");$s->execute($instanceIds);}$s=$db->prepare("DELETE FROM workflow_instances WHERE id IN ({$q})");$s->execute($instanceIds);}$s=$db->prepare("DELETE FROM document_status_history WHERE document_id IN ({$p})");$s->execute($documentIds);$s=$db->prepare("DELETE FROM documents WHERE id IN ({$p})");$s->execute($documentIds);}
 foreach($delegationIds as$id){$db->prepare("DELETE FROM activity_logs WHERE module='workflows' AND entity_type='workflow_delegations' AND entity_id=?")->execute([$id]);$db->prepare('DELETE FROM workflow_delegations WHERE id=?')->execute([$id]);}foreach($assignmentIds as$id){$db->prepare('DELETE FROM user_role_assignments WHERE id=?')->execute([$id]);}foreach(array_reverse($definitionIds)as$id){$db->prepare('DELETE FROM workflow_steps WHERE workflow_definition_id=?')->execute([$id]);$db->prepare('DELETE FROM workflow_definitions WHERE id=?')->execute([$id]);}Auth::logout();$out=ob_get_clean();echo$out;
}
