<?php
require_once dirname(__DIR__).'/app/helpers/functions.php';require_once dirname(__DIR__).'/app/core/Database.php';require_once dirname(__DIR__).'/app/core/Model.php';require_once dirname(__DIR__).'/app/core/Auth.php';require_once dirname(__DIR__).'/app/services/DocumentService.php';require_once dirname(__DIR__).'/app/services/PdfService.php';require_once dirname(__DIR__).'/app/models/Weighing.php';require_once dirname(__DIR__).'/app/models/Distribution.php';
$autoload=dirname(__DIR__).'/vendor/autoload.php';if(file_exists($autoload)){require_once $autoload;}ob_start();Auth::start();$db=Database::getInstance()->connection();$ids=[];
function doc_ok($condition,$label){if(!$condition){throw new RuntimeException('ECHEC: '.$label);}echo"[OK] {$label}\n";}
try{$admin=$db->query("SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id WHERE r.slug='administrateur' AND u.status='active' LIMIT 1")->fetch();$site=$db->query("SELECT id,code FROM sites WHERE code='MINO'")->fetch();Auth::login($admin);Auth::selectSite((string)$site['id']);$service=new DocumentService($db);$key=random_int(100000,999999);
 $a=$service->register('BT',$site['id'],'qa_document',$key,'draft',date('Y-m-d H:i:s'),$admin);$ids[]=$a['id'];$b=$service->register('BT',$site['id'],'qa_document',$key+1,'draft',date('Y-m-d H:i:s'),$admin);$ids[]=$b['id'];
 doc_ok($a['document_number']!==$b['document_number'],'Numéros uniques successifs');doc_ok(preg_match('#^BT/MINO/'.date('Y').'/\d{6}$#',$a['document_number'])===1,'Format configurable appliqué');
 $again=$service->register('BT',$site['id'],'qa_document',$key,'draft',date('Y-m-d H:i:s'),$admin);doc_ok((int)$again['id']===(int)$a['id'],'Enregistrement métier idempotent');
 $history=$db->prepare('SELECT COUNT(*) FROM document_status_history WHERE document_id IN (?,?)');$history->execute($ids);doc_ok((int)$history->fetchColumn()===2,'Historique initial créé');
 $pdf=(new PdfService())->output('Test document DAGRIL','<section class="sheet"><h2>'.$a['document_number'].'</h2></section>','portrait');doc_ok(substr($pdf,0,4)==='%PDF','Dompdf génère un PDF valide');
 Auth::selectSite('all');$weighingId=$db->query("SELECT id FROM weighings WHERE status='validated' AND deleted_at IS NULL LIMIT 1")->fetchColumn();if($weighingId){$weighing=(new Weighing())->findDetailed($weighingId);$pdfMode=true;$title='Ticket de pesée';ob_start();require dirname(__DIR__).'/app/views/weighings/ticket.php';$html=ob_get_clean();doc_ok(substr((new PdfService())->output($title,$html,'portrait'),0,4)==='%PDF','Ticket de pesée historique toujours générable');}
 $distributionId=$db->query("SELECT id FROM distributions WHERE deleted_at IS NULL LIMIT 1")->fetchColumn();if($distributionId){$distribution=(new Distribution())->findDetailed($distributionId);$pdfMode=true;$title='Bon de sortie';ob_start();require dirname(__DIR__).'/app/views/distributions/print.php';$html=ob_get_clean();doc_ok(substr((new PdfService())->output($title,$html,'portrait'),0,4)==='%PDF','Bon de sortie historique toujours générable');}
 $types=(int)$db->query('SELECT COUNT(*) FROM document_types WHERE deleted_at IS NULL')->fetchColumn();doc_ok($types===16,'Seize types documentaires disponibles');echo"Tous les tests documentaires sont conformes.\n";
}finally{if($ids){$p=implode(',',array_fill(0,count($ids),'?'));$s=$db->prepare("SELECT id FROM workflow_instances WHERE document_id IN ({$p})");$s->execute($ids);$workflowIds=$s->fetchAll(PDO::FETCH_COLUMN);if($workflowIds){$q=implode(',',array_fill(0,count($workflowIds),'?'));foreach(['workflow_notifications','workflow_level_approvals','workflow_transitions']as$table){$s=$db->prepare("DELETE FROM {$table} WHERE workflow_instance_id IN ({$q})");$s->execute($workflowIds);}$s=$db->prepare("DELETE FROM workflow_instances WHERE id IN ({$q})");$s->execute($workflowIds);}$s=$db->prepare("DELETE FROM document_status_history WHERE document_id IN ({$p})");$s->execute($ids);$s=$db->prepare("DELETE FROM documents WHERE id IN ({$p})");$s->execute($ids);}Auth::logout();$out=ob_get_clean();echo$out;}
