<?php
require dirname(__DIR__).'/app/helpers/functions.php';require dirname(__DIR__).'/app/core/Database.php';require dirname(__DIR__).'/app/core/Model.php';require dirname(__DIR__).'/app/core/Auth.php';require dirname(__DIR__).'/app/models/Agriculture.php';
ob_start();Auth::start();$_SERVER['HTTP_USER_AGENT']='AgricultureTest';$db=Database::getInstance()->connection();$fail=[];$x=[];
function agq($d,$s,$p=[]){$q=$d->prepare($s);$q->execute($p);return$q;}function agok($c,$m){global$fail;echo($c?'OK  - ':'FAIL - ').$m."\n";if(!$c)$fail[]=$m;}function agdocs($db,$entity,$id){$docs=agq($db,'SELECT id FROM documents WHERE entity_type=? AND entity_id=?',[$entity,$id])->fetchAll(PDO::FETCH_COLUMN);foreach($docs as$d){$wis=agq($db,'SELECT id FROM workflow_instances WHERE document_id=?',[$d])->fetchAll(PDO::FETCH_COLUMN);foreach($wis as$wi){foreach(['workflow_notifications','workflow_level_approvals','workflow_transitions']as$t)agq($db,"DELETE FROM $t WHERE workflow_instance_id=?",[$wi]);agq($db,'DELETE FROM workflow_instances WHERE id=?',[$wi]);}agq($db,'DELETE FROM document_status_history WHERE document_id=?',[$d]);agq($db,'DELETE FROM documents WHERE id=?',[$d]);}}
try{
 $users=agq($db,"SELECT u.*,r.name role_name,r.slug role_slug FROM users u JOIN roles r ON r.id=u.role_id WHERE u.status='active' AND u.deleted_at IS NULL AND r.slug IN('administrateur','direction') LIMIT 2")->fetchAll();if(count($users)<2)throw new RuntimeException('Deux utilisateurs requis.');$creator=$users[0];$validator=$users[1];$mut=(int)agq($db,"SELECT id FROM sites WHERE code='FARM-MUT'")->fetchColumn();$dik=(int)agq($db,"SELECT id FROM sites WHERE code='FARM-DIK'")->fetchColumn();$season=(int)agq($db,'SELECT id FROM agricultural_seasons LIMIT 1')->fetchColumn();$variety=(int)agq($db,'SELECT id FROM agricultural_varieties LIMIT 1')->fetchColumn();$input=(int)agq($db,'SELECT id FROM agricultural_inputs LIMIT 1')->fetchColumn();
 Auth::login($creator);Auth::selectSite((string)$mut);$creator=Auth::user();$m=new Agriculture();$suffix=random_int(10000,99999);$campaign=$m->createCampaign(['season_id'=>$season,'code'=>'TST-AG-'.$suffix,'name'=>'Campagne test','start_date'=>date('Y-m-d'),'end_date'=>date('Y-m-d',strtotime('+5 months'))],$creator);$x['campaign']=$campaign;$plot=$m->createPlot(['code'=>'TST-P-'.$suffix,'name'=>'Parcelle test','total_area_ha'=>20]);$x['plot']=$plot;$cp=$m->planPlot(['campaign_id'=>$campaign,'plot_id'=>$plot,'variety_id'=>$variety,'planned_area_ha'=>12,'actual_area_ha'=>10,'target_tons_per_ha'=>4]);$x['cp']=$cp;$allocation=$m->allocateInput(['campaign_plot_id'=>$cp,'input_id'=>$input,'planned_quantity'=>100,'actual_quantity'=>90,'unit_cost'=>2,'applied_at'=>date('Y-m-d H:i:s')],$creator);$x['allocation']=$allocation;agok((int)agq($db,'SELECT COUNT(*) FROM agricultural_input_allocations ia JOIN agricultural_campaign_plots cp ON cp.id=ia.campaign_plot_id WHERE ia.id=? AND cp.campaign_id=?',[$allocation,$campaign])->fetchColumn()===1,'Intrant imputé à la campagne et à la parcelle');
 $harvest=$m->createHarvest(['campaign_plot_id'=>$cp,'harvested_at'=>date('Y-m-d H:i:s'),'gross_weight_kg'=>42000,'tare_weight_kg'=>1000,'drying_loss_kg'=>1000,'moisture_before'=>18,'moisture_after'=>13,'drying_started_at'=>date('Y-m-d H:i:s'),'drying_ended_at'=>date('Y-m-d H:i:s')],$creator);$x['harvest']=$harvest;agok((float)agq($db,'SELECT yield_tons_per_ha FROM agricultural_harvests WHERE id=?',[$harvest])->fetchColumn()===4.0,'Rendement calculé sur les 10 ha réellement exploités');try{$m->validateHarvest($harvest,$creator);$blocked=false;}catch(Exception$e){$blocked=true;}agok($blocked,'Créateur empêché de valider sa récolte');
 Auth::login($validator);Auth::selectSite((string)$mut);$validator=Auth::user();$stock=$m->validateHarvest($harvest,$validator);$x['stock']=$stock;agok((float)agq($db,'SELECT physical_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn()===40000.0,'Validation crée une seule entrée de stock agricole');try{$m->validateHarvest($harvest,$validator);$double=false;}catch(Exception$e){$double=true;}agok($double&&(int)agq($db,'SELECT COUNT(*) FROM agricultural_stocks WHERE harvest_id=?',[$harvest])->fetchColumn()===1,'Double validation de récolte refusée');
 Auth::login($creator);Auth::selectSite((string)$mut);$creator=Auth::user();$transport=$m->createTransport(['stock_id'=>$stock,'quantity_kg'=>40000,'truck_plate'=>'TST-AG-01','driver_name'=>'Chauffeur test','route_description'=>'MUTALA - Minoterie'],$creator);$x['transport']=$transport;agok((float)agq($db,'SELECT reserved_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn()===0.0,'BT brouillon sans effet stock');try{$m->createTransport(['stock_id'=>$stock,'quantity_kg'=>1,'truck_plate'=>'X','driver_name'=>'X'],$creator);$duplicate=false;}catch(Exception$e){$duplicate=true;}agok($duplicate,'Une récolte ne peut pas être affectée à deux BT');
 Auth::login($validator);Auth::selectSite((string)$mut);$validator=Auth::user();$m->approveTransport($transport,$validator);agok((float)agq($db,'SELECT reserved_quantity_kg FROM agricultural_stocks WHERE id=?',[$stock])->fetchColumn()===40000.0,'Validation BT réserve le stock');$m->dispatchTransport($transport,$validator);$s=agq($db,'SELECT * FROM agricultural_stocks WHERE id=?',[$stock])->fetch();agok((float)$s['physical_quantity_kg']===0.0&&(float)$s['reserved_quantity_kg']===0.0,'Expédition sort le physique et solde la réservation');try{$m->dispatchTransport($transport,$validator);$twice=false;}catch(Exception$e){$twice=true;}agok($twice&&(int)agq($db,"SELECT COUNT(*) FROM agricultural_stock_movements WHERE stock_id=? AND movement_type='transport_out'",[$stock])->fetchColumn()===1,'Double expédition refusée');
 Auth::selectSite((string)$dik);agok(count($m->harvests())===0,'Isolation MUTALA/DIKAPA appliquée côté serveur');Auth::selectSite('all');$rows=$m->campaigns();$found=false;foreach($rows as$r)if((int)$r['id']===$campaign&&abs((float)$r['realized_tons']-40)<0.001)$found=true;agok($found,'Direction voit objectif et réalisé consolidés');
}catch(Exception$e){echo'ERREUR - '.$e->getMessage()."\n";$fail[]=$e->getMessage();}
finally{if(!empty($x['transport'])){agdocs($db,'agricultural_transports',$x['transport']);agq($db,'DELETE FROM agricultural_stock_movements WHERE stock_id=?',[$x['stock']]);agq($db,'DELETE FROM agricultural_transports WHERE id=?',[$x['transport']]);}if(!empty($x['stock']))agq($db,'DELETE FROM agricultural_stocks WHERE id=?',[$x['stock']]);if(!empty($x['harvest']))agq($db,'DELETE FROM agricultural_harvests WHERE id=?',[$x['harvest']]);if(!empty($x['allocation']))agq($db,'DELETE FROM agricultural_input_allocations WHERE id=?',[$x['allocation']]);if(!empty($x['cp']))agq($db,'DELETE FROM agricultural_campaign_plots WHERE id=?',[$x['cp']]);if(!empty($x['plot']))agq($db,'DELETE FROM agricultural_plots WHERE id=?',[$x['plot']]);if(!empty($x['campaign']))agq($db,'DELETE FROM agricultural_campaigns WHERE id=?',[$x['campaign']]);agq($db,"DELETE FROM activity_logs WHERE user_agent='AgricultureTest'");}
ob_end_flush();if($fail)exit(1);echo"\nGestion agricole conforme.\n";
