<section class="page-heading"><div><p class="page-kicker">Administration</p><h2>RBAC granulaire</h2><p>Utilisateur → rôle → site → composant → action.</p></div></section>
<?php if ($success): ?><div class="alert success"><?= e($success) ?></div><?php endif; ?>
<?php if ($error): ?><div class="alert danger"><?= e($error) ?></div><?php endif; ?>

<section class="table-panel"><div class="panel-heading"><div><h3>Nouvelle attribution</h3><p>Les rôles sensibles attendent une seconde approbation. Une délégation exige une expiration.</p></div></div>
<form method="post" action="<?= e(base_url('access-control/assignments')) ?>" class="enterprise-form"><?= csrf_field() ?><div class="form-grid">
<label><span>Utilisateur</span><select name="user_id" required><option value="">Choisir</option><?php foreach($users as $u): ?><option value="<?= e($u['id']) ?>"><?= e($u['name'].' — '.$u['email']) ?></option><?php endforeach; ?></select></label>
<label><span>Rôle</span><select name="role_id" required><option value="">Choisir</option><?php foreach($roles as $r): ?><option value="<?= e($r['id']) ?>"><?= e($r['name'].($r['is_sensitive']?' (sensible)':'')) ?></option><?php endforeach; ?></select></label>
<label><span>Site</span><select name="site_id"><option value="">Global</option><?php foreach($sites as $s): ?><option value="<?= e($s['id']) ?>"><?= e($s['code'].' — '.$s['name']) ?></option><?php endforeach; ?></select></label>
<label><span>Nature</span><select name="assignment_type"><option value="direct">Directe</option><option value="delegation">Délégation temporaire</option></select></label>
<label><span>Début</span><input type="datetime-local" name="starts_at"></label><label><span>Expiration</span><input type="datetime-local" name="expires_at"></label>
<label><span>Motif</span><input name="reason" maxlength="255"></label><div class="form-actions"><button class="btn-primary">Attribuer</button></div></div></form></section>

<section class="table-panel"><div class="panel-heading"><div><h3>Attributions</h3></div></div><div class="table-responsive"><table><thead><tr><th>Utilisateur</th><th>Rôle</th><th>Site</th><th>Période</th><th>Nature</th><th>Statut</th><th>Actions</th></tr></thead><tbody><?php foreach($assignments as $a): ?><tr><td><?= e($a['user_name']) ?></td><td><?= e($a['role_name']) ?><?= $a['is_sensitive']?' ⚠':'' ?></td><td><?= e($a['site_code']?:'Global') ?></td><td><?= e($a['starts_at']) ?><br><small><?= e($a['expires_at']?:'Sans expiration') ?></small></td><td><?= e($a['assignment_type']) ?></td><td><span class="status-badge status-<?= e($a['approval_status']==='approved'?'active':'pending') ?>"><?= e($a['approval_status']) ?></span></td><td><div class="table-actions"><?php if($a['approval_status']==='pending'): ?><form method="post" action="<?= e(base_url('access-control/assignments/'.$a['id'].'/approve')) ?>"><?= csrf_field() ?><button class="icon-button" title="Approuver">✓</button></form><form method="post" action="<?= e(base_url('access-control/assignments/'.$a['id'].'/reject')) ?>"><?= csrf_field() ?><button class="icon-button" title="Rejeter">×</button></form><?php elseif($a['approval_status']==='approved'): ?><form method="post" action="<?= e(base_url('access-control/assignments/'.$a['id'].'/revoke')) ?>"><?= csrf_field() ?><button class="icon-button" title="Révoquer">×</button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div></section>

<section class="table-panel"><div class="panel-heading"><div><h3>Matrice rôle-permissions</h3><p>Chaque modification est journalisée.</p></div></div><?php foreach($roles as $r): ?><details style="padding:1rem;border-bottom:1px solid #d9e1ea"><summary><strong><?= e($r['name']) ?></strong></summary><form method="post" action="<?= e(base_url('access-control/roles/'.$r['id'].'/permissions')) ?>" class="enterprise-form"><?= csrf_field() ?><div class="form-grid"><?php foreach($permissions as $p): $ids=array_map('intval',array_filter(explode(',',(string)$p['role_ids']))); ?><label style="display:flex;gap:.5rem;align-items:center"><input type="checkbox" name="permission_ids[]" value="<?= e($p['id']) ?>" <?= in_array((int)$r['id'],$ids,true)?'checked':'' ?>> <span><?= e($p['component'].'.'.$p['action']) ?></span></label><?php endforeach; ?></div><div class="form-actions"><button class="btn-primary">Enregistrer la matrice</button></div></form></details><?php endforeach; ?></section>
