<?php
$openMissions=array_values(array_filter($dashboard['missions'],static function($r){return in_array($r['status'],['approved','in_progress','completed','justification_pending'],true);}));
$metricTables=[
 'missions'=>['Missions non soldées',$dashboard['kpis']['unsettled'],$openMissions,['mission_number'=>'Mission','asset_code'=>'Actif','person_name'=>'Responsable','planned_start'=>'Départ prévu','status'=>'Statut']],
 'distributions'=>['Distributions · 100 dernières',count($dashboard['distributions']),$dashboard['distributions'],['distribution_number'=>'Référence','site_code'=>'Site','fuel_code'=>'Carburant','asset_code'=>'Actif','person_name'=>'Responsable','quantity'=>'Litres','distributed_at'=>'Date']],
 'stocks'=>['Stocks carburant',count($dashboard['stocks']),$dashboard['stocks'],['site_code'=>'Site','fuel_code'=>'Carburant','physical_quantity'=>'Physique (L)','reserved_quantity'=>'Réservé (L)','available_quantity'=>'Disponible (L)']]
];
?>
<div class="butchery-metrics"><?php foreach($metricTables as $key=>$metric):?><button type="button" class="butchery-kpi" data-workspace-modal-open="fuel-kpi-<?=e($key)?>"><strong><?=e($metric[1])?></strong><span><?=e($metric[0])?></span><i class="bi bi-chevron-right" aria-hidden="true"></i></button><?php endforeach;?></div>
<?php foreach($metricTables as $key=>$metric):ob_start();?>
<section id="fuel-kpi-<?=e($key)?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="fuel-kpi-title-<?=e($key)?>"><header><h2 id="fuel-kpi-title-<?=e($key)?>"><?=e($metric[0])?></h2><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header><div class="feed-form-body"><?php if(!$metric[2]):?><p class="butchery-empty">Aucune donnée dans cette sélection.</p><?php else:?><table class="enterprise-table"><thead><tr><?php foreach($metric[3] as $label):?><th><?=e($label)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($metric[2] as $row):?><tr><?php foreach($metric[3] as $field=>$label):?><td><?php if($field==='status'):?><?=e($fuelLabels[$row[$field]]??$row[$field])?><?php elseif($field==='available_quantity'):?><?=e(number_format(max(0,$row['physical_quantity']-$row['reserved_quantity']),3,',',' '))?><?php else:?><?=e($row[$field])?><?php endif;?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table><?php endif;?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer></section>
<?php $fuelModals[]=ob_get_clean();endforeach;?>
