<?php
class TransferController extends Controller
{
 public function index(){$this->view('transfers.index',['title'=>'Transferts inter-sites','transfers'=>$this->model('Transfer')->allDetailed(),'success'=>flash('success'),'error'=>flash('error')],'layouts.main');}
 public function create(){$this->view('transfers.create',array_merge(['title'=>'Nouvelle demande de transfert','errors'=>flash('errors')?:[]],$this->model('Transfer')->references()),'layouts.main');}
 public function store(){$this->csrf();try{$id=$this->service()->create(['transfer_type'=>$_POST['transfer_type']??'inter_site','source_site_id'=>(int)($_POST['source_site_id']??0),'destination_site_id'=>(int)($_POST['destination_site_id']??0),'notes'=>trim($_POST['notes']??''),'items'=>[['finished_stock_id'=>(int)($_POST['finished_stock_id']??0),'quantity_bags'=>(int)($_POST['quantity_bags']??0)]]],Auth::user());flash('success','Demande créée.');redirect('transfers/'.$id);}catch(Exception$e){flash('error',$e->getMessage());redirect('transfers/create');}}
 public function show($id){$t=$this->model('Transfer')->findDetailed((int)$id);if(!$t){http_response_code(404);echo'Transfert introuvable.';return;}$this->view('transfers.show',['title'=>$t['transfer_number'],'transfer'=>$t,'success'=>flash('success'),'error'=>flash('error')],'layouts.main');}
 public function submit($id){$this->act($id,'submit');}public function approve($id){$this->act($id,'approve');}public function reserve($id){$this->act($id,'reserve');}public function close($id){$this->act($id,'close');}
 public function ship($id){$this->csrf();$q=[];foreach($_POST['quantity_bags']??[]as$k=>$v){$q[(int)$k]=(int)$v;}try{$this->service()->ship((int)$id,$q,Auth::user(),trim($_POST['vehicle_reference']??''));flash('success','Expédition enregistrée.');}catch(Exception$e){flash('error',$e->getMessage());}redirect('transfers/'.$id);}
 public function receive($id){$this->csrf();$lines=[];foreach($_POST['accepted_bags']??[]as$k=>$v){$lines[(int)$k]=['accepted_bags'=>(int)$v,'rejected_bags'=>(int)($_POST['rejected_bags'][$k]??0),'quality_notes'=>trim($_POST['quality_notes'][$k]??'')];}try{$this->service()->receive((int)$_POST['shipment_id'],hash('sha256',trim($_POST['idempotency_key']??'')),$lines,Auth::user(),trim($_POST['notes']??''));flash('success','Réception enregistrée.');}catch(Exception$e){flash('error',$e->getMessage());}redirect('transfers/'.$id);}
 public function dispatchReturn($id,$returnId){$this->csrf();try{$this->service()->dispatchReturn((int)$returnId,Auth::user());flash('success','Retour expédié.');}catch(Exception$e){flash('error',$e->getMessage());}redirect('transfers/'.$id);}public function receiveReturn($id,$returnId){$this->csrf();try{$this->service()->receiveReturn((int)$returnId,Auth::user());flash('success','Retour reçu au site source.');}catch(Exception$e){flash('error',$e->getMessage());}redirect('transfers/'.$id);}
 private function act($id,$action){$this->csrf();try{$this->service()->{$action}((int)$id,Auth::user());flash('success','Action enregistrée.');}catch(Exception$e){flash('error',$e->getMessage());}redirect('transfers/'.$id);}private function service(){require_once dirname(__DIR__).'/services/TransferService.php';return new TransferService();}private function csrf(){if(!verify_csrf($_POST['_token']??'')){throw new RuntimeException('Jeton CSRF invalide.');}}
}
