<?php if($canUpdate&&$source&&in_array($t['status'],['reserved','partially_shipped'],true)):
ob_start();?>
<form method="post" action="<?=e(base_url('transfers/'.$t['id'].'/ship'))?>" data-transfer-operation="ship" data-native-submit><?=csrf_field()?>
<div class="feed-form-body"><p data-transfer-error class="app-alert app-alert-error" role="alert" hidden></p><p class="butchery-detail-note"><?=e($t['source_code'].' → '.$t['destination_code'])?> · Quantités en sacs</p><label>Véhicule <small>facultatif</small><input name="vehicle_reference" maxlength="100" placeholder="Immatriculation"></label><div class="table-responsive"><table class="enterprise-table" data-datatable="false"><thead><tr><th>Produit / format</th><th>Restants</th><th>À expédier</th></tr></thead><tbody><?php foreach($t['items'] as $item):$left=max(0,$item['reserved_bags']-$item['shipped_bags']);if(!$left)continue;?><tr><td><?=e($item['product_name'])?><small><?=e($item['format_name'])?></small></td><td><?=$left?></td><td><input type="number" min="0" max="<?=$left?>" step="1" value="0" name="quantity_bags[<?=e($item['id'])?>]" aria-label="<?=e('Sacs à expédier : '.$item['product_name'])?>"></td></tr><?php endforeach;?></tbody></table></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Confirmer l’expédition</button></footer></form>
<?php $modal('transfer-ship','Expédier le transfert',ob_get_clean());endif;?>
<?php foreach($t['shipments'] as $shipment):if(!$canUpdate||!$destination||!in_array($shipment['status'],['dispatched','partially_received'],true))continue;ob_start();?>
<form method="post" action="<?=e(base_url('transfers/'.$t['id'].'/receive'))?>" data-transfer-operation="receive" data-native-submit><?=csrf_field()?>
<input type="hidden" name="shipment_id" value="<?=e($shipment['id'])?>"><input type="hidden" name="idempotency_key" value="<?=e(bin2hex(random_bytes(16)))?>">
<div class="feed-form-body"><p data-transfer-error class="app-alert app-alert-error" role="alert" hidden></p><p class="butchery-detail-note"><?=e($shipment['shipment_number'])?> · Quantités en sacs</p><div class="table-responsive"><table class="enterprise-table" data-datatable="false"><thead><tr><th>Produit / format</th><th>Restants</th><th>Acceptés</th><th>Refusés</th><th>Note qualité</th></tr></thead><tbody><?php foreach($shipment['items'] as $item):$left=max(0,$item['quantity_bags']-$item['received_bags']);if(!$left)continue;?><tr data-receive-left="<?=$left?>"><td><?=e($item['product_name'])?><small><?=e($item['format_name'])?></small></td><td><?=$left?></td><td><input type="number" min="0" max="<?=$left?>" step="1" value="0" name="accepted_bags[<?=e($item['id'])?>]" data-accepted aria-label="<?=e('Sacs acceptés : '.$item['product_name'])?>"></td><td><input type="number" min="0" max="<?=$left?>" step="1" value="0" name="rejected_bags[<?=e($item['id'])?>]" data-rejected aria-label="<?=e('Sacs refusés : '.$item['product_name'])?>"></td><td><input name="quality_notes[<?=e($item['id'])?>]" maxlength="500" placeholder="Facultatif" aria-label="<?=e('Note qualité : '.$item['product_name'])?>"></td></tr><?php endforeach;?></tbody></table></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Annuler</button><button type="submit" class="btn-primary">Enregistrer la réception</button></footer></form>
<?php $modal('transfer-receive-'.$shipment['id'],'Réceptionner l’expédition',ob_get_clean());endforeach;?>
