<?php
require __DIR__.'/labels.php';
$t=$transfer;$date=static function($v){return $v?date('d/m/Y H:i',strtotime($v)):'—';};
$sum=[];foreach(['requested_bags','reserved_bags','shipped_bags','received_bags','accepted_bags','rejected_bags'] as $field)$sum[$field]=array_sum(array_column($t['items'],$field));
$source=Auth::canAccessSite($t['source_site_id']);$destination=Auth::canAccessSite($t['destination_site_id']);
$canUpdate=Auth::can('transfers','update');$modals=[];
$modal=static function($id,$title,$body)use(&$modals){ob_start();?>
<section id="<?=e($id)?>" class="entity-modal workspace-entity-modal feed-editor livestock-editor conversion-editor butchery-editor butchery-kpi-modal" role="dialog" aria-modal="true" aria-hidden="true" aria-labelledby="<?=e($id)?>-title"><header><h2 id="<?=e($id)?>-title"><?=e($title)?></h2><button type="button" class="modal-close" data-workspace-modal-close aria-label="Fermer">×</button></header><?=$body?></section>
<?php $modals[]=ob_get_clean();};
$shipmentLabels=['draft'=>'Brouillon','dispatched'=>'Expédiée','partially_received'=>'Réception partielle','received'=>'Reçue','return_pending'=>'Retour à traiter','returned'=>'Retournée'];
$returnLabels=['planned'=>'À expédier','dispatched'=>'En transit','received'=>'Reçu au départ','closed'=>'Clôturé'];
?>
<div class="butchery-workspace transfer-workspace transfer-dossier">
<header class="butchery-heading"><a class="icon-button" href="<?=e(base_url('transfers'))?>" aria-label="Retour aux transferts"><i class="bi bi-arrow-left"></i></a><div><p><?=$t['transfer_type']==='internal'?'Transfert interne':'Transfert inter-site'?></p><h2><?=e($t['transfer_number'])?></h2></div><span class="butchery-status"><?=e($transferLabels[$t['status']]??$t['status'])?></span></header>
<?php if($success):?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?>
<section class="form-panel butchery-slaughter-actions"><div class="butchery-slaughter-toolbar"><h3><?=e($t['source_code'].' → '.$t['destination_code'])?></h3><button type="button" class="btn-secondary" data-workspace-modal-open="transfer-info">Informations</button>
<?php foreach(['draft'=>['submit','Soumettre','create'],'submitted'=>['approve','Valider et réserver','validate'],'approved'=>['reserve','Réserver','validate']] as $state=>$action):if($t['status']===$state&&$source&&Auth::can('transfers',$action[2])):?>
<form method="post" action="<?=e(base_url('transfers/'.$t['id'].'/'.$action[0]))?>" data-confirm="<?=e($action[1].' ce transfert ?')?>"><?=csrf_field()?><button class="btn-primary"><?=e($action[1])?></button></form>
<?php endif;endforeach;?>
<?php if($canUpdate&&$source&&in_array($t['status'],['reserved','partially_shipped'],true)):?><button type="button" class="btn-primary" data-workspace-modal-open="transfer-ship">Expédier</button><?php endif;?>
<?php if($canUpdate&&$source&&in_array($t['status'],['accepted','partially_accepted','returned'],true)&&$sum['shipped_bags']==$sum['received_bags']&&!array_filter($t['returns'],static function($r){return $r['status']!=='received';})):?><form method="post" action="<?=e(base_url('transfers/'.$t['id'].'/close'))?>" data-confirm="Clôturer le transfert et libérer les réservations restantes ?"><?=csrf_field()?><button class="btn-secondary">Clôturer</button></form><?php endif;?>
</div></section>
<div class="butchery-metrics"><?php foreach([['Demandés',$sum['requested_bags'],'requested_bags'],['En transit',max(0,$sum['shipped_bags']-$sum['received_bags']),'transit'],['Acceptés',$sum['accepted_bags'],'accepted_bags'],['Refusés',$sum['rejected_bags'],'rejected_bags']] as $metric):?><button type="button" class="butchery-kpi" data-workspace-modal-open="transfer-quantities-<?=e($metric[2])?>"><strong><?=e(number_format($metric[1],0,',',' '))?></strong><span><?=e($metric[0])?> · sacs</span><i class="bi bi-chevron-right" aria-hidden="true"></i></button><?php ob_start();?><div class="feed-form-body"><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Produit / format</th><th>Sacs</th></tr></thead><tbody><?php foreach($t['items'] as $item):$quantity=$metric[2]==='transit'?max(0,$item['shipped_bags']-$item['received_bags']):$item[$metric[2]];?><tr><td><?=e($item['product_name'].' · '.$item['format_name'])?></td><td><?=e($quantity)?></td></tr><?php endforeach;?></tbody></table></div></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer><?php $modal('transfer-quantities-'.$metric[2],$metric[0].' · sacs',ob_get_clean());endforeach;?></div>
<section class="table-panel butchery-history"><header class="butchery-history-heading"><h3>Produits et quantités <small>en sacs</small></h3></header><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Produit / format</th><th>Demandés</th><th>À expédier</th><th>Expédiés</th><th>Reçus</th><th>Acceptés</th><th>Refusés</th></tr></thead><tbody><?php foreach($t['items'] as $item):?><tr><td><strong><?=e($item['product_name'])?></strong><small><?=e($item['format_name'])?> · Lot #<?=e($item['source_finished_stock_id'])?></small></td><td><?=e($item['requested_bags'])?></td><td><?=e($t['status']==='closed'?0:max(0,$item['reserved_bags']-$item['shipped_bags']))?></td><?php foreach(['shipped_bags','received_bags','accepted_bags','rejected_bags'] as $key):?><td><?=e($item[$key])?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section>
<section class="table-panel butchery-history"><header class="butchery-history-heading"><h3>Expéditions</h3><span class="butchery-status"><?=count($t['shipments'])?></span></header><?php if(!$t['shipments']):?><p class="butchery-empty">Aucune expédition enregistrée.</p><?php else:?><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Référence / départ</th><th>Véhicule</th><th>Expédiés</th><th>À recevoir</th><th>Statut</th><th>Action</th></tr></thead><tbody><?php foreach($t['shipments'] as $shipment):?><tr><td><strong><?=e($shipment['shipment_number'])?></strong><small><?=e($date($shipment['dispatched_at']))?></small></td><td><?=e($shipment['vehicle_reference']?:'—')?></td><td><?=array_sum(array_column($shipment['items'],'quantity_bags'))?></td><td><?=array_sum(array_column($shipment['items'],'quantity_bags'))-array_sum(array_column($shipment['items'],'received_bags'))?></td><td><?=e($shipmentLabels[$shipment['status']]??$shipment['status'])?></td><td><?php if($canUpdate&&$destination&&in_array($shipment['status'],['dispatched','partially_received'],true)):?><button type="button" class="btn-primary" data-workspace-modal-open="transfer-receive-<?=e($shipment['id'])?>">Réceptionner</button><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php if($t['returns']):?><section class="table-panel butchery-history"><header class="butchery-history-heading"><h3>Retours</h3></header><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Référence</th><th>Prévu le</th><th>Expédié le</th><th>Reçu le</th><th>Statut</th><th>Action</th></tr></thead><tbody><?php foreach($t['returns'] as $r):?><tr><td><?=e($r['return_number'])?></td><?php foreach(['planned_at','dispatched_at','received_at'] as $key):?><td><?=e($date($r[$key]))?></td><?php endforeach;?><td><?=e($returnLabels[$r['status']]??$r['status'])?></td><td><?php if($canUpdate&&(($r['status']==='planned'&&$destination)||($r['status']==='dispatched'&&$source))):?><form method="post" action="<?=e(base_url('transfers/'.$t['id'].'/returns/'.$r['id'].'/'.($r['status']==='planned'?'dispatch':'receive')))?>" data-confirm="Confirmer cette opération de retour ?"><?=csrf_field()?><button class="btn-secondary"><?=$r['status']==='planned'?'Expédier le retour':'Recevoir au départ'?></button></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<?php if($t['non_conformities']):?><section class="table-panel butchery-history"><header class="butchery-history-heading"><h3>Écarts de réception</h3></header><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Référence</th><th>Attendus</th><th>Reçus</th><th>Refusés</th><th>Motif</th><th>Statut</th></tr></thead><tbody><?php foreach($t['non_conformities'] as $nc):?><tr><td><?=e($nc['reference'])?></td><td><?=e($nc['expected_bags'])?></td><td><?=e($nc['received_bags'])?></td><td><?=e($nc['rejected_bags'])?></td><td><?=e($nc['description'])?></td><td><?=e(['open'=>'Ouvert','resolved'=>'Résolu','closed'=>'Clôturé'][$nc['status']]??$nc['status'])?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
<section class="table-panel butchery-history"><header class="butchery-history-heading"><h3>Historique des opérations</h3></header><?php if(!$t['history']):?><p class="butchery-empty">Aucune opération enregistrée.</p><?php else:?><div class="table-responsive"><table class="enterprise-table"><thead><tr><th>Date</th><th>Opération</th><th>Statut obtenu</th><th>Effectuée par</th><th>Note</th></tr></thead><tbody><?php foreach($t['history'] as $h):?><tr><td data-order="<?=e(strtotime($h['created_at']))?>"><?=e($date($h['created_at']))?></td><td><?=e(['create'=>'Création','submit'=>'Soumission','approve_and_reserve'=>'Validation et réservation','approve'=>'Validation','reserve'=>'Réservation','ship'=>'Expédition','receive'=>'Réception','return_dispatch'=>'Expédition du retour','return_receive'=>'Réception du retour','close'=>'Clôture'][$h['action']]??$h['action'])?></td><td><?=e($transferLabels[$h['new_status']]??$h['new_status'])?></td><td><?=e($h['actor_name'])?></td><td><?=e($h['reason']?:'—')?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<?php
ob_start();?><div class="feed-form-body"><dl class="butchery-history-details"><?php foreach(['Départ'=>$t['source_code'].' · '.$t['source_name'],'Destination'=>$t['destination_code'].' · '.$t['destination_name'],'Demandé le'=>$date($t['requested_at']),'Créé par'=>$t['creator_name'],'Soumis le'=>$date($t['submitted_at']),'Approuvé par'=>$t['approver_name']?:'—','Approuvé le'=>$date($t['approved_at']),'Clôturé le'=>$date($t['closed_at'])] as $label=>$value):?><div><dt><?=e($label)?></dt><dd><?=e($value)?></dd></div><?php endforeach;?></dl><?php if($t['notes']):?><div class="transfer-notes"><strong>Notes</strong><p><?=nl2br(e($t['notes']))?></p></div><?php endif;?></div><footer><button type="button" class="btn-secondary" data-workspace-modal-close>Fermer</button></footer><?php $modal('transfer-info','Informations du transfert',ob_get_clean());
require __DIR__.'/operation_modals.php';
echo implode('',$modals);
?>
</div>
