<?php

class Document extends Model
{
    protected $table='documents';
    public function allDetailed(){ $params=[];$scope=Auth::siteClause('d.site_id',$params);return $this->query("SELECT d.*,dt.display_code,dt.name type_name,s.code site_code,u.name creator_name,v.name validator_name,(SELECT COUNT(*) FROM document_attachments da WHERE da.document_id=d.id AND da.deleted_at IS NULL) attachment_count FROM documents d INNER JOIN document_types dt ON dt.id=d.document_type_id INNER JOIN sites s ON s.id=d.site_id LEFT JOIN users u ON u.id=d.created_by LEFT JOIN users v ON v.id=d.validated_by WHERE d.deleted_at IS NULL{$scope} ORDER BY d.document_date DESC,d.id DESC",$params)->fetchAll();}
    public function findDetailed($id){$params=['id'=>$id];$scope=Auth::siteClause('d.site_id',$params);$doc=$this->query("SELECT d.*,dt.display_code,dt.name type_name,s.code site_code,s.name site_name,u.name creator_name,v.name validator_name,wi.id workflow_instance_id,wi.current_state workflow_state,wi.current_level,wi.required_levels,wi.amount workflow_amount FROM documents d INNER JOIN document_types dt ON dt.id=d.document_type_id INNER JOIN sites s ON s.id=d.site_id LEFT JOIN users u ON u.id=d.created_by LEFT JOIN users v ON v.id=d.validated_by LEFT JOIN workflow_instances wi ON wi.document_id=d.id WHERE d.id=:id AND d.deleted_at IS NULL{$scope} LIMIT 1",$params)->fetch();if(!$doc){return null;}$doc['attachments']=$this->query('SELECT da.*,u.name uploader_name FROM document_attachments da LEFT JOIN users u ON u.id=da.uploaded_by WHERE da.document_id=:id AND da.deleted_at IS NULL ORDER BY da.created_at DESC',['id'=>$id])->fetchAll();$doc['history']=$this->query('SELECT wt.*,u.name actor_name FROM workflow_transitions wt LEFT JOIN users u ON u.id=wt.actor_id WHERE wt.workflow_instance_id=:id ORDER BY wt.transitioned_at DESC,wt.id DESC',['id'=>$doc['workflow_instance_id']])->fetchAll();return $doc;}
    public function attach($id,array $file,array $user){$doc=$this->findDetailed($id);if(!$doc){throw new RuntimeException('Document introuvable.');}if(($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK){throw new RuntimeException('Pièce jointe invalide.');}if(($file['size']??0)>10*1024*1024){throw new RuntimeException('La pièce jointe dépasse 10 Mo.');}$allowed=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);if(!isset($allowed[$mime])){throw new RuntimeException('Format autorisé: PDF, JPG ou PNG.');}$relative='documents/'.$doc['site_code'].'/'.date('Y').'/'.bin2hex(random_bytes(16)).'.'.$allowed[$mime];$base=dirname(__DIR__,2).'/storage/uploads';$target=$base.'/'.$relative;if(!is_dir(dirname($target))&&!mkdir(dirname($target),0775,true)&&!is_dir(dirname($target))){throw new RuntimeException('Stockage des pièces jointes indisponible.');}if(!move_uploaded_file($file['tmp_name'],$target)){throw new RuntimeException('Échec enregistrement pièce jointe.');}$this->query('INSERT INTO document_attachments(document_id,original_name,storage_path,mime_type,file_size,checksum_sha256,uploaded_by) VALUES(:document,:name,:path,:mime,:size,:checksum,:user)',['document'=>$id,'name'=>basename($file['name']),'path'=>$relative,'mime'=>$mime,'size'=>$file['size'],'checksum'=>hash_file('sha256',$target),'user'=>$user['id']]);$attachmentId=$this->db->lastInsertId();$this->logActivity('document_attachment','documents','document_attachments',$attachmentId,'Ajout pièce jointe.',null,['document_id'=>$id,'name'=>basename($file['name'])],$user);return $attachmentId;}
    public function attachment($id){$params=['id'=>$id];$scope=Auth::siteClause('d.site_id',$params);return $this->query("SELECT da.*,d.site_id FROM document_attachments da INNER JOIN documents d ON d.id=da.document_id WHERE da.id=:id AND da.deleted_at IS NULL AND d.deleted_at IS NULL{$scope} LIMIT 1",$params)->fetch();}
}
