<?php
class Livestock extends Model
{
 protected $table='livestock_batches';
 public function formReferences(){
 $ids=array_map(fn($site)=>(int)$site['id'],array_filter(Auth::sites(),fn($site)=>in_array($site['code'],['FARM-MUT','FARM-DIK'],true)));
 $scope=implode(',',$ids)?:'0';
 return ['facilities'=>$this->query("SELECT * FROM livestock_facilities WHERE site_id IN ($scope) AND status='active' AND deleted_at IS NULL ORDER BY name")->fetchAll(),
 'batches'=>$this->query("SELECT b.*,sp.name species_name,sp.category,f.name facility_name FROM livestock_batches b JOIN livestock_species sp ON sp.id=b.species_id JOIN livestock_facilities f ON f.id=b.facility_id WHERE b.site_id IN ($scope) AND b.deleted_at IS NULL ORDER BY b.id DESC")->fetchAll(),
 'stocks'=>$this->query("SELECT ws.id stock_id,ws.batch_id,ws.site_id,ws.quantity_kg,ws.reserved_kg,b.batch_number FROM livestock_weight_stocks ws JOIN livestock_batches b ON b.id=ws.batch_id WHERE ws.site_id IN ($scope) AND ws.status='available' ORDER BY ws.id DESC")->fetchAll()];
 }
 private function inputSite(array $data,string $permission):int{
 if(!array_key_exists('site_id',$data))return $this->farm();
 $site=(string)$data['site_id'];$allowed=false;
 foreach(Auth::sites() as $candidate)if((string)$candidate['id']===$site && in_array($candidate['code'],['FARM-MUT','FARM-DIK'],true))$allowed=true;
 if(!$allowed||!Auth::can('livestock',$permission,(int)$site))throw new RuntimeException('Sélectionnez un site d’élevage autorisé (MUTALA ou DIKAPA).');
 $active=$this->row("SELECT id FROM sites WHERE id=? AND status='active' AND deleted_at IS NULL",[(int)$site]);
 if(!$active)throw new RuntimeException('Le site sélectionné n’est plus actif.');
 return (int)$site;
 }
 private function checkInputBatchSite(array $data,array $batch,string $permission):void{
 if(array_key_exists('site_id',$data)&&$this->inputSite($data,$permission)!==(int)$batch['site_id'])throw new RuntimeException('Le lot choisi n’appartient pas au site du formulaire. Sélectionnez un lot de ce site.');
 }
 public function references(){return['species'=>$this->query("SELECT * FROM livestock_species WHERE status='active' AND deleted_at IS NULL ORDER BY name")->fetchAll(),'facilities'=>$this->scoped("SELECT * FROM livestock_facilities WHERE status='active' AND deleted_at IS NULL",'site_id'),'feed_products'=>$this->query("SELECT id,code,name FROM products WHERE code='ALIMENT-BETAIL' AND deleted_at IS NULL")->fetchAll()];}
 public function batches(){$p=[];$s=Auth::siteClause('b.site_id',$p);return$this->query("SELECT b.*,sp.name species_name,sp.category,f.name facility_name,f.facility_type,f.area_m2,COALESCE((SELECT SUM(quantity_kg) FROM livestock_feedings WHERE batch_id=b.id AND deleted_at IS NULL),0) feed_kg,COALESCE((SELECT SUM(eggs_count) FROM poultry_productions WHERE batch_id=b.id),0) eggs_count FROM livestock_batches b JOIN livestock_species sp ON sp.id=b.species_id JOIN livestock_facilities f ON f.id=b.facility_id WHERE b.deleted_at IS NULL{$s} ORDER BY b.id DESC",$p)->fetchAll();}
 public function dailyHistory():array{
 $events=[];
 foreach(['feedings'=>['livestock_feedings','fed_at'],'weighings'=>['livestock_weighings','weighed_at'],'poultry'=>['poultry_productions','production_date']] as $kind=>[$table,$date]){
 $params=[];$scope=Auth::siteClause('b.site_id',$params);
 $extra=$kind==='feedings'?' AND r.deleted_at IS NULL':'';
 $rows=$this->query("SELECT r.*,b.site_id,b.batch_number,u.name author,r.$date event_at FROM $table r JOIN livestock_batches b ON b.id=r.batch_id LEFT JOIN users u ON u.id=r.created_by WHERE b.deleted_at IS NULL$extra$scope",$params)->fetchAll();
 foreach($rows as $row){$row['kind']=$kind;$events[]=$row;}
 }
 usort($events,static fn($a,$b)=>strcmp($b['event_at'],$a['event_at'])?:($b['id']<=>$a['id']));
 return $events;
 }
 public function conversions(){$p=[];$s=Auth::siteClause('b.site_id',$p);return$this->query("SELECT c.*,b.site_id,b.batch_number,sp.name species_name,ws.id stock_id,ws.quantity_kg,ws.reserved_kg FROM livestock_conversions c JOIN livestock_batches b ON b.id=c.batch_id JOIN livestock_species sp ON sp.id=b.species_id LEFT JOIN livestock_weight_stocks ws ON ws.conversion_id=c.id WHERE 1=1{$s} ORDER BY c.id DESC",$p)->fetchAll();}
 public function transfers(){$p=[];$s=Auth::siteClause('t.source_site_id',$p);return$this->query("SELECT t.*,b.batch_number,d.document_number FROM livestock_transfers t JOIN livestock_batches b ON b.id=t.batch_id LEFT JOIN documents d ON d.entity_type='livestock_transfers' AND d.entity_id=t.id AND d.document_type_id=(SELECT id FROM document_types WHERE code='BTR') WHERE t.deleted_at IS NULL{$s} ORDER BY t.id DESC",$p)->fetchAll();}
 public static function facilityCode(string $type):string{
 $prefix=['housing'=>'BAT','poultry_house'=>'POUL','pond'=>'ETG'][$type]??'BAT';
 return $prefix.'-'.date('Ymd').'-'.strtoupper(bin2hex(random_bytes(3)));
 }
 private function checkedFacilityCode(array $data,int $site,int $exceptId=0):string{
 $code=strtoupper(trim((string)($data['code']??'')));
 if($code==='')$code=self::facilityCode($data['facility_type']??'housing');
 if(!preg_match('/^[A-Z0-9][A-Z0-9_-]{0,59}$/D',$code))throw new RuntimeException('Le code doit contenir 1 à 60 caractères : lettres sans accents, chiffres, tirets ou underscores.');
 if($this->row('SELECT id FROM livestock_facilities WHERE site_id=? AND code=? AND id<>?',[$site,$code,$exceptId]))throw new RuntimeException('Ce code de bâtiment ou d’étang existe déjà sur ce site. Modifiez-le ou cliquez sur « Générer un autre code ».');
 return $code;
 }
 public function createFacility(array$d){$site=$this->inputSite($d,'administer');$code=$this->checkedFacilityCode($d,$site);$area=$d['facility_type']==='pond'?(float)$d['area_m2']:null;if($d['facility_type']==='pond'&&$area<=0)throw new RuntimeException('Surface de l’étang obligatoire.');$this->query("INSERT INTO livestock_facilities(site_id,code,name,facility_type,area_m2,capacity_heads,status) VALUES(:site,:code,:name,:type,:area,:capacity,'active')",['site'=>$site,'code'=>$code,'name'=>trim($d['name']),'type'=>$d['facility_type'],'area'=>$area,'capacity'=>$d['capacity_heads']?:null]);return(int)$this->db->lastInsertId();}
 public function updateFacility($id,array $data,array $user):void{
 $this->db->beginTransaction();try{
 $before=$this->row('SELECT * FROM livestock_facilities WHERE id=? AND deleted_at IS NULL FOR UPDATE',[$id]);
 if(!$before)throw new RuntimeException('Bâtiment ou étang introuvable.');
 Auth::requireSiteAccess($before['site_id']);
 if(!Auth::can('livestock','administer',(int)$before['site_id']))throw new RuntimeException('Vous ne pouvez pas modifier cette unité.');
 if((int)($data['site_id']??0)!==(int)$before['site_id'])throw new RuntimeException('Le site de cette unité ne peut pas être modifié.');
 $code=$this->checkedFacilityCode($data,(int)$before['site_id'],(int)$id);$name=trim($data['name']??'');$type=$data['facility_type']??'';
 if($name===''||mb_strlen($name)>150)throw new RuntimeException('Saisissez un nom de 1 à 150 caractères.');
 if(!in_array($type,['housing','poultry_house','pond'],true))throw new RuntimeException('Choisissez un type d’unité valide.');
 $lots=$this->row('SELECT COUNT(*) count_lots,COALESCE(SUM(current_heads),0) heads FROM livestock_batches WHERE facility_id=? AND deleted_at IS NULL',[$id]);
 if($lots['count_lots']>0&&$type!==$before['facility_type'])throw new RuntimeException('Cette unité possède des lots : son type doit être conservé pour préserver leur historique.');
 $area=$type==='pond'?($data['area_m2']??''):null;$capacity=trim((string)($data['capacity_heads']??''));
 if($type==='pond'&&(!is_numeric($area)||(float)$area<=0))throw new RuntimeException('La surface de l’étang doit être supérieure à zéro.');
 if($capacity!==''&&(!ctype_digit($capacity)||(int)$capacity<(int)$lots['heads']))throw new RuntimeException('La capacité doit être un entier au moins égal à l’effectif actuel : '.$lots['heads'].' têtes.');
 $this->query('UPDATE livestock_facilities SET code=:code,name=:name,facility_type=:type,area_m2=:area,capacity_heads=:capacity WHERE id=:id',['code'=>$code,'name'=>$name,'type'=>$type,'area'=>$area,'capacity'=>$capacity===''?null:(int)$capacity,'id'=>$id]);
 $this->logActivity('update','livestock','livestock_facilities',$id,'Modification du bâtiment ou de l’étang.',$before,['code'=>$code,'name'=>$name,'facility_type'=>$type,'area_m2'=>$area,'capacity_heads'=>$capacity],$user,(int)$before['site_id']);
 $this->db->commit();
 }catch(Exception $e){$this->db->rollBack();throw $e;}
 }
 public function createBatch(array$d,array$u){$site=$this->inputSite($d,'create');$f=$this->row('SELECT * FROM livestock_facilities WHERE id=? AND site_id=? AND deleted_at IS NULL',[$d['facility_id'],$site]);$sp=$this->row('SELECT * FROM livestock_species WHERE id=? AND deleted_at IS NULL',[$d['species_id']]);$heads=(int)$d['initial_heads'];if(!$f||!$sp||$heads<=0)throw new RuntimeException('Vérifiez l’espèce, le bâtiment du site sélectionné et un effectif initial supérieur à zéro.');if($sp['category']==='fish'&&$f['facility_type']!=='pond')throw new RuntimeException('Un lot piscicole exige un étang.');if($sp['category']==='poultry'&&$f['facility_type']!=='poultry_house')throw new RuntimeException('Un lot avicole exige un poulailler.');if($sp['category']==='livestock'&&$f['facility_type']!=='housing')throw new RuntimeException('Cette espèce nécessite un bâtiment d’élevage, pas un étang ou un poulailler.');if(($d['purpose']??'')==='laying'&&$sp['category']!=='poultry')throw new RuntimeException('L’objectif ponte est réservé aux volailles.');$d['initial_average_weight_kg']=$sp['category']==='fish'?null:($d['initial_average_weight_kg']??null);$d['initial_total_weight_kg']=$sp['category']==='fish'?($d['initial_total_weight_kg']??null):null;$n='ELV-'.date('YmdHis').'-'.random_int(100,999);$this->db->beginTransaction();try{$this->query("INSERT INTO livestock_batches(site_id,species_id,facility_id,batch_number,purpose,started_at,initial_heads,current_heads,initial_average_weight_kg,current_average_weight_kg,status,created_by) VALUES(:site,:species,:facility,:number,:purpose,:start,:heads,:current,:weight,:weight2,'active',:user)",['site'=>$site,'species'=>$sp['id'],'facility'=>$f['id'],'number'=>$n,'purpose'=>$d['purpose'],'start'=>$d['started_at'],'heads'=>$heads,'current'=>$heads,'weight'=>$d['initial_average_weight_kg']?:null,'weight2'=>$d['initial_average_weight_kg']?:null,'user'=>$u['id']]);$id=(int)$this->db->lastInsertId();$this->headMove($id,'stocking',$heads,0,$heads,'livestock_batches',$id,$u);if($sp['category']==='fish')$this->query('INSERT INTO fish_stockings(batch_id,stocked_heads,total_weight_kg,stocked_at,created_by) VALUES(:batch,:heads,:weight,NOW(),:user)',['batch'=>$id,'heads'=>$heads,'weight'=>$d['initial_total_weight_kg']?:null,'user'=>$u['id']]);$this->db->commit();return$id;}catch(Exception$e){$this->db->rollBack();throw$e;}}
 public function feed(array$d,array$u){$b=$this->batch($d['batch_id']);$this->checkInputBatchSite($d,$b,'update');$q=(float)$d['quantity_kg'];if($q<=0)throw new RuntimeException('Quantité d’aliment invalide.');$this->query('INSERT INTO livestock_feedings(batch_id,feed_product_id,quantity_kg,fed_at,unit_cost,created_by) VALUES(:batch,:product,:qty,:at,:cost,:user)',['batch'=>$b['id'],'product'=>$d['feed_product_id']?:null,'qty'=>$q,'at'=>$d['fed_at'],'cost'=>(float)$d['unit_cost'],'user'=>$u['id']]);}
 public function weigh(array$d,array$u){$b=$this->batch($d['batch_id']);$this->checkInputBatchSite($d,$b,'update');$heads=(int)$d['sample_heads'];$kg=(float)$d['total_weight_kg'];if($heads<=0||$heads>(int)$b['current_heads']||$kg<=0)throw new RuntimeException('Saisissez un nombre de têtes pesées supérieur à zéro et inférieur ou égal à l’effectif du lot, ainsi qu’un poids total positif.');$avg=$kg/$heads;$this->query('INSERT INTO livestock_weighings(batch_id,sample_heads,total_weight_kg,average_weight_kg,weighed_at,created_by) VALUES(:batch,:heads,:kg,:avg,:at,:user)',['batch'=>$b['id'],'heads'=>$heads,'kg'=>$kg,'avg'=>$avg,'at'=>$d['weighed_at'],'user'=>$u['id']]);$this->query('UPDATE livestock_batches SET current_average_weight_kg=:avg WHERE id=:id',['avg'=>$avg,'id'=>$b['id']]);return$avg;}
 public function poultry(array$d,array$u){$b=$this->batch($d['batch_id'],true);$this->checkInputBatchSite($d,$b,'update');if($b['category']!=='poultry')throw new RuntimeException('Lot non avicole.');$mort=(int)$d['mortality_heads'];$sold=(int)$d['sold_heads'];$out=$mort+$sold;if($out<0||$out>(int)$b['current_heads'])throw new RuntimeException('Sortie avicole supérieure à l’effectif.');$this->db->beginTransaction();try{$this->query('INSERT INTO poultry_productions(batch_id,production_date,eggs_count,mortality_heads,sold_heads,created_by) VALUES(:batch,:date,:eggs,:mortality,:sold,:user)',['batch'=>$b['id'],'date'=>$d['production_date'],'eggs'=>(int)$d['eggs_count'],'mortality'=>$mort,'sold'=>$sold,'user'=>$u['id']]);$ref=(int)$this->db->lastInsertId();$before=(int)$b['current_heads'];if($mort)$this->headMove($b['id'],'mortality',$mort,$before,$before-$mort,'poultry_productions',$ref,$u);if($sold)$this->headMove($b['id'],'sale',$sold,$before-$mort,$before-$out,'poultry_productions',$ref,$u);$this->query('UPDATE livestock_batches SET current_heads=:heads WHERE id=:id',['heads'=>$before-$out,'id'=>$b['id']]);$this->db->commit();}catch(Exception$e){$this->db->rollBack();throw$e;}}
 public function createConversion(array$d,array$u){$b=$this->batch($d['batch_id'],true);$this->checkInputBatchSite($d,$b,'create');$heads=(int)$d['input_heads'];$gross=(float)$d['gross_weight_kg'];$tare=(float)$d['tare_weight_kg'];$net=$gross-$tare;if($heads<=0||$heads>(int)$b['current_heads']||$gross<=0||$tare<0||$net<=0)throw new RuntimeException('Vérifiez la conversion : le nombre de têtes doit être compris entre 1 et l’effectif vivant, le poids brut doit être positif et la tare doit être inférieure au poids brut.');$n='CONV-'.date('YmdHis').'-'.random_int(100,999);$this->query("INSERT INTO livestock_conversions(batch_id,conversion_number,conversion_type,input_heads,gross_weight_kg,tare_weight_kg,net_weight_kg,converted_at,status,created_by) VALUES(:batch,:number,:type,:heads,:gross,:tare,:net,:at,'submitted',:user)",['batch'=>$b['id'],'number'=>$n,'type'=>$d['conversion_type'],'heads'=>$heads,'gross'=>$gross,'tare'=>$tare,'net'=>$net,'at'=>$d['converted_at'],'user'=>$u['id']]);return(int)$this->db->lastInsertId();}
 public function createFishCatch(array$d,array$u){$b=$this->batch($d['batch_id'],true);$this->checkInputBatchSite($d,$b,'create');if($b['category']!=='fish'||(float)$b['area_m2']<=0)throw new RuntimeException('Lot piscicole ou surface d’étang invalide.');$d['conversion_type']='fish_catch';$conversion=$this->createConversion($d,$u);$net=(float)$d['gross_weight_kg']-(float)$d['tare_weight_kg'];$this->query("INSERT INTO fish_catches(batch_id,conversion_id,catch_number,heads_caught,gross_weight_kg,tare_weight_kg,net_weight_kg,yield_kg_m2,status,caught_at,created_by) VALUES(:batch,:conversion,:number,:heads,:gross,:tare,:net,:yield,'submitted',:at,:user)",['batch'=>$b['id'],'conversion'=>$conversion,'number'=>'PEC-'.date('YmdHis').'-'.random_int(100,999),'heads'=>(int)$d['input_heads'],'gross'=>$d['gross_weight_kg'],'tare'=>$d['tare_weight_kg'],'net'=>$net,'yield'=>$net/(float)$b['area_m2'],'at'=>$d['converted_at'],'user'=>$u['id']]);return$conversion;}
 public function validateConversion($id,array$u){$this->db->beginTransaction();try{$c=$this->row('SELECT c.*,b.site_id,b.current_heads FROM livestock_conversions c JOIN livestock_batches b ON b.id=c.batch_id WHERE c.id=? FOR UPDATE',[$id]);if(!$c||$c['status']!=='submitted')throw new RuntimeException('Conversion non validable ou déjà validée.');Auth::requireSiteAccess($c['site_id']);if((int)$c['created_by']===(int)$u['id']&&!Auth::canSelfValidate($u['id']))throw new RuntimeException('Le créateur ne peut pas valider la conversion.');if((int)$c['current_heads']<(int)$c['input_heads'])throw new RuntimeException('Effectif vivant insuffisant.');$after=(int)$c['current_heads']-(int)$c['input_heads'];$this->query('UPDATE livestock_batches SET current_heads=:heads,status=IF(:heads2>0,status,\'completed\') WHERE id=:id',['heads'=>$after,'heads2'=>$after,'id'=>$c['batch_id']]);$this->headMove($c['batch_id'],$c['conversion_type']==='slaughter'?'slaughter':'transfer_out',$c['input_heads'],$c['current_heads'],$after,'livestock_conversions',$id,$u);$this->query("INSERT INTO livestock_weight_stocks(site_id,batch_id,conversion_id,quantity_kg,reserved_kg,status) VALUES(:site,:batch,:conversion,:qty,0,'available')",['site'=>$c['site_id'],'batch'=>$c['batch_id'],'conversion'=>$id,'qty'=>$c['net_weight_kg']]);$stock=(int)$this->db->lastInsertId();$this->weightMove($stock,'conversion_in',$c['net_weight_kg'],0,$c['net_weight_kg'],0,0,'livestock_conversions',$id,$u);$this->query("UPDATE livestock_conversions SET status='validated',validated_by=:user,validated_at=NOW() WHERE id=:id",['user'=>$u['id'],'id'=>$id]);$this->logActivity('validate_livestock_conversion','livestock','livestock_conversions',$id,'Conversion formelle des têtes vivantes en kilogrammes.',null,['stock_id'=>$stock],$u);$this->db->commit();return$stock;}catch(Exception$e){$this->db->rollBack();throw$e;}}
 public function createTransfer(array$d,array$u){$site=$this->inputSite($d,'create');$dest=$this->siteId('BOUCH');$unit=$d['source_unit'];$batch=$this->row('SELECT * FROM livestock_batches WHERE id=? AND site_id=? AND status=\'active\'',[$d['batch_id'],$site]);if(!$batch)throw new RuntimeException('Choisissez un lot actif appartenant au site sélectionné dans l’application.');$heads=null;$kg=null;$weight=null;if($unit==='head'){$heads=(int)$d['quantity_heads'];if($heads<=0||$heads>(int)$batch['current_heads'])throw new RuntimeException('Effectif insuffisant.');}elseif($unit==='kg'){$weight=$this->row("SELECT * FROM livestock_weight_stocks WHERE id=? AND batch_id=? AND status='available'",[$d['weight_stock_id'],$batch['id']]);$kg=(float)$d['quantity_kg'];if(!$weight||$kg<=0||$kg>(float)$weight['quantity_kg'])throw new RuntimeException('Sélectionnez un stock issu d’une conversion du même lot et une quantité positive ne dépassant pas ce stock.');}else throw new RuntimeException('Unité de transfert invalide.');$this->db->beginTransaction();try{$n='BTR-ELV-'.date('YmdHis').'-'.random_int(100,999);$this->query("INSERT INTO livestock_transfers(batch_id,weight_stock_id,source_site_id,destination_site_id,transfer_number,source_unit,quantity_heads,quantity_kg,status,truck_plate,driver_name,created_by) VALUES(:batch,:weight,:source,:dest,:number,:unit,:heads,:kg,'draft',:truck,:driver,:user)",['batch'=>$batch['id'],'weight'=>$weight['id']??null,'source'=>$site,'dest'=>$dest,'number'=>$n,'unit'=>$unit,'heads'=>$heads,'kg'=>$kg,'truck'=>strtoupper(trim($d['truck_plate'])),'driver'=>trim($d['driver_name']),'user'=>$u['id']]);$id=(int)$this->db->lastInsertId();require_once dirname(__DIR__).'/services/DocumentService.php';(new DocumentService($this->db))->register('BTR',$site,'livestock_transfers',$id,'draft',date('Y-m-d H:i:s'),$u);$this->db->commit();return$id;}catch(Exception$e){$this->db->rollBack();throw$e;}}
 public function approveTransfer($id,array$u){$this->db->beginTransaction();try{$t=$this->row('SELECT * FROM livestock_transfers WHERE id=? FOR UPDATE',[$id]);if(!$t||$t['status']!=='draft')throw new RuntimeException('BTR non validable.');if((int)$t['created_by']===(int)$u['id']&&!Auth::canSelfValidate($u['id']))throw new RuntimeException('Le créateur ne peut pas valider le BTR.');Auth::requireSiteAccess($t['source_site_id']);if($t['source_unit']==='kg'){$s=$this->row('SELECT * FROM livestock_weight_stocks WHERE id=? FOR UPDATE',[$t['weight_stock_id']]);$avail=(float)$s['quantity_kg']-(float)$s['reserved_kg'];if($avail<(float)$t['quantity_kg'])throw new RuntimeException('Kilogrammes disponibles insuffisants.');$after=(float)$s['reserved_kg']+(float)$t['quantity_kg'];$this->query("UPDATE livestock_weight_stocks SET reserved_kg=:q,status='reserved' WHERE id=:id",['q'=>$after,'id'=>$s['id']]);$this->weightMove($s['id'],'reserve',$t['quantity_kg'],$s['quantity_kg'],$s['quantity_kg'],$s['reserved_kg'],$after,'livestock_transfers',$id,$u);}$this->query("UPDATE livestock_transfers SET status='approved',approved_by=:user WHERE id=:id",['user'=>$u['id'],'id'=>$id]);$this->approveDoc($id,$u);$this->db->commit();}catch(Exception$e){$this->db->rollBack();throw$e;}}
 public function dispatchTransfer($id,array$u){$this->db->beginTransaction();try{$t=$this->row('SELECT * FROM livestock_transfers WHERE id=? FOR UPDATE',[$id]);if(!$t||$t['status']!=='approved')throw new RuntimeException('BTR non expédiable ou déjà expédié.');Auth::requireSiteAccess($t['source_site_id']);if($t['source_unit']==='head'){$b=$this->row('SELECT * FROM livestock_batches WHERE id=? FOR UPDATE',[$t['batch_id']]);if((int)$b['current_heads']<(int)$t['quantity_heads'])throw new RuntimeException('Effectif insuffisant.');$after=(int)$b['current_heads']-(int)$t['quantity_heads'];$this->query('UPDATE livestock_batches SET current_heads=:q WHERE id=:id',['q'=>$after,'id'=>$b['id']]);$this->headMove($b['id'],'transfer_out',$t['quantity_heads'],$b['current_heads'],$after,'livestock_transfers',$id,$u);}else{$s=$this->row('SELECT * FROM livestock_weight_stocks WHERE id=? FOR UPDATE',[$t['weight_stock_id']]);$q=(float)$t['quantity_kg'];if((float)$s['quantity_kg']<$q||(float)$s['reserved_kg']<$q)throw new RuntimeException('Stock pesé réservé incohérent.');$after=(float)$s['quantity_kg']-$q;$reserved=(float)$s['reserved_kg']-$q;$this->query("UPDATE livestock_weight_stocks SET quantity_kg=:q,reserved_kg=:r,status=IF(:q2>0,'available','in_transit') WHERE id=:id",['q'=>$after,'r'=>$reserved,'q2'=>$after,'id'=>$s['id']]);$this->weightMove($s['id'],'transfer_out',$q,$s['quantity_kg'],$after,$s['reserved_kg'],$reserved,'livestock_transfers',$id,$u);}$this->query("UPDATE livestock_transfers SET status='in_transit',dispatched_by=:user,dispatched_at=NOW() WHERE id=:id",['user'=>$u['id'],'id'=>$id]);$this->logActivity('dispatch_livestock_transfer','livestock','livestock_transfers',$id,'BTR vers la boucherie expédié avec lot d’origine.',null,$t,$u);$this->db->commit();}catch(Exception$e){$this->db->rollBack();throw$e;}}
 public function metrics($batchId){$b=$this->batch($batchId,true);$days=max(1,(strtotime(date('Y-m-d'))-strtotime($b['started_at']))/86400);$gmq=$b['initial_average_weight_kg']!==null&&$b['current_average_weight_kg']!==null?(((float)$b['current_average_weight_kg']-(float)$b['initial_average_weight_kg'])*1000/$days):null;$fishYield=$b['category']==='fish'&&$b['area_m2']>0?(float)$this->query("SELECT COALESCE(SUM(net_weight_kg),0) FROM fish_catches WHERE batch_id=:id AND status='validated'",['id'=>$b['id']])->fetchColumn()/(float)$b['area_m2']:null;return['gmq_g_day'=>$gmq,'fish_yield_kg_m2'=>$fishYield];}
 private function batch($id,$details=false){$sql=$details?"SELECT b.*,sp.category,f.area_m2 FROM livestock_batches b JOIN livestock_species sp ON sp.id=b.species_id JOIN livestock_facilities f ON f.id=b.facility_id WHERE b.id=? AND b.deleted_at IS NULL":"SELECT * FROM livestock_batches WHERE id=? AND deleted_at IS NULL";$b=$this->row($sql,[$id]);if(!$b)throw new RuntimeException('Lot introuvable.');Auth::requireSiteAccess($b['site_id']);return$b;}private function farm(){$s=Auth::requireCurrentSite();$c=$this->query('SELECT code FROM sites WHERE id=:id',['id'=>$s])->fetchColumn();if(!in_array($c,['FARM-MUT','FARM-DIK'],true))throw new RuntimeException('Sélectionnez MUTALA ou DIKAPA.');return$s;}private function siteId($c){return(int)$this->query('SELECT id FROM sites WHERE code=:c',['c'=>$c])->fetchColumn();}private function scoped($sql,$column){$p=[];$s=Auth::siteClause($column,$p);return$this->query($sql.$s.' ORDER BY name',$p)->fetchAll();}
 private function headMove($b,$t,$q,$before,$after,$rt,$rid,$u){$this->query('INSERT INTO livestock_head_movements(batch_id,movement_type,quantity_heads,heads_before,heads_after,reference_type,reference_id,movement_at,created_by) VALUES(:b,:t,:q,:before,:after,:rt,:rid,NOW(),:u)',['b'=>$b,'t'=>$t,'q'=>$q,'before'=>$before,'after'=>$after,'rt'=>$rt,'rid'=>$rid,'u'=>$u['id']]);}private function weightMove($s,$t,$q,$before,$after,$rb,$ra,$rt,$rid,$u){$this->query('INSERT INTO livestock_weight_movements(stock_id,movement_type,quantity_kg,stock_before_kg,stock_after_kg,reserved_before_kg,reserved_after_kg,reference_type,reference_id,created_by) VALUES(:s,:t,:q,:b,:a,:rb,:ra,:rt,:rid,:u)',['s'=>$s,'t'=>$t,'q'=>$q,'b'=>$before,'a'=>$after,'rb'=>$rb,'ra'=>$ra,'rt'=>$rt,'rid'=>$rid,'u'=>$u['id']]);}private function approveDoc($id,$u){$d=$this->row("SELECT d.* FROM documents d JOIN document_types dt ON dt.id=d.document_type_id WHERE dt.code='BTR' AND d.entity_type='livestock_transfers' AND d.entity_id=? FOR UPDATE",[$id]);if($d){$this->query("UPDATE documents SET status='approved',validated_by=:u,validated_at=NOW() WHERE id=:id",['u'=>$u['id'],'id'=>$d['id']]);$this->query("INSERT INTO document_status_history(document_id,old_status,new_status,changed_by,reason) VALUES(:d,:old,'approved',:u,'Validation BTR élevage')",['d'=>$d['id'],'old'=>$d['status'],'u'=>$u['id']]);}}private function row($s,$p=[]){$q=$this->db->prepare($s);$q->execute($p);return$q->fetch();}
}
