<?php
class Transfer extends Model
{
 protected $table='stock_transfers';
 public function allDetailed(){$p=[];$scope=Auth::siteClause('t.source_site_id',$p);if(Auth::currentSiteId()!==null){$site=Auth::currentSiteId();$p=['transfer_site'=>$site];$scope=' AND (t.source_site_id=:transfer_site OR t.destination_site_id=:transfer_site2)';$p['transfer_site2']=$site;}return$this->query("SELECT t.*,ss.code source_code,ss.name source_name,ds.code destination_code,ds.name destination_name,u.name creator_name,a.name approver_name,(SELECT SUM(requested_bags) FROM stock_transfer_items WHERE transfer_id=t.id) requested_bags FROM stock_transfers t JOIN sites ss ON ss.id=t.source_site_id JOIN sites ds ON ds.id=t.destination_site_id JOIN users u ON u.id=t.created_by LEFT JOIN users a ON a.id=t.approved_by WHERE t.deleted_at IS NULL{$scope} ORDER BY t.created_at DESC",$p)->fetchAll();}
 public function directoryItems(array $transfers)
 {
  if (!$transfers) return [];
  $ids = array_map('intval', array_column($transfers, 'id'));
  $rows = $this->query('SELECT ti.*,p.name product_name,bf.name format_name FROM stock_transfer_items ti JOIN products p ON p.id=ti.product_id JOIN bag_formats bf ON bf.id=ti.bag_format_id WHERE ti.transfer_id IN ('.implode(',', $ids).') ORDER BY ti.id')->fetchAll();
  $grouped = [];
  foreach ($rows as $row) $grouped[$row['transfer_id']][] = $row;
  return $grouped;
 }
 public function findDetailed($id){$t=$this->query("SELECT t.*,ss.code source_code,ss.name source_name,ds.code destination_code,ds.name destination_name,u.name creator_name,a.name approver_name FROM stock_transfers t JOIN sites ss ON ss.id=t.source_site_id JOIN sites ds ON ds.id=t.destination_site_id JOIN users u ON u.id=t.created_by LEFT JOIN users a ON a.id=t.approved_by WHERE t.id=:id AND t.deleted_at IS NULL",['id'=>$id])->fetch();if(!$t){return null;}if(!Auth::canAccessSite($t['source_site_id'])&&!Auth::canAccessSite($t['destination_site_id'])){return null;}$t['items']=$this->query('SELECT ti.*,p.name product_name,bf.name format_name FROM stock_transfer_items ti JOIN products p ON p.id=ti.product_id JOIN bag_formats bf ON bf.id=ti.bag_format_id WHERE ti.transfer_id=:id',['id'=>$id])->fetchAll();$t['shipments']=$this->query('SELECT * FROM transfer_shipments WHERE transfer_id=:id ORDER BY id',['id'=>$id])->fetchAll();foreach($t['shipments']as&$s){$s['items']=$this->query('SELECT si.*,ti.product_id,p.name product_name,bf.name format_name FROM transfer_shipment_items si JOIN stock_transfer_items ti ON ti.id=si.transfer_item_id JOIN products p ON p.id=ti.product_id JOIN bag_formats bf ON bf.id=ti.bag_format_id WHERE si.shipment_id=:id',['id'=>$s['id']])->fetchAll();}unset($s);$t['returns']=$this->query('SELECT * FROM transfer_returns WHERE transfer_id=:id ORDER BY id',['id'=>$id])->fetchAll();$t['non_conformities']=$this->query('SELECT * FROM transfer_non_conformities WHERE transfer_id=:id ORDER BY id',['id'=>$id])->fetchAll();$t['history']=$this->query('SELECT h.*,u.name actor_name FROM stock_transfer_history h JOIN users u ON u.id=h.actor_id WHERE h.transfer_id=:id ORDER BY h.id DESC',['id'=>$id])->fetchAll();return$t;}
 public function siteBalances()
 {
  $rows=$this->query("SELECT fs.site_id,fs.product_id,fs.bag_format_id,p.name product_name,bf.name format_name,SUM(fs.quantity_bags) physical,SUM(fs.reserved_bags) reserved,SUM(GREATEST(fs.quantity_bags-fs.reserved_bags,0)) available FROM finished_stocks fs JOIN products p ON p.id=fs.product_id JOIN bag_formats bf ON bf.id=fs.bag_format_id JOIN sites s ON s.id=fs.site_id WHERE fs.deleted_at IS NULL AND fs.status IN ('active','validated') AND s.status='active' AND s.deleted_at IS NULL GROUP BY fs.site_id,fs.product_id,fs.bag_format_id,p.name,bf.name ORDER BY p.name,bf.name")->fetchAll();
  return array_values(array_filter($rows,static function($row){return Auth::canAccessSite($row['site_id']);}));
 }
 public function references(){return['balances'=>$this->siteBalances(),'sites'=>$this->query("SELECT id,code,name FROM sites WHERE status='active' AND deleted_at IS NULL ORDER BY name")->fetchAll(),'stocks'=>$this->query("SELECT fs.id,fs.site_id,fs.product_id,fs.bag_format_id,fs.quantity_bags,fs.reserved_bags,fs.total_weight_kg,p.name product_name,bf.name format_name,s.code site_code FROM finished_stocks fs JOIN products p ON p.id=fs.product_id JOIN bag_formats bf ON bf.id=fs.bag_format_id JOIN sites s ON s.id=fs.site_id WHERE fs.deleted_at IS NULL AND fs.status IN('active','validated') AND fs.quantity_bags>fs.reserved_bags ORDER BY s.code,p.name")->fetchAll()];}
}
