<?php
$referenceCount=count($locations)+count($costCenters)+count($units);$assignedUsers=0;
foreach($users as$account){if(!empty($account['site_ids']))$assignedUsers++;}
function site_options($rows){foreach($rows as$row){?><option value="<?=e($row['id'])?>"><?=e($row['code'].' — '.$row['name'])?></option><?php }}
function site_modal_header($id,$icon,$title,$subtitle){?><header><span class="entity-modal-icon"><i class="bi <?=e($icon)?>"></i></span><div><p class="section-label">ADMINISTRATION MULTI-SITES</p><h2 id="<?=e($id)?>Title"><?=e($title)?></h2><p><?=e($subtitle)?></p></div><button type="button" class="modal-close" data-site-modal-close aria-label="Fermer"><i class="bi bi-x-lg"></i></button></header><?php }
?>
<section class="page-heading sites-heading"><div><p class="page-kicker">Administration · Organisation</p><h2>Sites & structures</h2><p>Gérez le périmètre opérationnel, ses référentiels et les accès géographiques depuis un espace unique.</p></div></section>
<?php if(!empty($success)):?><div class="app-alert app-alert-success"><?=e($success)?></div><?php endif;?>
<?php if(!empty($error)):?><div class="app-alert app-alert-error"><?=e($error)?></div><?php endif;?>

<section class="site-stat-grid" aria-label="Synthèse multi-sites">
 <article><span class="user-stat-icon is-blue"><i class="bi bi-buildings"></i></span><div><strong><?=e(count($sites))?></strong><span>Sites configurés</span></div></article>
 <article><span class="user-stat-icon is-green"><i class="bi bi-geo-alt"></i></span><div><strong><?=e(count($locations))?></strong><span>Emplacements</span></div></article>
 <article><span class="user-stat-icon is-orange"><i class="bi bi-diagram-3"></i></span><div><strong><?=e($referenceCount)?></strong><span>Référentiels rattachés</span></div></article>
 <article><span class="user-stat-icon is-slate"><i class="bi bi-person-check"></i></span><div><strong><?=e($assignedUsers)?></strong><span>Utilisateurs affectés</span></div></article>
</section>

<nav class="site-directory-nav" role="tablist" aria-label="Répertoires multi-sites" data-site-tabs><button type="button" role="tab" aria-selected="true" aria-controls="siteDirectory" data-site-tab="sites"><i class="bi bi-buildings"></i><span>Sites</span><strong><?=e(count($sites))?></strong></button><button type="button" role="tab" aria-selected="false" aria-controls="siteLocations" data-site-tab="locations" tabindex="-1"><i class="bi bi-box-seam"></i><span>Emplacements</span><strong><?=e(count($locations))?></strong></button><button type="button" role="tab" aria-selected="false" aria-controls="siteCostCenters" data-site-tab="cost-centers" tabindex="-1"><i class="bi bi-cash-stack"></i><span>Centres de coût</span><strong><?=e(count($costCenters))?></strong></button><button type="button" role="tab" aria-selected="false" aria-controls="siteUnits" data-site-tab="units" tabindex="-1"><i class="bi bi-diagram-2"></i><span>Unités</span><strong><?=e(count($units))?></strong></button><button type="button" role="tab" aria-selected="false" aria-controls="siteAssignments" data-site-tab="assignments" tabindex="-1"><i class="bi bi-people"></i><span>Affectations</span><strong><?=e(count($users))?></strong></button></nav>

<section class="site-quick-actions"><div class="site-quick-intro"><p class="section-label">Créer et organiser</p><h3>Que souhaitez-vous ajouter ?</h3><p>Chaque action ouvre un formulaire guidé sans quitter cette page.</p></div><div class="site-action-buttons">
 <button type="button" class="is-primary" data-site-modal-open="siteEditor"><i class="bi bi-building-add"></i><span><strong>Ajouter un site</strong><small>Ferme, dépôt ou unité industrielle</small></span><i class="bi bi-chevron-right"></i></button>
 <button type="button" data-site-modal-open="siteTypeEditor"><i class="bi bi-tags"></i><span><strong>Ajouter un type</strong><small>Catégorie utilisée par les sites</small></span><i class="bi bi-chevron-right"></i></button>
 <button type="button" data-site-modal-open="locationEditor"><i class="bi bi-box-seam"></i><span><strong>Ajouter un emplacement</strong><small>Dépôt, silo ou chambre froide</small></span><i class="bi bi-chevron-right"></i></button>
 <button type="button" data-site-modal-open="costCenterEditor"><i class="bi bi-cash-stack"></i><span><strong>Ajouter un centre de coût</strong><small>Périmètre de suivi budgétaire</small></span><i class="bi bi-chevron-right"></i></button>
 <button type="button" data-site-modal-open="unitEditor"><i class="bi bi-diagram-2"></i><span><strong>Ajouter une unité</strong><small>Équipe ou unité opérationnelle</small></span><i class="bi bi-chevron-right"></i></button>
</div></section>

<section class="table-panel sites-table-panel"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-buildings"></i></span><div><h3>Répertoire des sites</h3><p>Structures DAGRIL et niveau d’utilisation.</p></div></div><div class="table-responsive"><table data-search-placeholder="Rechercher un code, un site ou un type"><thead><tr><th>Site</th><th>Type</th><th>Utilisateurs</th><th>Emplacements</th><th>Statut</th><th data-sortable="false">Actions</th></tr></thead><tbody>
<?php foreach($sites as$site):$payload=['id'=>(int)$site['id'],'site_type_id'=>(int)$site['site_type_id'],'code'=>$site['code'],'name'=>$site['name'],'description'=>$site['description'],'status'=>$site['status']];?><tr><td><div class="site-name-cell"><span><i class="bi bi-building"></i></span><div><strong><?=e($site['code'])?></strong><small><?=e($site['name'])?></small></div></div></td><td><?=e($site['type_name'])?></td><td><strong><?=e($site['users_count'])?></strong><small class="table-subline">affectation(s)</small></td><td><strong><?=e($site['locations_count'])?></strong><small class="table-subline">emplacement(s)</small></td><td><span class="status-badge status-<?=e($site['status'])?>"><?=e($site['status']==='active'?'Actif':'Inactif')?></span></td><td><button type="button" class="icon-button" title="Modifier le site" data-site-edit data-site='<?=e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>'><i class="bi bi-pencil-square"></i></button></td></tr><?php endforeach;?>
<?php if(!$sites):?><tr><td colspan="6">Aucun site configuré.</td></tr><?php endif;?></tbody></table></div></section>

<nav class="site-directory-nav" aria-label="Accès aux tableaux"><a href="#siteLocations"><i class="bi bi-box-seam"></i><span>Emplacements</span><strong><?=e(count($locations))?></strong></a><a href="#siteCostCenters" class="is-highlighted"><i class="bi bi-cash-stack"></i><span>Centres de coût</span><strong><?=e(count($costCenters))?></strong></a><a href="#siteUnits"><i class="bi bi-diagram-2"></i><span>Unités opérationnelles</span><strong><?=e(count($units))?></strong></a><a href="#siteAssignments"><i class="bi bi-people"></i><span>Affectations</span><strong><?=e(count($users))?></strong></a></nav>

<section class="table-panel site-reference-panel" id="siteLocations"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-box-seam"></i></span><div><h3>Emplacements de stockage</h3><p>Dépôts, silos, zones de production, cours et chambres froides — <?=e(count($locations))?> enregistré(s).</p></div><button type="button" class="panel-action" data-site-modal-open="locationEditor"><i class="bi bi-plus-lg"></i> Ajouter</button></div><div class="table-responsive"><table data-search-placeholder="Rechercher un emplacement, un site ou un type"><thead><tr><th>Code emplacement</th><th>Désignation</th><th>Site de rattachement</th><th>Type d’emplacement</th><th>Statut</th></tr></thead><tbody><?php foreach($locations as$row):?><tr><td><strong><?=e($row['code'])?></strong></td><td><?=e($row['name'])?></td><td><span class="site-chip"><?=e($row['site_code'])?></span><small class="table-subline"><?=e($row['site_name'])?></small></td><td><?=e($row['location_type']??'—')?></td><td><span class="status-badge status-<?=e($row['status'])?>"><?=e($row['status']==='active'?'Actif':'Inactif')?></span></td></tr><?php endforeach;?><?php if(!$locations):?><tr><td colspan="5">Aucun emplacement. Utilisez « Ajouter » pour créer le premier.</td></tr><?php endif;?></tbody></table></div></section>

<section class="table-panel site-reference-panel cost-center-panel" id="siteCostCenters"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-cash-stack"></i></span><div><h3>Centres de coût</h3><p>Axes d’imputation budgétaire et analytique par site — <?=e(count($costCenters))?> enregistré(s).</p></div><button type="button" class="panel-action" data-site-modal-open="costCenterEditor"><i class="bi bi-plus-lg"></i> Ajouter un centre</button></div><div class="table-responsive"><table data-search-placeholder="Rechercher un centre de coût, un code ou un site"><thead><tr><th>Code centre de coût</th><th>Libellé du centre</th><th>Site d’imputation</th><th>Unités rattachées</th><th>Statut</th></tr></thead><tbody><?php foreach($costCenters as$row):$linked=0;foreach($units as$unit){if((int)($unit['cost_center_id']??0)===(int)$row['id'])$linked++;}?><tr><td><strong><?=e($row['code'])?></strong></td><td><?=e($row['name'])?></td><td><span class="site-chip"><?=e($row['site_code'])?></span><small class="table-subline"><?=e($row['site_name'])?></small></td><td><strong><?=e($linked)?></strong><small class="table-subline">unité(s)</small></td><td><span class="status-badge status-<?=e($row['status'])?>"><?=e($row['status']==='active'?'Actif':'Inactif')?></span></td></tr><?php endforeach;?><?php if(!$costCenters):?><tr><td colspan="5">Aucun centre de coût. Utilisez « Ajouter un centre » pour créer le premier.</td></tr><?php endif;?></tbody></table></div></section>

<section class="table-panel site-reference-panel" id="siteUnits"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-diagram-2"></i></span><div><h3>Unités opérationnelles</h3><p>Équipes et structures d’exécution rattachées aux sites — <?=e(count($units))?> enregistrée(s).</p></div><button type="button" class="panel-action" data-site-modal-open="unitEditor"><i class="bi bi-plus-lg"></i> Ajouter</button></div><div class="table-responsive"><table data-search-placeholder="Rechercher une unité, un centre de coût ou un site"><thead><tr><th>Code unité</th><th>Désignation</th><th>Site de rattachement</th><th>Centre de coût associé</th><th>Statut</th></tr></thead><tbody><?php foreach($units as$row):?><tr><td><strong><?=e($row['code'])?></strong></td><td><?=e($row['name'])?></td><td><span class="site-chip"><?=e($row['site_code'])?></span><small class="table-subline"><?=e($row['site_name'])?></small></td><td><?=e($row['cost_center_name']??'Non rattaché')?></td><td><span class="status-badge status-<?=e($row['status'])?>"><?=e($row['status']==='active'?'Actif':'Inactif')?></span></td></tr><?php endforeach;?><?php if(!$units):?><tr><td colspan="5">Aucune unité opérationnelle. Utilisez « Ajouter » pour créer la première.</td></tr><?php endif;?></tbody></table></div></section>

<section class="table-panel" id="siteAssignments"><div class="panel-heading"><span class="panel-icon"><i class="bi bi-people"></i></span><div><h3>Affectations des utilisateurs</h3><p>Périmètre géographique autorisé et contexte de connexion par défaut.</p></div></div><div class="table-responsive"><table data-search-placeholder="Rechercher un utilisateur, un rôle ou un site"><thead><tr><th>Compte utilisateur</th><th>Rôle historique</th><th>Sites accessibles</th><th>Contexte par défaut</th><th data-sortable="false">Gérer</th></tr></thead><tbody>
<?php foreach($users as$account):$codes=[];$default='Non défini';foreach($activeSites as$s){if(in_array((int)$s['id'],$account['site_ids'],true))$codes[]=$s['code'];if((int)$account['default_site_id']===(int)$s['id'])$default=$s['code'];}$payload=['id'=>(int)$account['id'],'name'=>$account['name'],'role_name'=>$account['role_name'],'site_ids'=>$account['site_ids'],'default_site_id'=>$account['default_site_id']];?><tr><td><div class="user-cell"><span><?=e(strtoupper(substr($account['name'],0,1)))?></span><div><strong><?=e($account['name'])?></strong><small><?=e($account['email'])?></small></div></div></td><td><?=e($account['role_name'])?></td><td><div class="site-chip-list"><?php if(!$codes):?><span class="site-chip is-empty">Aucun site</span><?php else:foreach($codes as$code):?><span class="site-chip"><?=e($code)?></span><?php endforeach;endif;?></div></td><td><strong><?=e($default)?></strong></td><td><button type="button" class="icon-button" title="Modifier les affectations" data-site-assignment data-assignment='<?=e(json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?>'><i class="bi bi-geo-alt"></i></button></td></tr><?php endforeach;?></tbody></table></div></section>

<div class="entity-modal-backdrop site-entity-backdrop" data-site-modal-backdrop></div>
<section id="siteEditor" class="entity-modal site-entity-modal" role="dialog" aria-modal="true" aria-labelledby="siteEditorTitle" aria-hidden="true" data-site-editor data-create-action="<?=e(base_url('sites'))?>" data-update-pattern="<?=e(base_url('sites/__id__/update'))?>"><?php site_modal_header('siteEditor','bi-building-add','Nouveau site','Créez une structure opérationnelle et définissez son statut.');?><form method="post" action="<?=e(base_url('sites'))?>" data-site-form data-confirm-title="Enregistrer le site"><?=csrf_field()?><div class="entity-modal-body"><section class="modal-form-section"><div class="modal-form-section-head"><i class="bi bi-building-gear"></i><div><strong>Identification</strong><span>Le code doit rester unique.</span></div></div><div class="form-grid"><label><span>Type de site *</span><select name="site_type_id" required><?php foreach($types as$type):?><option value="<?=e($type['id'])?>"><?=e($type['code'].' — '.$type['name'])?></option><?php endforeach;?></select></label><label><span>Code *</span><input name="code" maxlength="50" data-uppercase required></label><label class="field-wide"><span>Nom *</span><input name="name" maxlength="150" required></label><label class="field-wide"><span>Description</span><textarea name="description" rows="3"></textarea></label><label><span>Statut *</span><select name="status"><option value="active">Actif</option><option value="inactive">Inactif</option></select></label></div></section></div><footer><button type="button" class="btn-secondary" data-site-modal-close>Annuler</button><button class="btn-primary"><i class="bi bi-check2"></i><span data-site-submit-label>Créer le site</span></button></footer></form></section>

<?php $simple=[['siteTypeEditor','bi-tags','Type de site','Ajoutez une catégorie de structure.','site-type',false],['locationEditor','bi-box-seam','Nouvel emplacement','Créez un dépôt ou emplacement.','location',true],['costCenterEditor','bi-cash-stack','Nouveau centre de coût','Rattachez les coûts à un site.','cost-center',true]];foreach($simple as$d):?>
<section id="<?=e($d[0])?>" class="entity-modal site-entity-modal" role="dialog" aria-modal="true" aria-labelledby="<?=e($d[0])?>Title" aria-hidden="true"><?php site_modal_header($d[0],$d[1],$d[2],$d[3]);?><form method="post" action="<?=e(base_url('sites/references/'.$d[4]))?>" data-confirm-title="Ajouter le référentiel"><?=csrf_field()?><div class="entity-modal-body"><section class="modal-form-section"><div class="form-grid"><?php if($d[5]):?><label class="field-wide"><span>Site *</span><select name="site_id" required><?php site_options($activeSites);?></select></label><?php endif;?><label><span>Code *</span><input name="code" maxlength="50" data-uppercase required></label><label><span>Nom *</span><input name="name" maxlength="150" required></label><?php if($d[4]==='location'):?><label class="field-wide"><span>Type</span><select name="location_type"><option value="warehouse">Dépôt</option><option value="silo">Silo</option><option value="production">Production</option><option value="yard">Cour</option><option value="cold_room">Chambre froide</option><option value="other">Autre</option></select></label><?php endif;?></div></section></div><footer><button type="button" class="btn-secondary" data-site-modal-close>Annuler</button><button class="btn-primary"><i class="bi bi-plus-lg"></i> Ajouter</button></footer></form></section><?php endforeach;?>

<section id="unitEditor" class="entity-modal site-entity-modal" role="dialog" aria-modal="true" aria-labelledby="unitEditorTitle" aria-hidden="true"><?php site_modal_header('unitEditor','bi-diagram-2','Nouvelle unité opérationnelle','Associez une unité à son site et à un centre de coût.');?><form method="post" action="<?=e(base_url('sites/references/unit'))?>" data-confirm-title="Ajouter l’unité"><?=csrf_field()?><div class="entity-modal-body"><section class="modal-form-section"><div class="form-grid"><label><span>Site *</span><select name="site_id" required><?php site_options($activeSites);?></select></label><label><span>Centre de coût</span><select name="cost_center_id"><option value="">Aucun</option><?php foreach($costCenters as$c):?><option value="<?=e($c['id'])?>"><?=e($c['site_code'].' — '.$c['name'])?></option><?php endforeach;?></select></label><label><span>Code *</span><input name="code" maxlength="50" data-uppercase required></label><label><span>Nom *</span><input name="name" maxlength="150" required></label></div></section></div><footer><button type="button" class="btn-secondary" data-site-modal-close>Annuler</button><button class="btn-primary"><i class="bi bi-plus-lg"></i> Ajouter</button></footer></form></section>

<section id="assignmentEditor" class="entity-modal site-entity-modal" role="dialog" aria-modal="true" aria-labelledby="assignmentEditorTitle" aria-hidden="true" data-assignment-editor data-action-pattern="<?=e(base_url('sites/users/__id__/assign'))?>"><?php site_modal_header('assignmentEditor','bi-person-gear','Affecter les sites','Définissez les sites accessibles et le contexte par défaut.');?><form method="post" action="#" data-assignment-form data-confirm-title="Mettre à jour les affectations"><?=csrf_field()?><div class="entity-modal-body"><section class="modal-form-section"><div class="modal-form-section-head"><i class="bi bi-person-vcard"></i><div><strong data-assignment-name>Utilisateur</strong><span data-assignment-role>Rôle</span></div></div><div class="site-choice-grid"><?php foreach($activeSites as$s):?><label><input type="checkbox" name="site_ids[]" value="<?=e($s['id'])?>"><span><strong><?=e($s['code'])?></strong><small><?=e($s['name'])?></small></span></label><?php endforeach;?></div></section><section class="modal-form-section"><div class="form-grid"><label class="field-wide"><span>Site par défaut *</span><select name="default_site_id" required><?php site_options($activeSites);?></select><small>Le site par défaut doit être sélectionné ci-dessus.</small></label></div></section></div><footer><button type="button" class="btn-secondary" data-site-modal-close>Annuler</button><button class="btn-primary"><i class="bi bi-check2"></i> Enregistrer</button></footer></form></section>
