<?php
$query=http_build_query($filters);$exporting=!empty($exportMode);
$num=static function($v,$d=0){return number_format((float)$v,$d,',',' ');};
$period=date('d/m/Y',strtotime($filters['start_date'])).' — '.date('d/m/Y',strtotime($filters['end_date']));
$previousPeriod=date('d/m/Y',strtotime($previousFilters['start_date'])).' — '.date('d/m/Y',strtotime($previousFilters['end_date']));
$indicators=[['Réceptions','received_kg','kg','reports/daily'],['Production','produced_kg','kg','reports/production'],['Emballage','packaged_kg','kg','reports/packaging'],['Distribution','distributed_kg','kg','reports/distribution'],['Rendement pondéré','average_yield','%','reports/yield'],['Flux emballé − distribué','net_finished_flow_kg','kg','reports/stocks']];
$activity=$summary['reception_count']+$summary['production_count']+$summary['packaging_count']+$summary['distribution_count'];
$observations=[];
if(!$activity)$observations[]=['Aucune opération validée','Vérifier la période, le site sélectionné et les opérations en attente.','reports/daily'];
if($summary['net_finished_flow_kg']<0)$observations[]=['Les sorties dépassent l’emballage de '.$num(abs($summary['net_finished_flow_kg'])).' kg','Consulter le stock disponible et les transferts avant de planifier les prochaines sorties.','reports/stocks'];
if($summary['production_count']&&$previousSummary['production_count']&&$summary['average_yield']<$previousSummary['average_yield'])$observations[]=['Rendement en recul de '.$num($previousSummary['average_yield']-$summary['average_yield'],1).' points','Examiner les lots et les machines concernés ; la composition de la production peut expliquer une partie de l’écart.','reports/yield'];
if($summary['waste_kg']>0)$observations[]=['Déchets générés : '.$num($summary['waste_kg']).' kg','Examiner leur valorisation et les pertes par lot. Les déchets traités peuvent provenir de périodes antérieures.','reports/waste'];
if(!$observations)$observations[]=['Lecture des volumes de la période','Compléter cette lecture avec les stocks actuels et les contraintes de production. Aucun objectif de performance n’est configuré ici.','reports/stocks'];
?>
<div class="butchery-workspace reports-executive">
<header class="butchery-heading report-print-header"><span class="butchery-heading-icon"><i class="bi bi-graph-up-arrow" aria-hidden="true"></i></span><div><p>Direction · Flux industriels</p><h2>Synthèse de direction</h2><small><?=e($period)?> · <?=e($periodDays)?> jour(s) · Généré le <?=e($generatedAt??date('d/m/Y H:i'))?></small></div></header>
<?php if(!$exporting):?>
<form method="get" action="<?=e(base_url('reports'))?>" class="report-compact-filters print-hidden">
<label><span>Du</span><input type="date" name="start_date" required value="<?=e($filters['start_date'])?>"></label><label><span>Au</span><input type="date" name="end_date" required value="<?=e($filters['end_date'])?>"></label>
<label><span>Fournisseur · réceptions</span><select name="supplier_id"><option value="">Tous</option><?php foreach($references['suppliers'] as $supplier):?><option value="<?=e($supplier['id'])?>" <?=(string)$filters['supplier_id']===(string)$supplier['id']?'selected':''?>><?=e($supplier['name'])?></option><?php endforeach;?></select></label>
<label><span>Machine · production</span><select name="machine_id"><option value="">Toutes</option><?php foreach($references['machines'] as $machine):?><option value="<?=e($machine['id'])?>" <?=(string)$filters['machine_id']===(string)$machine['id']?'selected':''?>><?=e($machine['name'])?></option><?php endforeach;?></select></label>
<button class="btn-primary" type="submit">Actualiser</button><a class="btn-secondary" href="<?=e(base_url('reports'))?>">Réinitialiser</a>
</form>
<div class="report-export-actions print-hidden"><span>Exporter cette synthèse</span><?php foreach(['excel'=>'Excel','pdf'=>'PDF','print'=>'Imprimer'] as $type=>$label):?><a class="btn-secondary" href="<?=e(base_url('reports?export='.$type.'&'.$query))?>" <?=$type!=='excel'?'target="_blank" rel="noopener"':''?>><?=e($label)?></a><?php endforeach;?></div>
<?php endif;?>
<p class="report-scope">Volumes validés du périmètre sélectionné. Le fournisseur filtre les réceptions ; la machine filtre la production et le traitement des déchets. L’emballage et la distribution restent au périmètre du site et des dates.</p>
<section class="report-decision-grid" aria-label="Points d’attention"><?php foreach($observations as $observation):?><article><h3><?=e($observation[0])?></h3><p><?=e($observation[1])?></p><?php if(!$exporting):?><a href="<?=e(base_url($observation[2].'?'.$query))?>">Examiner les détails <i class="bi bi-arrow-right" aria-hidden="true"></i></a><?php endif;?></article><?php endforeach;?></section>
<section class="report-kpi-grid" aria-label="Indicateurs clés"><?php foreach($indicators as $metric):$missing=$metric[2]==='%'&&!$summary['production_count'];?><article><span><?=e($metric[0])?></span><strong><?=$missing?'—':e($num($summary[$metric[1]],$metric[2]==='%'?1:0).' '.$metric[2])?></strong><?php if($metric[2]==='kg'&&$metric[1]!=='net_finished_flow_kg'):?><small><?=e($num($summary[$metric[1]]/$periodDays))?> kg / jour</small><?php elseif($metric[1]==='net_finished_flow_kg'):?><small>Flux de période, pas un solde de stock</small><?php else:?><small>Sortie ÷ entrée des lots validés</small><?php endif;?></article><?php endforeach;?></section>
<section class="table-panel butchery-history"><header class="fuel-section-heading"><div><h3>Évolution des résultats</h3><small>Comparaison : <?=e($previousPeriod)?> · même durée et mêmes filtres</small></div></header><div class="table-responsive"><table class="enterprise-table" data-datatable="false"><thead><tr><th>Indicateur</th><th>Période</th><th>Précédente</th><th>Écart</th><th>Variation</th><?php if(!$exporting):?><th>Détail</th><?php endif;?></tr></thead><tbody><?php foreach($indicators as $metric):$key=$metric[1];$current=$summary[$key];$before=$previousSummary[$key];$yield=$metric[2]==='%';$missing=$yield&&(!$summary['production_count']||!$previousSummary['production_count']);$delta=$current-$before;?><tr><td><strong><?=e($metric[0])?></strong></td><td><?=($yield&&!$summary['production_count'])?'—':e($num($current,$yield?1:0).' '.$metric[2])?></td><td><?=($yield&&!$previousSummary['production_count'])?'—':e($num($before,$yield?1:0).' '.$metric[2])?></td><td><?=$missing?'—':e(($delta>0?'+':'').$num($delta,$yield?1:0).($yield?' points':' kg'))?></td><td><?=$missing||$yield||$before<=0?'—':e(($delta>0?'+':'').$num($delta/$before*100,1).' %')?></td><?php if(!$exporting):?><td><a class="btn-secondary" href="<?=e(base_url($metric[3].'?'.$query))?>">Consulter</a></td><?php endif;?></tr><?php endforeach;?></tbody></table></div><p class="report-scope">« — » : comparaison non applicable ou base précédente nulle. Une hausse de volume n’indique pas à elle seule une amélioration de performance.</p></section>
<section class="table-panel butchery-history"><header class="fuel-section-heading"><h3>Activité de la période</h3></header><div class="table-responsive"><table class="enterprise-table" data-datatable="false"><thead><tr><th>Activité</th><th>Opérations</th><th>Volume</th></tr></thead><tbody><?php foreach($directionRows as $row):?><tr><td><?=e($row['label'])?></td><td><?=e($num($row['count']))?></td><td><?=e($num($row['quantity']))?> kg</td></tr><?php endforeach;?></tbody></table></div></section>
<?php if(!$exporting):?><nav class="report-detail-links print-hidden" aria-label="Rapports détaillés"><?php foreach(['daily'=>'Réceptions','production'=>'Production','stocks'=>'Stocks actuels','waste'=>'Déchets','packaging'=>'Emballage','distribution'=>'Distribution','yield'=>'Machines','supplier'=>'Fournisseurs'] as $path=>$label):?><a class="btn-secondary" href="<?=e(base_url('reports/'.$path.'?'.$query))?>"><?=e($label)?></a><?php endforeach;?></nav><?php endif;?>
</div>
<?php if(!empty($printMode)):?><script>window.print();</script><?php endif;?>
